### PR TITLE
Trusts: Iroha and Iroha II Spell Implementation

### PR DESCRIPTION
**Pull request by DotesMiqotes**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
Adds spell gambits for Iroha and Iroha II.
Adds `MPP` mods for both, and gives Iroha II `BLACK_MAGIC_CAST` -85 for her "near instacast" Flare II.
Removes lower tier versions of Protectra and Shellra from both spell lists.
Adds TODO messages for everything that still needs to be implemented.

## Steps to test these changes

I play tested the changes made to Iroha and Iroha II in a party with Fablinix and Moogle.

### CODE REVIEW

**Comment by zach2good** [comment]
I'd want some big fat TODO comments in these scripts; saying that this is not the full implementation for these Trusts. List the things that are missing, please.

Things that are only partially implemented tend to have a much lower chance of ever being finished than things that are completely missing. The "build it and they will come" initiative for giving people the tools to implement Trusts has failed - we may as well start accepting things piecemeal (not applicable to anything apart from Trusts, I'm not opening a free-for-all for people to be lazy).

**Comment by DotesMiqotes** [comment]
I can add those, and I understand. Implementing everything trust related is actually fairly high on my TODO list (currently working on Aldo). I have a little bit more done for these two trusts than what's here, nothing that I feel is 100% ready for a PR though.

It would actually be easier for me to implement trust features all at once, instead of trust by trust. The order would be something along the lines of teamwork messages > spells > mods (would include getting store tp working properly for trusts) > abilities > weaponskills > teamwork interactions.

**Comment by zach2good** [comment]
That may be easier for you, but we've witnessed these points many times over over the course of time:
- Things that are partially complete will be misconstrued as complete, and then never be revisited and actually completed.
- Contributors will start large bodies of work with the best of intentions, and then disappear for whatever reason - despite their most steadfast promises that they wouldn't do so. This leads to the first point.

So these things being said: for example, instead of submitting all missing Trust friendship texts at once etc., please submit each Trust as completely as you can. It'll also mean they get better and closer reviews.

**Comment by DotesMiqotes** [comment]
In that case, I'll keep the partially completed trusts [here](https://github.com/DotesMiqotes/server/tree/trusts). My main concern is saving work for anyone that can finish implementing a trust before me.

This spell implementation for Iroha I and II is mostly an extension of the work I was doing with trust spells in general, as well as fixing the minor issue of her potentially having access to lower tier protectra and shellra when she shouldn't.

**Comment by DotesMiqotes** [comment]
#6122

**Pull request closed without merging**
