### PR TITLE
[core] Fixed merit related heap errors

### PR DESCRIPTION
**Pull request by Omnione**
Fixed merit related heap errors
fixed dbtool.py

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Review by claywar — APPROVED** [review]

**Comment by claywar** [comment]
(Hopefully) Closes #1421

**Comment by Omnione** [comment]
Clay test this before merging please, (works on my machine)

**Comment by WinterSolstice8** [comment]
Spot checked Battuta and Inspiration in cat 2 RUN merits, still works.

**Review by zach2good — APPROVED** [review]
Tested on my side, couldn't trigger the warning 👍

**Review by claywar — APPROVED** [review]

**Pull request merged**
