### PR TITLE
Spell Tp correction and major cleaning

### PR DESCRIPTION
**Pull request by Xaver-DaRed**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to Topaz Next's [Limited Contributor License Agreement](https://github.com/DerpyProjectGroup/topaz/blob/info/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/DerpyProjectGroup/topaz/blob/info/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

- Cleaned magic.lua and bluemagic.lua, according to the style guide 
- Fixed enspell buff being aplied with the target and not the caster enhancing skill
- Fixed spells giving TP when dealing 0 damage

Credit to Mattyg for the TP fix

### CODE REVIEW

**Review by claywar — APPROVED** [review]

**Comment by TeoTwawki** [comment]
@Xaver-DaRed can you rebase to the new target branch? things will merge to freedom 1st, but I have that stable branch to maintain too, I don't want to just keep merging freedom into it - that could in the future cause me to pull multiple things in at once before all are ready. Freedom is like older topaz's canary branch: things land there first, but the base of each pr should be the stable branch.

**Comment by Xaver-DaRed** [comment]
Done

**Comment by TeoTwawki** [comment]
got an extra commit in it still

**Comment by Xaver-DaRed** [comment]
Fuck it. I'll do a new PR. I'm just making it worse

**Pull request closed without merging**
