### PR TITLE
Merge `feature/conquest_world_server` into `base`

### PR DESCRIPTION
**Pull request by zach2good**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

This is mainly for my own sanity to do another full review pass before merging into `base`. I think all points in all the other PRs are addressed and I'm happy with everything

### CODE REVIEW

**Comment by zach2good** [comment]
Anything I find that wants changing I can quickly fixup, now that this is all in an LSB-owned branch

**Comment by Xaver-DaRed** [comment]
This is also moving gobbie box daily tally to world, isnt it?
I ask because, while I do think it belongs to world, it isnt part of the conquest system

**Comment by claywar** [comment]
Its a lot more than conquest if you look at the time functions, so there's a bit of a disconnect in the branch name, though looking reasonable so far.  I would suggest perhaps renaming gobbie box to daily tally or something along those lines to be more specific

**Comment by zach2good** [comment]
I asked for the refactoring of time_server and gobbie box stuff as part of these PRs, to make the setup for conquest/besieged etc. easier in the future. 

gobbiebox/dailytally was already part of world server (since it only wants to be ran once per period). I asked for it to be renamed to gobbiebox, as thats the front-facing gameplay mechanic for accessing daily tally points. We can revert that back though if people want

**Review by claywar — APPROVED** [review]

**Comment by TeoTwawki** [comment]
"gobbiebox" is the npc part players interact with. the actual points being stored is referred to as daily tally both by the in game currency menu and by the npc dialogs. So when we're dealing with that number value part, makes more sense to call it by what SE did.

**Comment by zach2good** [comment]
- Added missing GPL headers to all files
- Used `#pragma` once at the top of headers
- Removed small data type file and added `influence_t` and `region_control_t` to `conquest_data.h` (there was a circular header dependency that was blocking that, so I fixed it)
- `gobbiebox::` -> `dailytally::`
- Jiggled a couple of other things I noticed around
- Messed up my interactive rebase, so I rebased again onto current main
- `./tools/run_clang_format.sh`

**Comment by zach2good** [comment]
Do not merge, I have some changes I want to make in ZMQ message handling

**Comment by zach2good** [comment]
OK, ready to go

**Review by Xaver-DaRed — APPROVED** [review]

**Pull request merged**
