### PR TITLE
Added Poppet Katars to droplist of NM

### PR DESCRIPTION
**Pull request by Aeltorian**
Adding Poppet Katars with latent and drop rate to Olgoi-Khurkoi in North Gustaberg (s)

**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Enables Poppet Katars to drop from Olgoi-Khurkoi in North Gustaberg (S). Created droplist 3285 to reflect proper droprate of Poppet Katars. Also, added the correct latent onto the weapon. 

## Steps to test these changes

Farm the worm and wish it'll drop. Checked latent and droprate.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
This is doing more than the title says, including changing the spawn type of the mob. please update both your pr titles AND commit messages to reflect and explain everything happened: I suggest just rebasing to one commit that contains detailed descriptions of all changes. DO NOT simply close the PR to start over. Force pushing your work to the same branch name will automatically update the PR so there is no reason whatsoever to close it. If you have trouble with rebasing, ask for help.

**Comment by Aeltorian** [comment]
Oh, I *did* change it. That was my mistake. I'll put that 128 back in when I recommit in the morning as I'm not at my desk. 

I don't know what you're talking about with closing a PR. I've only don't that with one of my first PRs. The one prior to this one,  I didn't close. Someone else did.

**Comment by TeoTwawki** [comment]
> I don't know what you're talking about with closing a PR. I've only don't that with one of my first PRs

I've seen so many pr's close and duplicates open this month that I've started preemptively telling people, it was not intended as some sort of scolding - people legit do not know that they don't have to

apologies for the tone of it

**Comment by Aeltorian** [comment]
> > I don't know what you're talking about with closing a PR. I've only don't that with one of my first PRs
> 
> I've seen so many pr's close and duplicates open this month that I've started preemptively telling people, it was not intended as some sort of scolding - people legit do not know that they don't have to
> 
> apologies for the tone of it

No worries. I have stoneskin. I've recommited the spawntype. Is there anything else I need to do as of this moment?

**Review by TeoTwawki — APPROVED** [review]

**Comment by TeoTwawki** [comment]
> > > I don't know what you're talking about with closing a PR. I've only don't that with one of my first PRs
> > 
> > 
> > I've seen so many pr's close and duplicates open this month that I've started preemptively telling people, it was not intended as some sort of scolding - people legit do not know that they don't have to
> > apologies for the tone of it
> 
> No worries. I have stoneskin. I've recommited the spawntype. Is there anything else I need to do as of this moment?

nope, we'll squash on merge to fix the commit message(s). What you have as your PR message is basically what we were looking for as your commit message as long as it covers everything happening (and we try to omit what Zach calls "ci dance").

**Pull request merged**
