### PR TITLE
[WIP] Rune Fencer Part 1

### PR DESCRIPTION
**Pull request by zach2good**
Shout out to MrSent and Apocarypse, on who's commits (`--author`'d) this PR is based.

**SCOPE:**
- RUN, up to Lv 10
- Add `battleutils::HandleRuneEffects` to handle rune effects and damage, alongside enspells, weapon effects, dnc effects etc.
- RUN job utils global
- DB entries
- Whatever core work needs to be done/cleaned up
- Animations? MrSent had some mapped out [here](https://github.com/LandSandBoat/server/commit/150a0eca234af507ae955d8216fdb62b43f326d3), do we need them?

**TODO:**
- `runefencer` vs `rune_fencer` etc.
- Research and observe the priority systems between enspells, dnc effects, weapon effects and rune enchantment effects.
- Research and observe which rune enchantment is chosen to give AE effects and damage when multiple are active, in regard to their strengths, elements, age etc.
- Unlock and get some early caps of RUN, so I can compare
- When casting more runes than your level will allow, the previous new and old rune will be visible together for just a moment. This is not retail accurate, there is no overlap moment!
- Sanitize and check all of the db entries (Abilities at Lv5 are messed up)

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by ShiyoKozuki** [comment]
Parry doesn't use your agi vs mobs dex and caps at 20%, not 25%(pre-Inquartata)

https://github.com/LandSandBoat/server/blob/base/src/map/utils/battleutils.cpp#L1804
https://www.bg-wiki.com/ffxi/Parrying_Skill
https://www.bluegartr.com/threads/120223-Agility-s-effect-on-Parrying-and-Shield-rate
https://www.bluegartr.com/threads/120223-Agility-s-effect-on-Parrying-and-Shield-rate?p=6042523&viewfull=1#post6042523 exactly where it says it for parry

**Comment by WinterSolstice8** [comment]
Is anyone working on this PR? I had previously worked on this independently ([here](https://github.com/WinterSolstice8/topaz/commit/e6a95c8c377fc1965dd6b102574820e0b5e147cf)) and would like to see RUN implemented. Can I pick up the work here?

Should I use this work as a base? Admittedly I am not familiar with how code "should" be done in this project and I may have written things not in line with what is expected.

**Comment by zach2good** [comment]
Feel free to pick this up, or use it as inspiration or start your own
thing. 👍

This isn't being actively worked on, but I would have come back to it
"eventually"

The only things you should be wary of:
- please submit work in sane, small-ish chunks, little and often. Otherwise
it's very hard for us to review. We can start a dedicated feature branch if
needed
- please stick to retail accuracy
- when doing calculations for things, please cite your sources and be
prepared to defend any assumptions you make. We're not trying to be
difficult, we just want to make sure the implementation is correct

Good luck!

**Comment by zach2good** [comment]
Also, any operation that happens a lot during regular game play (changing
runes, parrying, extending buffs onto other party members etc.) should be
handled in core for performance reasons :)

**Comment by WinterSolstice8** [comment]
> - please stick to retail accuracy
>- when doing calculations for things, please cite your sources and be
prepared to defend any assumptions you make. We're not trying to be
difficult, we just want to make sure the implementation is correct

Absolutely. That is my intent, I love this job very much in retail and would like more to experience it, though it doesn't look like we'll get accurate Rune Enchantment damage numbers right now. Nobody has seemed to have solved that, but I have an acquaintance math nerd on retail I might be able to bug because he too loves Rune Fencer... 

That said, by "core" I assume you mean in pure C++ code? I am not totally familiar here. My old work (Vivacious Pulse, Runes) were done solely in Lua. Runes work on a FIFO system and don't really need to be too complicated due to the fact the first rune in the buff list should always be the oldest -- but again, I am not familiar with the code. Perhaps this discussion is better left in new PRs with said features :)

**Comment by zach2good** [comment]
I'd be fine if you did the work in lua, and then I can come in afterwards
and move relevant bits down into C++ if that's easier.

I don't know much about RUN, but I think our damage and elemental
resistance numbers are historically all messed up, so you may struggle to
make things totally correct. Good enough is good enough though!

**Comment by TeoTwawki** [comment]
> I'd be fine if you did the work in lua, and then I can come in afterwards and move relevant bits down into C++ if that's easier. I don't know much about RUN, but I think our damage and elemental resistance numbers are historically all messed up, so you may struggle to make things totally correct. Good enough is good enough though!

So long as we don't mix up damage reductions of damage types with randomly resisting damage types, it should be ok. While not perfect the whole "nothing ever resists ever" feel of the old dsp code has been improved since xavers refactor. Neither he nor I know how since he didn't set out to fix that but something seems to be accidentally fixed there (I've had BLMs complaining ever since).

**Comment by zach2good** [comment]
Replaced by https://github.com/LandSandBoat/server/pull/1339 and similar PRs to `feature/rune_fencer`

**Pull request closed without merging**
