### PR TITLE
Remove unused parameters from Emela-ntouka setRespawnTime

### PR DESCRIPTION
**Pull request by claywar**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
Binding: `void CLuaBaseEntity::setRespawnTime(uint32 seconds)`

Removes second parameter from this script which provides no impact

## Steps to test these changes
No changes should be observed

### CODE REVIEW

**Review by TeoTwawki — COMMENTED** [review]
looks like it used to exist, since this is still in the comment block:
```
 *  Notes   : Haven't seen the second argument option being used
 *
 * Note: Removed optional (and unused) parameter 2:
 *      if (!lua_isnil(L, 2) && lua_isboolean(L, 2) && lua_toboolean(L, 2))
        { // set optional parameter to true to only modify the timer
            return 0;
        }
 ************************************************************************/
 ```

**Comment by claywar** [comment]
Given ` Removed optional (and unused) parameter 2` Is this something we want/need to support?

**Comment by TeoTwawki** [comment]
> Given ` Removed optional (and unused) parameter 2` Is this something we want/need to support?

I'm not sure why we ever did tbh

**Comment by TeoTwawki** [comment]
tell you what, if we need it later, lets give it its own function not a param

**Review by TeoTwawki — APPROVED** [review]

**Comment by zach2good** [comment]
This is also present in [Xolotl.lua](https://github.com/LandSandBoat/server/blob/4b87f4e35dc0f7dd43196eb90c61ea00599e31fa/scripts/zones/Attohwa_Chasm/mobs/Xolotl.lua#L10) if anyone wants a free PR

https://github.com/search?q=repo%3ALandSandBoat%2Fserver+mob%3AsetRespawnTime%280&type=code

**Pull request merged**
