### PR TITLE
RoV Crashing Waves

### PR DESCRIPTION
**Pull request by kaincenteno**
Added text ID for Mystic Retriever in Rulude Gardens' IDs.lua
Added reward in items.lua's table
Added correct info for Mystic Retriever in npc_list
Logic for giving reward if not enough space in inventory in NPC script
All logic for the mission is inside Rulude_Gardens' Zone.lua

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by Era-Lusiphur** [comment]
Eyeballing it it looks nice, but I have to wonder with the TODOs. I sometimes use event dumps and reason to help layout quests, but I always compare them to existing caps to ensure they're accurate in the end. It looks like all of the dialogue options here are unconfirmed. 

You PR'd this on the original Topaz and closed it out due to needing more research, but it looks largely the same for the conditions of the dialogue. Except now there's TODOs?

https://github.com/project-topaz/topaz/pull/1289

**Review by zach2good — APPROVED** [review]
> You PR'd this on the original Topaz and closed it out due to needing more research, but it looks largely the same for the conditions of the dialogue. Except now there's TODOs?

I don't remember the old PRs, but I would argue that this is probably the best we can do (and much better than leaving comment-only TODO's saying "probably needs research"):
```lua
            -- TODO: Needs research of when this dialog gets enabled. Have added a condition that makes sense to me.
            if player:getCurrentMission(COP) == xi.mission.id.cop.DARKNESS_NAMED then
                var2 = 1
            end

            -- TODO: Needs research of when this dialog gets enabled. Have added a condition that makes sense to me.
            if player:hasCompletedMission(xi.mission.log_id.COP, xi.mission.id.cop.DARKNESS_NAMED) then
                var2 = 1
                var3 = 1
            end
```

If we exhaustively search every cutscene for potential args and watch for all the potential changes in the cutscenes -- that's as good as we can reasonably do without running 3-6 characters through the entire game in different configurations to legitimately get the correct args.

Another way to try and make sure we catch things is to inspect the text in the event dumps, and compare that to the cutscene with arguments, with all zeroes, with all ones etc.

**Comment by zach2good** [comment]
Now that I go back and look at the old PR, it would be better to name these conditions like you did before:
```
            if player:hasCompletedMission(COP, tpz.mission.id.cop.DISTANT_BELIEFS) then
                metPrishe = 1
            end

            if player:getCurrentMission(COP) == tpz.mission.id.cop.DARKNESS_NAMED then
                prisheIsSick = 1
            end

            if player:hasCompletedMission(COP, tpz.mission.id.cop.DARKNESS_NAMED) then
                prisheIsSick = 1
                prisheIsHealthy = 1
            end
```

**Comment by Era-Lusiphur** [comment]
Ah, to clarify, @kaincenteno and I talked about this off the PR. My concern, which I suppose was poorly communicated here, was if anything was verified in some fashion with a capture or on retail. I agree there's a good middle ground using context and what's available to make reasonable assumptions, especially with something with so many potential variables.

**Comment by kaincenteno** [comment]
I'm kind of confused. Can you please enumerate what needs to be changed so I can go ahead and try and work on it if it's possible based on the captures available in Wiggo's awesome discord channel? 😸 

I changed the naming to var1 .. varN so it can make sense but i can revert that if needed too

**Comment by kaincenteno** [comment]
changed varnames to old PR in project-topaz

**Review by Era-Lusiphur — APPROVED** [review]

**Pull request merged**
