### PR TITLE
[Feature] Login Campaign (originally by kaincenteno)

### PR DESCRIPTION
**Pull request by zach2good**
I've rebased this onto `main`, patched up some broken bits and left a few TODOs for myself. Tested in Windurst, works fine (single day only).

Things I'm going to change:

- Code
  - General cleanup, it's already good to go, pretty much
 
- Settings
  - The campaign will be set as a Lua `os.date()`, with an additional length (in days)
  - These are easier and less wasteful to store

- Prizes
  - The fear we've had the entire time this has existed was about whether or not we're going to accumulate an entire back-history of prizes for every month there has been a Login Campaign. Absolutely not. We're going to have a single table, in some untracked place (the same as conf's and settings) that can be edited at will.
 

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by zach2good** [comment]
What do we want to do about the dates? I don't really want to force users to have to manually set a start date and a campaign length every time they want to run the campaign. I also don't want them to maintain a long list of when they want the campaign to start or repeat.

I think it would be very acceptable to set a start "numbered day of the month" and a campaign length, and let it run that way.

**Comment by claywar** [comment]
Can we extract that info from the version conf?

**Comment by kaincenteno** [comment]
> What do we want to do about the dates? I don't really want to force users to have to manually set a start date and a campaign length every time they want to run the campaign. I also don't want them to maintain a long list of when they want the campaign to start or repeat.
> 
> I think it would be very acceptable to set a start "numbered day of the month" and a campaign length, and let it run that way.

how about making it a param when running `topaz_game` like `topaz_game --login_campaign 8` the number meaning the number of days that the campaign should run for 8 days 😄  that way if the server crashes the server admin can just change the number. Also an ingame `!logincampaign` command would be good to end it early or extend it without having to make the server go down.

What do you guys think of that idea? 😸

**Comment by zach2good** [comment]
Ready for review, no longer WIP

I'm going to leave the current system of setting the dates in the script, since they are extracted into the CS and I'm too lazy to change it if it's already working and usable

**Comment by zach2good** [comment]
> how about making it a param when running topaz_game like topaz_game --login_campaign 8 the number meaning the number of days that the campaign should run for 8 days 😄 that way if the server crashes the server admin can just change the number. 

Nope, this is a normal way of setting things for people on Linux but our most common users are on Windows, where args are not as easy to use. I think using args for gameplay or event features will just lead to lots of bloat. Also also, are arg handling is very bad, best to leave it alone as much as possible.

> Also an ingame !logincampaign command would be good to end it early or extend it without having to make the server go down.

More admin tools being available through GM commands is probably a good idea, but it's outside of the scope of this PR. Any server-effecting command has to ripple out to all instances, not just the current one - and we don't have easy support for that yet

**Review by claywar — APPROVED** [review]

**Review by Xaver-DaRed — APPROVED** [review]

**Comment by TeoTwawki** [comment]
>  like topaz_game --login_campaign 8 the number meaning the number of days that the campaign should run

I dislike the pattern to doing settings-like things as arguments for anything _**except**_ basic exe behavior like logging controls.

**Pull request merged**
