### PR TITLE
SQL Gear Update

### PR DESCRIPTION
**Pull request by ghost**
Gear that was missing mods or was not able to equip, this just some gear I could get to at the time. I will update more in time as I come across them.

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by claywar** [comment]
Just a note on the style check fail, need to have a space after the initial `--` in comments to make all db imports happy.

**Comment by ghost** [comment]
So make like 4 spaces?

**Comment by claywar** [comment]
More like `; --<space here>Additional comment`

**Comment by ghost** [comment]
Ah I see. seems I did forget the damn space. That what happens when trying to add and over look. Thanks

**Comment by ghost** [comment]
Added some Odyssey Gear also at this time of Atonement 1 and Atonement 2 

I will add Atonement 3 and Atonement 4 at later time.

**Comment by zach2good** [comment]
Glad to see the sql sanity checks are working! Content seems fine, looks like there's another style point: our sql entries don't have spaces in them:
```
Thing(0, 0, 0);
```
Vs
```
Thing(0,0,0);
```

Ill look into writing a check for that today 👍

**Comment by ghost** [comment]
Ok I can try update the spaces.

**Comment by ghost** [comment]
Updated the Spaces that need removed

**Comment by TeoTwawki** [comment]
Regarding formatting I want to explain why the styling is what it is (we're not just being nitpicky I swear): we're matching the output of the command-line mysql dump tool (also what dbtool uses btw) so that in the event of a re-dump we don not see git claim that _all however many thousands_ lines are "changed" and can spot just the ones we need to when comparing.

Another tip: when you have the work you intended done, open the PR then and don't add more to it except to fix errors or address concerns raised in reviews, or alternatively open a draft instead of a pr so you can get assistance along the way and convert to pr "when its ready". In general its best to keep the scope of a pull request or draft from expanding to much. The bigger they get the longer review takes increasing the risk something else goes in first and then makes you rebased.

When I redid additional effects, it languished in rebase hell a long time because I touched a"busy" file in the core. I wound up with a not very nice looking script in order to get the core end in at the time that I still have to revisit.

**Comment by ghost** [comment]
Ok thanks for that info, when I do my next PR for future Gear Updates. As if now this one is completed with what I am able to add. It will take me some more time to add more and I will do New PR for that one.

**Review by claywar — APPROVED** [review]

**Pull request merged**
