### PR TITLE
Update missing/incorrect model id's for lockstyle items

### PR DESCRIPTION
**Pull request by CatsEyeXI**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Zach was nice enough to provide me with the model Id for Helgoland, so i went through the rest of his list and updated any missing/wrong models in the database.

## Steps to test these changes

Equip item, profit

image

### CODE REVIEW

**Review by WinterSolstice8 — APPROVED** [review]
Change requested: fix your aspect ratio :)

**Comment by CatsEyeXI** [comment]
> Change requested: fix your aspect ratio :)

omg, yes please, how, and what do i change it to??

**Comment by WinterSolstice8** [comment]
> omg, yes please, how, and what do i change it to??

Config -> Misc 2
image
It's probably supposed to be 16:9, though depends on your resolution.

**Comment by CatsEyeXI** [comment]
> > omg, yes please, how, and what do i change it to??
> 
> Config -> Misc 2 image It's probably supposed to be 16:9, though depends on your resolution.

omg that's so much better, thanks! <3

**Review by zach2good — APPROVED** [review]

**Pull request merged**
