### PR TITLE
Implemented Bailarin/Bailarina

### PR DESCRIPTION
**Pull request by hooksta4**
added bailarin/a to lottery spawn NM and associated loot tables IAW the table that has been passed around.

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by hooksta4** [comment]
Hold on this - I am getting a weird error when killing PH that I was not getting before hand. 

16/22 11:35:05:927][map][warning][warning] luautils::GetNPCByID NPC doesn't exist (17629663) (luautils::GetNPCByID:825)
[02/16/22 11:35:05:927][map][warning][warning] luautils::GetNPCByID NPC doesn't exist (17629664) (luautils::GetNPCByID:825)
[02/16/22 11:35:05:927][map][warning][warning] luautils::GetNPCByID NPC doesn't exist (17629665) (luautils::GetNPCByID:825)
[02/16/22 11:35:05:927][map][warning][warning] luautils::GetNPCByID NPC doesn't exist (17629666) (luautils::GetNPCByID:825)
[02/16/22 11:35:05:927][map][warning][warning] luautils::GetNPCByID NPC doesn't exist (17629667) (luautils::GetNPCByID:825)
[02/16/22 11:35:07:239][map][info][info] parse: 03A | 0313 0312 04 from user: Hook (parse:633)
[02/16/22 11:35:09:311][map][info][info] parse: 03A | 0318 0317 04 from user: Hook (parse:633)
[02/16/22 11:35:11:376][map][info][info] parse: 03A | 031D 031C 04 from user: Hook (parse:633)
[02/16/22 11:35:13:440][map][info][info] parse: 03A | 0322 0321 04 from user: Hook (parse:633)
[02/16/22 11:35:15:504][map][info][info] parse: 03A | 0327 0326 04 from user: Hook (parse:633)
[02/16/22 11:35:17:910][map][info][info] parse: 03A | 032D 032C 04 from user: Hook (parse:633)
[02/16/22 11:35:19:979][map][info][info] parse: 03A | 0332 0331 04 from user: Hook (parse:633)
[02/16/22 11:35:22:046][map][info][info] parse: 03A | 0337 0336 04 from user: Hook (parse:633)
[02/16/22 11:35:24:123][map][info][info] parse: 03A | 033C 033B 04 from user: Hook (parse:633)
[02/16/22 11:35:24:327][map][error][error] luautils::onMobDespawn: ...pts/zones/Quicksand_Caves/mobs/Spelunking_Sabotender.lua:14: attempt to index global 'ID' (a nil value)
stack traceback:
        ...pts/zones/Quicksand_Caves/mobs/Spelunking_Sabotender.lua:14: in function <...pts/zones/Quicksand_Caves/mobs/Spelunking_Sabotender.lua:13> (luautils::OnMobDespawn:3233)
[02/16/22 11:35:26:193][map]

Will take a look at it when I get home from work.

**Comment by TeoTwawki** [comment]
should catch them things before opening the pr :stuck_out_tongue_closed_eyes: 

its saying your value used in line 14 is nil which is where your PH ID is, so I am guessing you live edited your actual running server then copy pasted to your pr rather than testing your actual pr as a stand a lone build separately (improper testing, naughty!) so the code is probably alright but you got nailed by caching. But its complaining about npc instead of mob in the other lines, so you have a different error that also happened to get caught in your log quote also.

**Comment by hooksta4** [comment]
It looks like there was some ID shifts from NPCList in Quicksand caves, doesn't look like the ID's match up..??

**Comment by hooksta4** [comment]
> should catch them things before opening the pr 😝
> 
> its saying your value used in line 14 is nil which is where your PH ID is, so I am guessing you live edited your actual running server then copy pasted to your pr rather than testing your actual pr as a stand a lone build separately (improper testing, naughty!) so the code is probably alright but you got nailed by caching. But its complaining about npc instead of mob in the other lines, so you have a different error that also happened to get caught in your log quote also.

I am still getting the following error... Is there something I am missing to clear the cache?

[error][error] luautils::onMobDespawn: ...pts/zones/Quicksand_Caves/mobs/Spelunking_Sabotender.lua:14: attempt to index global 'ID' (a nil value)
stack traceback:
        ...pts/zones/Quicksand_Caves/mobs/Spelunking_Sabotender.lua:14: in function <...pts/zones/Quicksand_Caves/mobs/Spelunking_Sabotender.lua:13> (luautils::OnMobDespawn:3233)

**Comment by Xaver-DaRed** [comment]
You are missing a require in those mob scripts

**Comment by hooksta4** [comment]
> You are missing a require in that mob script

oh ffs.... thanks!

**Comment by hooksta4** [comment]
Also shout out to @Era-Lusiphur for the assist with Balarina!

**Review by Xaver-DaRed — APPROVED** [review]

**Pull request merged**
