### PR TITLE
beep

### LINKED ISSUE #1177: Lure of the Wildcat (Jeuno) - Bluffnix not replying
I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
I have checked the commit log to see if the issue has been resolved since my server was last updated
I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
I have specified what branch this happens on branch: 202102_1 (stable)

Additional Information (Steps to reproduce/Expected behavior) :

I am experiencing an issue with the "Lure of the Wildcat (Jeuno)" quest in which Bluffnix does not "flash his badge." All other characters involved in this quest seem to work properly. The LUA code for Bluffnix seems to imply he should work, but I also see that Gobbiebag logic was removed entirely to its own script, making me unsure how well I really understand the NPC-interaction process.

I experience this on whasf's "Oldschool" server. While the version reports as 202102_1 (stable), whasf does update it regularly (though in what capacity, I do not know), and it was just updated on 2022/01/04. If it helps: there are other players on the server that previously/successfully completed the aforementioned quest.

This is the first issue I'm reporting; I've tried to do as much due diligence as I can. (Unfortunately, without an active IRC channel, I see no way to vet/test possible issues with others before reporting.) I hope my efforts/report will be well-received. Thank you.

### PR DESCRIPTION
**Pull request by Noikar**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Closes #1177

### CODE REVIEW

**Comment by claywar** [comment]
Quests and Missions should generally be atomic in nature.  The right way to fix this is to convert Lure of the Wildcat (Jeuno) to interaction framework, and give Bluffnix's event the same priority (progressEvent, 1000).

**Comment by Noikar** [comment]
@zach2good and @jinxdojo asked me to PR this regardless (I no longer work on the server stuff) so I'm just gonna leave it here.

**Comment by zach2good** [comment]
👍

**Comment by Lynnea1320** [comment]
@zach2good  So you didn't want this? I literally pasted the code in advance so you could see what it was and you told me to PR it...

**Pull request closed without merging**
