### PR TITLE
Adds Ecphoria Ring Functionality

### PR DESCRIPTION
**Pull request by TonzoffunCE**
This item cures Amnesia status.

**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

This ring cures Amnesia status effect, this adds it's functionality.

### CODE REVIEW

**Comment by TonzoffunCE** [comment]
inb4: After posting this, I realized that this ring should not clear ALL amnesia status effects. It should not clear amnesia from Ladybugs or Rafflesia.

**Comment by TeoTwawki** [comment]
Don’t actually have to check “has” before deletion - delStatusEffect was made smart enough to just do nothing if the effect isn’t there.

If you need to omit some sources, those sources need to use the tier field and then the item script can do getStatusEffect():getTier() to check it

**Comment by TeoTwawki** [comment]
Don’t actually have to check “has” before deletion - delStatusEffect was made smart enough to just do nothing if the effect isn’t there.

If you need to omit some sources, tgose sources need to use the tier field and then the item script can do getStTusEffect()getTeir() to check it

**Comment by TeoTwawki** [comment]
Ugh..posting from mobile and can’t edit to spell that correctly atm

**Comment by TeoTwawki** [comment]
superseded by #4731

**Pull request closed without merging**
