### PR TITLE
db: p.stmt and query will now reconnect after disconnects

### PR DESCRIPTION
**Pull request by zach2good**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Using the new `db` command to test the connection:
```
[12/21/24 14:04:22:427][world][info] ZMQ Server listening... (message_server_init:426)
db
> Query successful: SELECT 1
> Prepared statement successful: SELECT 1
db
> Query successful: SELECT 1
> Prepared statement successful: SELECT 1
restarting MariaDB service
> Unknown command: restarting
db
[12/21/24 14:05:03:381][world][info] Connection lost, re-establishing connection and retrying query (attempt 1) (db::queryStr::<lambda_1>::operator ():149)
> Query successful: SELECT 1
> Prepared statement successful: SELECT 1
db
> Query successful: SELECT 1
> Prepared statement successful: SELECT 1
stopping MariaDB service
> Unknown command: stopping
db
[12/21/24 14:05:22:426][world][info] Connection lost, re-establishing connection and retrying query (attempt 1) (db::queryStr::<lambda_1>::operator ():149)
[12/21/24 14:05:24:479][world][critical] !!! Failed to connect to database, terminating server !!! (db::getConnection:66)
[12/21/24 14:05:24:479][world][critical] Could not connect to address=(host=127.0.0.1)(port=3306)(type=master) : Can't connect to server on '127.0.0.1' (10061) (db::getConnection:67)
PS C:\ffxi\server> 
```

### CODE REVIEW

**Comment by zach2good** [comment]
Updated the logic here:
- We no longer ping the db before _every_ query, this should result in a speedup. I'm quite hyped about this, so I'll go collect some numbers.
- We try every query. If it fails due to "lost connection" or "server went away" we'll rebuild the connection and try again n times (there's a setting for that)
- If _at any stage_ we try to build a connection to the db and it fails - the server needs to die. This is an ABSOLUTE MEGA FAILURE STATE and we absolutely don't want to try and recover from it. Sorry not sorry.

**Comment by zach2good** [comment]
Old system (with pinging, doesn't correctly safety check or reconnect):
```
db_perf_test
> db_perf_test queries took 173ms
> db_perf_test prepared statements took 181ms
db_perf_test
> db_perf_test queries took 158ms
> db_perf_test prepared statements took 158ms
db_perf_test
> db_perf_test queries took 243ms
> db_perf_test prepared statements took 176ms
db_perf_test
> db_perf_test queries took 160ms
> db_perf_test prepared statements took 166ms
db_perf_test
> db_perf_test queries took 160ms
> db_perf_test prepared statements took 154ms
```

New system (no pinging, will repair connection if it goes away):
```
db_perf_test
> db_perf_test queries took 135ms
> db_perf_test prepared statements took 136ms
db_perf_test
> db_perf_test queries took 130ms
> db_perf_test prepared statements took 135ms
db_perf_test
> db_perf_test queries took 132ms
> db_perf_test prepared statements took 149ms
db_perf_test
> db_perf_test queries took 151ms
> db_perf_test prepared statements took 129ms
db_perf_test
> db_perf_test queries took 139ms
> db_perf_test prepared statements took 133ms
```

Comparison, as generated by ChatGPT:

# Performance Comparison: Old vs. New DB System

Below is a brief, high-level comparison of the old system vs. the new system and how queries compare to prepared statements based on the data you provided.

---

## 1. Data Recap

### Old System

*(Has pinging, doesn’t always safety-check or reconnect properly)*

| Run | Queries (ms) | Prepared (ms) |
|-----|--------------|---------------|
| 1   | 173          | 181           |
| 2   | 158          | 158           |
| 3   | 243          | 176           |
| 4   | 160          | 166           |
| 5   | 160          | 154           |

- **Average (Queries)**  
  \[
    \frac{173 + 158 + 243 + 160 + 160}{5} = 178.8\,\text{ms}
  \]

- **Average (Prepared)**  
  \[
    \frac{181 + 158 + 176 + 166 + 154}{5} = 167\,\text{ms}
  \]

### New System

*(No pinging, automatically repairs connection if it fails)*

| Run | Queries (ms) | Prepared (ms) |
|-----|--------------|---------------|
| 1   | 135          | 136           |
| 2   | 130          | 135           |
| 3   | 132          | 149           |
| 4   | 151          | 129           |
| 5   | 139          | 133           |

- **Average (Queries)**  
  \[
    \frac{135 + 130 + 132 + 151 + 139}{5} = 137.4\,\text{ms}
  \]

- **Average (Prepared)**  
  \[
    \frac{136 + 135 + 149 + 129 + 133}{5} = 136.4\,\text{ms}
  \]

---

## 2. Observations

1. **New System is Faster Overall**  
   - Old system queries: **178.8 ms** on average  
   - New system queries: **137.4 ms** on average  
   - Old system prepared statements: **167 ms** on average  
   - New system prepared statements: **136.4 ms** on average  
   <br>
   The new system is roughly 20–40 ms faster on average for both queries and prepared statements.

2. **Prepared vs. Queries**  
   - **Old system**: Prepared statements (167 ms) are faster than raw queries (178.8 ms).  
   - **New system**: Prepared statements (136.4 ms) vs. queries (137.4 ms) are very close. Sometimes queries are slightly faster; sometimes prepared is.

3. **Consistency and Variance**  
   - The old system occasionally had large spikes (e.g., **243 ms** for queries).  
   - The new system’s worst outliers are less drastic (e.g., **151 ms** for queries, **149 ms** for prepared statements).  
   - Likely, the old system’s overhead from “pinging” and poor reconnection handling introduced more variance. The new system’s auto-repair logic provides more stable performance.

---

## 3. Possible Explanations

1. **Reduced Overhead**  
   Eliminating extra ping logic in the new system likely reduces overhead, trimming a few milliseconds off each test.

2. **Improved Connection Handling**  
   The old system didn’t properly handle reconnections, resulting in occasional spikes. The new system’s “repair if dropped” approach is more efficient and robust.

3. **Small Differences for Prepared Statements**  
   - Prepared statements help if you reuse the same query repeatedly.  
   - In this short test scenario, the differences can be small or overshadowed by network/driver overhead.  
   - The main gains in the new system come from improved connection handling rather than the query execution strategy itself.

---

## 4. Key Takeaways

- **Significant Speedup**: The new system consistently outperforms the old system for both raw queries and prepared statements.  
- **Lower Variability**: Performance in the new system is more tightly clustered, which points to better connection stability and less overhead.  
- **Prepared vs. Queries**: Prepared statements are marginally faster or on par with queries in these tests. The biggest win is still from the new connection handling and eliminating ping overhead.

**Comment by zach2good** [comment]
So, roughly:

Queries: ~23% faster
Prepared statements: ~18% faster

On our slowest, most frequent, and most blocking system.

**Review by claywar — APPROVED** [review]

**Comment by zach2good** [comment]
and for fairness, I built the same test harness for the old system, which has: zero thread safety, zero convenience, entirely global state, no resilience or self repair, no prepared statements, server-based string escaping, etc.

```
db_perf_test
> db_perf_test queries took 133ms
db_perf_test
> db_perf_test queries took 138ms
db_perf_test
> db_perf_test queries took 123ms
db_perf_test
> db_perf_test queries took 130ms
db_perf_test
> db_perf_test queries took 147ms
```

Pretty much the same as the new system, with slightly more variance?

**Comment by zach2good** [comment]
This pretty much wraps up and confirms that the new db system is ready for primetime - it does everything the old system does, as fast, with many many more bells and whistles.

**Comment by StabbyCutyou** [comment]
Apologies as I'm coming in post-merge but, on the approach to retry queries N times, is there a risk that a write is accepted, then an error occurs as the response is being sent to the client (a read timeout, a socket error of some kind, etc), then you retry the write and end up in a bad state? I can see you're scoping it to a limited set of exceptions, but wondering if it's possible for this case to appear with one of those errors.

Fairly odd edge case to consider, but just wondering if you think that might be an issue to look out for.

I'm also curious if you've considered a connection pooling approach, as typically they'll handle always ensuring the caller gets a clean connection (and increase throughput at the cost of a bit of general latency) but that is probably a different discussion that you've already had somewhere else.

**Comment by zach2good** [comment]
In terms of what might affect the game, players, and game state data: I don't think we need to worry about multiple query retry. If we try to insert twice we'll be inserting to the same item slot, if we try to delete twice the second delete will be moot, etc.

Connection pooling is a tough one, it's on my list of things to do. The MariaDB connectors we use (C and C++ versions) don't provide all the flags and options they claim to - including pooling, auto-reconnect, etc. This is why I've done the reconnection logic manually. At some point I'll handle doing connection pooling manually, but that'll likely come after the other db, ASIO, and worker thread work I have upcoming.

**Comment by StabbyCutyou** [comment]
Makes sense, you would definitely know more than I there wrt the risk to game state.

On the latter, I didn't see any native pooling in the driver so I assume it means you need to roll your own, which... Always fun. Also makes sense if it's not a genuine priority at the moment. I'd definitely be interested in learning and following along with the async io / worker thread stuff (obsessed with digging into the codebase ATM, and apologies for distracting so many recent prs/issues).

Thanks!

**Comment by zach2good** [comment]
If you're interested in following along, I'm tinkering on the general layout for ASIO here: https://github.com/zach2good/asio_coro_test/blob/main/main.cpp

Once I get the Tracy profiler working nicely with coroutines/fibers I'll rebuild connect/search/world exes to use ASIO+Coros in this way

**Comment by StabbyCutyou** [comment]
Now this is exciting stuff! Familiar with it from other languages but not
cpp, will definitely follow along!

**Pull request merged**
