### PR TITLE
[sql] NM: Bastet

### PR DESCRIPTION
**Pull request by CatsEyeXI**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
Adds missing NM: Bastet (Sanc. of ZiTah)
https://www.youtube.com/watch?v=PUtcCE5Sa1k
PCAP just submitted in the captures discord

## Steps to test these changes
!gotoid 17273190

### CODE REVIEW

**Review by Xaver-DaRed — APPROVED** [review]

**Review by zach2good — APPROVED** [review]
I can only assume the changes in `mob_pools` are the immunities and weaknesses Bastet has to things 👍

**Comment by TeoTwawki** [comment]
> I can only assume the changes in `mob_pools` are the immunities and weaknesses Bastet has to things 👍

image

1817 [immunity](https://github.com/LandSandBoat/server/blob/6f7d3c3ce7f308e408d8b7ee8c4715fead3a7718/src/map/entities/battleentity.h#L457) = sleep, stun, silence, poison elegy, requiem


98 "flag" = we don't even use this field, we use the ones "name prefix" (left of it) next to it, "entityFlags" (right of it)

493 = the spell list added in this pr

and that 0 is the skill list, making this mob use no tp skills at all


@CatsEyeXI did you mean to edit "flag" or was that meant for another field? what's the source of that value?

**Comment by Xaver-DaRed** [comment]
The mob was capped
```sql
[17273190] =
{
    ['id']=17273190,
    ['name']="Bastet",
    ['polutils_name']="Bastet",
    ['type']="Equipped NPC",
    ['index']=358,
    ['level']=62, 
    ['x']=-275.021, ['y']=-0.463,   ['z']=204.891,  ['r']=222,
    ['flag']=98,
    ['speed']=60, ['speedsub']=60,
    ['animation']=0,  ['animationsub']=8,
    ['namevis']=0,
    ['status']=1,
    ['flags']=667,
    ['name_prefix']=32,
    ['look']="00006F01,
    ['raw_packet']="0E1C4D0666910701660107DEB08289C3560EEDBE19E44C43620000003C3C6400019B020000100020000008000000000000006F0100000000",
},
```

**Comment by TeoTwawki** [comment]
Silence Gravity Sleep Bind would be 0x17 or 23

**Comment by TeoTwawki** [comment]
> The mob was capped ` [17273190] = {['id']=17273190, ['name']="Bastet", ['polutils_name']="Bastet", ['type']="Equipped NPC", ['index']=358, ['level']=62, ['x']=-275.021, ['y']=-0.463, ['z']=204.891, ['r']=222, ['flag']=98, ['speed']=60, ['speedsub']=60, ['animation']=0, ['animationsub']=8, ['namevis']=0, ['status']=1, ['flags']=667, ['name_prefix']=32, ['look']="00006F01", ['raw_packet']="0E1C4D0666910701660107DEB08289C3560EEDBE19E44C43620000003C3C6400019B020000100020000008000000000000006F0100000000",},`

just making sure he didn't mean to edit the field next to it, since that field _does nothing_ and a source for the value wasn't cited before hand _by him_

**Comment by CatsEyeXI** [comment]
> > I can only assume the changes in `mob_pools` are the immunities and weaknesses Bastet has to things 👍
> 
> image
> 
> 1817 [immunity](https://github.com/LandSandBoat/server/blob/6f7d3c3ce7f308e408d8b7ee8c4715fead3a7718/src/map/entities/battleentity.h#L457) = sleep, stun, silence, poison elegy, requiem
> 
> 98 "flag" = we don't even use this field, we use the ones "name prefix" (left of it) next to it, "entityFlags" (right of it)
> 
> 493 = the spell list added in this pr
> 
> and that 0 is the skill list, making this mob use no tp skills at all
> 
> @CatsEyeXI did you mean to edit "flag" or was that meant for another field? what's the source of that value?

thank you for clearing up the immunities, i've adjusted as requested. as discussed, i took flag from the pcap i recorded. I understand it's not used in our codebase so moving forward I will not bother to update it.

**Review by TeoTwawki — APPROVED** [review]

**Comment by TeoTwawki** [comment]
kicked hamster cage to re-run failed CI jobs

**Pull request merged**
