### PR TITLE
Patrol Rework Proposal

### PR DESCRIPTION
**Pull request by jmcmorris**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Moving patrol logic over into C++ primarily to introduce the ability for specifying wait times and rotations in patrol points. This will clean up many scripts and simplify the patrol interface. Overall there should be a small performance gain as now patrols are handled at spawn and not during scripts' `onPath`.

Because wait and rotations are both optional I decided to also try making the x/y/z values optional as well. If a coord value is not provided then it will use the last defined value.

Mobs will now automatically resume patrol when roaming. This removes the need to do it in each script.

Interacting with an NPC now only pauses their pathing rather than completely clearing it.

If accepted then I will make a follow-up PR with all of the scripts that use patrol to use this new patrol.

## Steps to test these changes

Observe the pathing of any of the changed npcs/mobs

### CODE REVIEW

**Comment by kaincenteno** [comment]
glad to see you around @jmcmorris  :D 

totally happy to see you working on patrol.

I created an issue last month about it, pasting it here https://github.com/LandSandBoat/server/issues/2463

thanks for adding tools to make NPCs more lively :D

**Comment by jmcmorris** [comment]
> glad to see you around @jmcmorris :D
> 
> totally happy to see you working on patrol.
> 
> I created an issue last month about it, pasting it here #2463
> 
> thanks for adding tools to make NPCs more lively :D

Thanks! I didn't even see that issue but happy to know that it is desired! My main motivation is to use this for Limbus which extensively uses mob patrols.

**Comment by kaincenteno** [comment]
> > glad to see you around @jmcmorris :D
> > totally happy to see you working on patrol.
> > I created an issue last month about it, pasting it here #2463
> > thanks for adding tools to make NPCs more lively :D
> 
> Thanks! I didn't even see that issue but happy to know that it is desired! My main motivation is to use this for Limbus which extensively uses mob patrols.

yeah the NPCs walk funky currently when moving from point to point as the make a quick weird stop shake/rotate and they keep walking. I dont have access to limbus on retail but I am happy to help on anything NPC pathing on cities :D (also this pathing would be helpful on those Wing of the Goddess missions that you have to follow an NPC around an area [forgot the name of the quests name])

**Comment by jmcmorris** [comment]
> yeah the NPCs walk funky currently when moving from point to point as the make a quick weird stop shake/rotate and they keep walking. I dont have access to limbus on retail but I am happy to help on anything NPC pathing on cities :D (also this pathing would be helpful on those Wing of the Goddess missions that you have to follow an NPC around an area [forgot the name of the quests name])

I think we have all of the captures for limbus. I have fixed up some of the pathing on NPCs and some of the mobs but it isn't perfect. Sometimes there are lots of patrol point entries which seems to cause them to slow down sometimes since they are so close to each other. These could likely be cleaned up by going through them and reducing the entries. Once I have this all done you're more than welcome to go through and clean them up further.

**Comment by TeoTwawki** [comment]
> > yeah the NPCs walk funky currently when moving from point to point as the make a quick weird stop shake/rotate and they keep walking. I dont have access to limbus on retail but I am happy to help on anything NPC pathing on cities :D (also this pathing would be helpful on those Wing of the Goddess missions that you have to follow an NPC around an area [forgot the name of the quests name])
> 
> I think we have all of the captures for limbus. I have fixed up some of the pathing on NPCs and some of the mobs but it isn't perfect. Sometimes there are lots of patrol point entries which seems to cause them to slow down sometimes since they are so close to each other. These could likely be cleaned up by going through them and reducing the entries. Once I have this all done you're more than welcome to go through and clean them up further.

Worth noting 90% of LSB's npc's have incorrect speed values that make it worse/more pronounced stutter-stepping. it's also more noticeable on shorter paths, like the pacing NPC in port jeuno tends to slide and stutter more than say Raminel. There are objects that actually _change speed_ during their movements too, but that's rare for NPCs so far. I've made a small addon that shows me this data on demand without having to dig through packet caps and I've been investigating speed issues so hopefully that gets better soon but anyone working on the stutter issue is going to want to make sure the object they work with is one with "known good" speed values.

Lots of patrol points causes execution to slow to a crawl and they super stutter (Cactrot rapido did this before I wrecked his node table)

**Comment by TeoTwawki** [comment]
Lots of patrol points causes execution to slow to a crawl and they super stutter (Cactrot rapid did this before I wrecked his node table)

**Comment by kaincenteno** [comment]
> he pacing NPC in port jeuno tends to slide and stutter more than say Raminel. There are objects that actually _change speed_ during their movements too, but that's rare for NPCs so far. I've made a small addon that shows me this data on demand without having to dig through packet caps and I've been investigating speed issues

I just capture the NPC while its moving back and forth and track the last x y z position before they change their rotation value. this gives me simple tables with only the necesary information =)

**Review by TeoTwawki — APPROVED** [review]
I like this

**Review by Xaver-DaRed — APPROVED** [review]
If Teo likes it, that's all I need.

**Comment by jmcmorris** [comment]
Great! I'll work on getting the rest of the scripts ported over to this new patrol method and make a new PR.

**Comment by claywar** [comment]
Heads up, #2727 is going to cause some table pain for potential conflicts.

**Pull request merged**
