### PR TITLE
[core] [cmake] [linux] Add "backward" trace stack for Linux

### PR DESCRIPTION
**Pull request by WinterSolstice8**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Adds a traceback print to linux upon crash, see pic

image

## Steps to test these changes

force crash applications, see cool traceback
May need debug mode and not just release with symbols.

Drafted for OSX CI.

### CODE REVIEW

**Comment by WinterSolstice8** [comment]
Apparently I need to add deps for linux CI, makes sense. Ubuntu wants `binutils-dev`

**Comment by WinterSolstice8** [comment]
`brew install binutils` may work for MacOS depdendencies

EDIT: binutils is sorta part of clang for MacOS and it doesn't need an extra dependency or link

**Comment by WinterSolstice8** [comment]
Ok, I think this is ready for review.

P.S. according to their docs, "backward" supports Windows but I hadn't tested how it compares to our current implementation on Windows.

**Comment by WinterSolstice8** [comment]
One thing I should note: The traceback generation on full debug mode on Linux takes quite some time for my poor 4 core ARM VPS,
```
[09/24/22 18:21:17:784][map][info] Console input thread exiting... (operator():116)
[09/24/22 18:23:16:129][map][critical] Stack trace (most recent call last):
```

Just under 2 minutes.

**Review by zach2good — APPROVED** [review]
Looking good 👍

If you're not entirely sick of this, can you move the Linux crash/Debug logic out of kernel and into debug_linux? Trying to kill kernel

**Comment by WinterSolstice8** [comment]
> If you're not entirely sick of this, can you move the Linux crash/Debug logic out of kernel and into debug_linux? Trying to kill kernel

Will look into this, I think "backward" might hook into signals in ways that might not be compatible with the current setup unless you're in a crash state already (which is what is currently being used)

**Comment by WinterSolstice8** [comment]
Latest changes seem to preserve Windows crash handler as I had hoped:

```
[09/25/22 11:08:30:513][map][info] Current State Top: 0, Total Memory Used: 67393kb (luautils::garbageCollectStep:290)
crash
=====================================================
!!! CRASH !!!
Exception code: C0000005 (ACCESS_VIOLATION)
Fault address: 00007FF60EF8DE32 01:000000000009CE32
Process Name: G:\dev\server\xi_map.exe
Full crash report: G:\dev\server\dmp\xi_map.exe_25-9_11-8-42.log
Memory dump: G:\dev\server\dmp\xi_map.exe_25-9_11-8-42.dmp
Time of crash: 2022/09/25 11:08:42
Process Uptime: 84 seconds
```

**Pull request merged**
