### PR TITLE
[RUN] Add core mods for Rune Fencer

### PR DESCRIPTION
**Pull request by zach2good**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by zach2good** [comment]
I don't know anything about Rune Fencer, let me know if we should rename these, add things etc.

**Comment by WinterSolstice8** [comment]
Inquartata can stay as "Inquartata", it's not a RUN specific thing, though it's their "featured trait" much like Fast Cast and RDM. BLU can get it as a trait via SOA spells and there's a couple gear slots that add it directly. Just like Fast Cast, +1 = +1%.

I forgot that SE went on a standardization of bonuses for new gear and to not hide effects, so things like 'Enhances "Fast Cast" Effect' got changed to show their real values/effects. So I should've looked at the +3 versions not the NQs for effect names...
`ENHANCES_PFLUG` -> `PFLUG` is just a direct % bonus added to the base % effect
`ENHANCES_VALIANCE_VALLATION` -> `VALIANCE_VALLATION_DURATION`
`ENHANCES_VIVACIOUS_PULSE`-> `VIVACIOUS_PULSE_POTENCY`

double checked for more RUN specific stuff  in JSE/augs/ambuscade gear to be added:
`RAYKE_DURATION`
`ODYLLIC_SUBTERFUGE_DURATION`
`SWIPE`
`LIEMENT_DURATION`
`GAMBIT_DURATION`
`EMBOLDEN_DURATION`
`LIEMENT_EXTENDS_TO_AREA` <- this one is a RUN "mythic weapon" bonus, I don't know if this effect should go somewhere else. There is also the same mythic weapon hidden % bonus to the associated weapon skill, `Dimidiation`
I can't find any more but it should cover most bases

**Comment by zach2good** [comment]
Okidoki, updated. If we need to add more later it isn't a problem 👍

**Review by claywar — APPROVED** [review]

**Review by Xaver-DaRed — APPROVED** [review]

**Comment by WinterSolstice8** [comment]
Looks perfect to me. Thanks a ton for this!

**Pull request merged**
