### PR TITLE
Add Storm and Helix Plumbing to Trust Adelheid

### PR DESCRIPTION
**Pull request by neuromancerxi**
Adds Gambits and related pieces to allow Adelheid to leverage Storms and Helix.
Currently both are only based on the day of week instead of mob weakness.
Left TODO: notes for remaining missing pieces.

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Creates Gambits for Storms and Helix based on Day of the Week.
Adds Gambits to Adelheid to cast Storms and Helices with checks to only cast when they are missing.

## Steps to test these changes

Cast Adelheid Trust
Note the Day of the Week
Engage a mob
Adelheid will cast Storm/Helix spells corresponding to the day and replace them when they wear off.

### CODE REVIEW

**Review by WinterSolstice8 — APPROVED** [review]
looks good to me

**Review by claywar — APPROVED** [review]

**Comment by Omnione** [comment]
I’m wondering if that hasStorm check can be simplified with effect flag checking, not sure if storms have a unique effect flag or not

**Comment by TeoTwawki** [comment]
> I’m wondering if that hasStorm check can be simplified with effect flag checking, not sure if storms have a unique effect flag or not

Nope. And using the list in hasStatusEffect there in core was actually more efficient. Also, today I learned hasStatusEffect can take a list/table.

**Comment by Omnione** [comment]
> 

Yeah I must admit, seeing that list kinda threw me for a second, did not know you could do that

**Pull request merged**
