### PR TITLE
Adjust merit weaponskill wsc calculations for  issue #998

### PR DESCRIPTION
**Pull request by RAIST5150**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by RAIST5150** [comment]
ACK!  Brain fart... gotta go back and make it use 0.03 on the SoA rules.

**Review by Xaver-DaRed — APPROVED** [review]
Seems to line up with https://forum.square-enix.com/ffxi/threads/32909-April-30-2013-%28JST%29-Version-Update?p=425562&viewfull=1#post425562

I hate how this scripts are aligned, but that isn't on you.

**Comment by RAIST5150** [comment]
> 
> 
> Seems to line up with https://forum.square-enix.com/ffxi/threads/32909-April-30-2013-%28JST%29-Version-Update?p=425562&viewfull=1#post425562
> 
> I hate how this scripts are aligned, but that isn't on you.

Yeah... I though about breaking out each wsc decleration to their own line while in there or something, but knowing me... I'd leave trailing spaces all over the place.

Such a blonde sometimes it scares me... as evidenced by me making SoA rules grossly OP on the first pass.

**Comment by TeoTwawki** [comment]
I know you did add further description after the main "update filename" line but we're likely to do a squash when we merge to get rid of "update filename" and combine what are essentially the same message down to 1 commit.

Future considerations: it is possible to attain these without the merit, via an aeonic weapon. when attained in such a way, it is full power without merits so eventually we'll need to worry about that (not in this PR we won't! Those don't _exist_ yet as far as I am concerned)

**Pull request merged**
