### PR TITLE
Updated example modules still using PrintToPlayer into lowercase

### PR DESCRIPTION
**Pull request by AppleCronch**
…tToPlayer.

**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Updates the example modules to follow the changes from #4842. Would save someone new from trying to figure out and troubleshoot why their NPC won't talk

## Steps to test these changes

Initialize example modules and they should properly print to player.

### CODE REVIEW

**Review by TeoTwawki — APPROVED** [review]

**Review by WinterSolstice8 — APPROVED** [review]

**Comment by WinterSolstice8** [comment]
CI error is that your commit title is too long, can amend with a shorter one and force push back

**Comment by TeoTwawki** [comment]
> Commit title is too long.
Maximum length is 72 characters.
If you need to provide a more detailed summary of your changes you should provide a multi-line commit message

(╯' ')╯︵ ┻━┻

I'm really sorry @AppleCronch, could you amend the commit to add a line break for this so the CI passes?

**Comment by AppleCronch** [comment]
Ooops sorry, amended

**Comment by TeoTwawki** [comment]
> Ooops sorry, amended

no your ok, ***I'm*** sorry you have to deal with the CI thinking we're in the early 80's when a large monitor was 640 by 480.

_cough_

**Pull request merged**
