### PR TITLE
[packets] Use 9/7 bit setters everywhere for packet type and size

### LINKED ISSUE #1253: Invalid Packet Size For `menu_unity` Packet
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

See file here: https://github.com/LandSandBoat/server/blob/base/src/map/packets/menu_unity.cpp#L48

The usage here is incorrect as setting the size directly does not correctly make use of the proper id and size packing. Instead, this causes the packet to be treated as `0x8C * 2` which causes the packet builder to crash from reading beyond the packet buffer limit of 260 bytes.

This should instead be set using the newer `id(..)` and `length(..)`  helpers to correct the problem.

The other sets in the file need to be fixed as well:
https://github.com/LandSandBoat/server/blob/67f34fc7eb251d5f006d5210ff302099ab94c78e/src/map/packets/menu_unity.cpp#L60
https://github.com/LandSandBoat/server/blob/67f34fc7eb251d5f006d5210ff302099ab94c78e/src/map/packets/menu_unity.cpp#L76
https://github.com/LandSandBoat/server/blob/67f34fc7eb251d5f006d5210ff302099ab94c78e/src/map/packets/menu_unity.cpp#L92
https://github.com/LandSandBoat/server/blob/67f34fc7eb251d5f006d5210ff302099ab94c78e/src/map/packets/menu_unity.cpp#L103
https://github.com/LandSandBoat/server/blob/67f34fc7eb251d5f006d5210ff302099ab94c78e/src/map/packets/menu_unity.cpp#L115
https://github.com/LandSandBoat/server/blob/67f34fc7eb251d5f006d5210ff302099ab94c78e/src/map/packets/menu_unity.cpp#L132
https://github.com/LandSandBoat/server/blob/67f34fc7eb251d5f006d5210ff302099ab94c78e/src/map/packets/menu_unity.cpp#L149

### PR DESCRIPTION
**Pull request by zach2good**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [🤞] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

Fixes https://github.com/LandSandBoat/server/issues/1253

WIP Until I test it

I marked all the packets that need investigation with `// TODO`, you can also search for them with `// 0`

### CODE REVIEW

**Comment by zach2good** [comment]
Relevant: https://github.com/LandSandBoat/server/issues/178

**Comment by zach2good** [comment]
And this: https://github.com/LandSandBoat/server/issues/177

**Comment by claywar** [comment]
Adding comment here so it doesn't get lost from the other PR:
TODO: A little documentation on setSize() to say what the old style was, what the new style is, etc.

**Comment by claywar** [comment]
Spent a few hours hitting basic function across multiple systems yesterday evening.  No issues so far.

**Comment by zach2good** [comment]
I'd say we should put off merging this until we've dealt with the incoming horror that will be the Feb update

**Review by claywar — APPROVED** [review]

**Pull request merged**
