### PR TITLE
Fix Lua onItemCheck

### PR DESCRIPTION
**Pull request by The-Aerec**
onItemCheck was incorrectly returning the user in two parameters instead of the item in the second param slot

**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

This PR fixes onItemCheck to actually allow the item being used during the check to be referenced instead of the caster. The function is defined as: 

`OnItemCheck(CBaseEntity* PTarget, CItem* PItem, ITEMCHECK param, CBaseEntity* PCaster)`

and was returning the following:

`Target, Caster, param`

it now returns:

`result = onItemCheck(CLuaBaseEntity(PTarget), CLuaItem(PItem), static_cast<uint32>(param), caster)`

## Steps to test these changes

Reference item anywhere in onItemCheck

print(item) to see that you are indeed referencing an CLuaItem instead of CLuaBaseEntity

### CODE REVIEW

**Comment by zach2good** [comment]
So caster is now unused?

**Comment by The-Aerec** [comment]
> So caster is now unused?

Yes, I can extend or modify the function to include the caster again. Or just change the place of the item return. Up to yall. Item was actually never being returned so you could never check anything about the item in onItemCheck

**Comment by The-Aerec** [comment]
I have added caster to its proper place: 
`OnItemCheck(CBaseEntity* PTarget, CItem* PItem, ITEMCHECK param, CBaseEntity* PCaster)`

`auto result = onItemCheck(CLuaBaseEntity(PTarget), CLuaItem(PItem), static_cast<uint32>(param), caster)`

**Comment by zach2good** [comment]
There's code that expects the original layout (note the comma):
image

I agree with you about matching the C++ signature: `std::tuple<int32, int32, int32> OnItemCheck(CBaseEntity* PTarget, CItem* PItem, ITEMCHECK param, CBaseEntity* PCaster)`

So you'll need to change the existing onItemCheck usages, plus replace the original simplest version with the new extended version:

```
itemObject.onItemCheck = function(target, player)
and
itemObject.onItemCheck = function(target)

to

itemObject.onItemCheck = function(target, item, param, caster)
```

and make sure everything matches up in the `itemObject.onItemCheck = function(target, player)` case etc.

**Comment by The-Aerec** [comment]
Zachs request has been compeleted:
Please note I can't test every item in the game!

**Review by zach2good — APPROVED** [review]
I checked ccb_polymer_pump, all looks fine :+1:

In the future, typically, you'd make the smaller logical changes or more sensitive changes in their own commit, and then the huge 2000+ file find/replace changes in another commit so things are more easily reviewable.

**Pull request merged**
