### PR TITLE
[Proposal] Create mobskill enum file

### PR DESCRIPTION
**Pull request by Xaver-DaRed**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Proposes the creation of an enum file with all mobskill IDs

This PR contains all entries of "foot kick", "sheep song", etc... among others

I could have added more, however, I rather know everyones opinion before commiting to add 4000 entries by hand.
This gives a clear example of what the file would look like and allows for certain patterns to be recognized.

Its use would be to be able to have tables with mobskill info, like we do for spells, for instance. Or at least to not use raw IDs in mob family scripts and such.

## Steps to test these changes

None

### CODE REVIEW

**Comment by zach2good** [comment]
I'm not against it, but maybe we should name things based on where they're used. RANGED_ATTACK_GOBLIN instead of _1 etc.?

**Comment by zach2good** [comment]
(only for skill names that are repeated, obviously)

**Comment by jmcmorris** [comment]
I like this as I see it one step moving towards being able to arbitrarily add/remove mobskills from a mob entity - either during initialization or during combat for a phase change or whatever.

**Comment by zach2good** [comment]
(out of scope of this PR, but worth starting this conversation)

Historically, an issue we have with dynamic lists (think mob skill lists, and lists of mob loot) - is how we'd track them and changes to them over time.

- If a mob starts with skill list A, it uses it, it dies, it respawns and continues to use skill list A
- If a mob starts with skill list A, changes to B at runtime, then it respawns and is set back to using skill list A
- If a mob starts with skill list A, has "RANGED_ATTACK_GOBLIN" added, then respawns and is set back to using skill list A

I think in the past one of the worries is about duplication of data - if there are 1024 mobs per zone (not always, but lets use it for the maths), and each mob has 3 skills in their list, and there are 300 zones, that's 921'600 entries across all mobs - which is cut down significantly by doing list lookups.

We had a drop list + modification list thing for treasure pools a while ago, but it was replaced with something else.

This sort of thing will need some planning is all.

**Comment by jmcmorris** [comment]
I agree this needs planning and is completely out of scope for this PR. This is the sort of thing I have had to worry about a lot in my personal gamedev. Here are my thoughts:

- First, it is possible to store this mob list on each mob as a vector<uint16>. The uint16 can function as a lookup to the mobskill since the mobskills are stateless they can be shared between all mobs. This would keep the data down to likely only a few MB in memory for all mobs.
- If we are still worried about memory then another trick would be to have a uint16 that tracks which mobskill list to use (which we already do as a mobmod). If this is set then we use that mobskill list otherwise we set it to either 0 to indicate that the mob uses its own skill list. This would keep the custom lists down and also mitigate the code churn required for this change.
- I propose that this custom mobskill list would also be a weighted list - perhaps a vector<pair<uint8, uint16>>. There is a reasonable amount of evidence that mobskills are not always weighted evenly. This would greatly simplify achieving this.

**Comment by jmcmorris** [comment]
I forgot to add this:

I think it would be safe to always reset the mob state at spawn time which is what we do for localvars. If we really wanted to we could use some special mobskill list IDs to indicate this. Such as 0 could be reset during spawn which is likely what we typically want. Then we could have 1 (or UINT16_MAX) be never reset. Anything other than that is considered a mobskill list ID. This would allow us to easily setup the custom list one time during mob initialization or initialize it every time during the mob spawn.

**Comment by zach2good** [comment]
My main concern here is by changing the underlying storage method, we'd be giving _every mob in the game_ a customisable skill list (a vector, or a weighted lookup etc.) when the vast majority won't need them.

In the grand scheme of things the amount of memory used by this would be negligible, but there's no need to do it.

The pattern I was thinking of (and used for customisable loot pools before you did the rewrite with Lua bindings):
- By default, mobs have their skill list id
- If you call any customisation function on them (and they don't have their local list ready), it'll copy the contents of their global skill list to their local one, and then apply changes to it.
- ^ This way all mobs only have an empty vector, or an optional<vector<pair<id, weight>>> until a customisation is requested. 
- It can/will be rebuilt every time the mob spawns/resets

EDIT: I don't like the idea of a magic number skill list to tell the mob to use custom things, we should enforce using actual types/mechanisms like optional

**Comment by zach2good** [comment]
TIL: Skill lists are mobMods and not just an innate part of the mob object... Why...

**Review by zach2good — APPROVED** [review]
Back on topic; I reckon this PR is fine. Especially with https://github.com/LandSandBoat/server/pull/6039 on the horizon - which will allow us to make sure enum renames don't get missed in areas where they're being used.

**Pull request merged**
