### PR TITLE
[trust] Disband party correctly when no other members and no trusts

### LINKED ISSUE #1237: Trust party not being disbanded
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: Base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
When partying with only trusts, party isn't being disbanded when zoning or dismising last trust in party.

### PR DESCRIPTION
**Pull request by zach2good**
Fixes https://github.com/LandSandBoat/server/issues/1237

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by zach2good** [comment]
Ew, doesn't work when zoning

**Comment by zach2good** [comment]
Tested with 
- `/refa all`
- Releasing trusts
- Zoning
- Multi-instance zoning

All seems fine. I have also discovered the `CParty` is utterly bonkers and broken, and I don't understand how any server is running. At all.

**Review by claywar — APPROVED** [review]

**Comment by TeoTwawki** [comment]
caveat: if you are the last remaining person of a party that DID NOT contain any more trusts (a human left and you had lead) you become the leader of a party of one.

was that scenario tested/covered?

**Comment by zach2good** [comment]
Will test now

**Comment by zach2good** [comment]
👀

**Pull request merged**
