### PR TITLE
Reraise menu disappearance fix

### PR DESCRIPTION
**Pull request by mumencoder**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

if the 'accept raise' menu disappears due to zoning/position change it will come back.

## Steps to test these changes

cloudy orb
!additem 1551

scroll of instant reraise
!additem 4182

!send testplayer 146
Trade the orb, use the scroll, and then wipe in the battlefield. Wait 3 minutes for removal. Raise menu should reappear afterwards

### CODE REVIEW

**Comment by TeoTwawki** [comment]
> if the 'accept raise' menu disappears due to zoning/position change it will come back.

Disregarding a sec that your draft went all kindsa crazy because branch didn't start clean, what are you trying to fix? Loss of reraise when being zoned is retail accurate and battlefields don't strip it on exit normally because they don't zone you - it's the same zone in the lobby area as it is inside the fight. Last I checked this weas working properly on our base branch.

**Comment by mumencoder** [comment]
I tried to PR from a separate fork, thinking it would be OK since github would only let me have one anyways. Working on fixing that. Also I tested this on retail and the raise menu does come back.

**Comment by Xaver-DaRed** [comment]
Could you share what test did you perform in retail?
From memomry, the only time RR carried over was when expulsed out of a battlefield, as teo suggested, so itwould be useful to know.

**Comment by TeoTwawki** [comment]
> I tried to PR from a separate fork, thinking it would be OK since github would only let me have one anyways. Working on fixing that. Also I tested this on retail and the raise menu does come back.

Tested getting kicked from a battlefield while dead or tested getting ***zoned*** while dead? These are ***not*** the same thing.

**Comment by mumencoder** [comment]
This is not the effect of re-raise carrying over. This is the 'accept raise' menu disappearing and not coming back if the client goes into the ... loading ... screen, which happens on a position/zone change. In retail it will come back.

**Comment by TeoTwawki** [comment]
> This is not the effect of re-raise carrying over. This is the 'accept raise' menu disappearing and not coming back if the client goes into the ... loading ... screen, which happens on a position/zone change. In retail it will come back.

ok look:

you zone into horloise peak, enter bcnm, wipe, get kick out, you are still in horloise peak. You will retain rr menu, on retail. because you still have the effect and the effect will re-open the menu again.

If however, something causes you to get actually zoned - its lost. it will not come back up. This is a rare but annoying circumstance.


We on same page?



If battlefield exit has been stripping it (this shouldn't be zonage) or we've been actually zoning people for that, I am going to be annoyed at the lack of reports since the last time I checked it, coz this used to work accurately.

**Comment by mumencoder** [comment]
Mostly but I maintain that getting kicked out of the battlefield due to the 3 minute timer also removes the menu. I didn't actually test *zoning*, but I assume it would happen as well (getting kicked from a battlefield causes the screen to go black and the ... loading... screen to pop up which is probably what does it)

I should add that I did not test this on LSB base, I did inspect the code and didn't see anywhere it could have been fixed besides deathstate.cpp between the different forks, but I admit I am new to the codebase. I could set up LSB base testing as well for this and will for sure for future PRs.

**Comment by TeoTwawki** [comment]
> Mostly but I maintain that getting kicked out of the battlefield due to the 3 minute timer also removes the menu.

Ok, that is def something for us to fix if that happens, I'm maintaining that that is not a zone (or at least should not be).

I also just had a chat with the team where I said I wouldn't be opposed to going against retail behavior in regard to the zoning part - it's incredibly annoying even if difficult to make happen on purpose. But I know what retail does so when you say "zone" I have to confirm that's actually what you mean or not, since battlefield kick isn't supposed to be a zone at all but both would do a fade to black (so, we could have 2 bugs here, or a diff one than expected, or a simple misunderstanding of what is being adjusted)


Edit: we're doing a little checking in our end as well. So far, seems I am right that you meant just battlefield exit when you said "zoning" but we do have a real problem with bf exit

**Comment by mumencoder** [comment]
Commenting out the lines at https://github.com/LandSandBoat/server/blob/df175711d1f7cd935becd9c091e500a64665b7d1/src/map/lua/luautils.cpp#L2079-L2084 actually seems to fix the problem as well, at least for Charming Trio.

**Comment by KnowOne134** [comment]
just tossing this into here for information:

tested in retail and a zoning while being kicked out of a assault instance (battlefield) RR menu does not persist and you have to homepoint.

**Pull request closed without merging**
