### PR TITLE
[Digging] Audit data tables

### PR DESCRIPTION
**Pull request by Xaver-DaRed**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

It audits the data tables with the info from https://www.bg-wiki.com/ffxi/Category:Chocobo_Digging for available items and rates.
Still takes the info from xiclopedia for BORE and BURROW exclusive items, which arent implemented.

Translates all item IDs to enums 

This is supposed to be the preamble for a rewrite. I decided to do it in 2 parts so to not clutter the next one (the more important one)

NOTE: I took the data from there as it was. This resulted in an overall lower rate for most items. Some very few items got lucky.
NOTE 2: For BURROW and BORE information, when in doubt, it was done against players.
NOTE 3: This will temporarily disable the ability to dig eggs when wearing the egg helm. It will be reintroduced in the next PR.

## Steps to test these changes

Logic is mostly the same

### CODE REVIEW

**Review by claywar — APPROVED** [review]
Nice work, and fine with the changes.  The only thing that I'd like others to chime in with is the use of ints for the `NONE` type, to not be confused with `BORE` when perusing the list.

**Comment by zach2good** [comment]
I'm not sure I like `0` being the representative for no reqs. It's not as short, but `NONE` could be `NO_REQS` and then it's visually distinct from `BORE`

Also, comments like `-- Fire Crystal` can now be removed

Otherwise looks good 👍

**Comment by Xaver-DaRed** [comment]
I've done some more digging, no pun intended, and it turns out the BURROW and BORE abilities open up new independent "strata" layers. What this means is that, if you have bore, for instance, you can get 1 item from the regular pool AND an additional item from the BORE pool/strata.

So those requirements will dissapear in my next PR and instead, each zone will have 3 different pools defined (regular, burrow and bore pools) so this can happen:
imagen

**Comment by Xaver-DaRed** [comment]
Changed `NONE` to `NO_REQS` and replaced all 0s with it. Also deleted unnecesary comments

**Review by zach2good — APPROVED** [review]

**Pull request merged**
