### PR TITLE
[NPC] Purakoko pathing

### PR DESCRIPTION
**Pull request by kaincenteno**
adds 3 points that Purakoko uses for pathing

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Purakoko is currently static. 
This PR added the pathing AI and her 3 points that she uses to move around.
pathing currently doesnt support waiting at point and/or rotating so added notes of her behaviour when this is implemented

### CODE REVIEW

**Comment by zach2good** [comment]
Can you test your PRs and mark the box please?

**Review by Xaver-DaRed — CHANGES_REQUESTED** [review]
Styling: The 3 points need 4 spaces before them.

Other than that, looks good.

**Comment by kaincenteno** [comment]
Tested pathing works good until she falls off the bridge and goes back to the path. The co-ordinates were captured from retail. Unsure if this is an issue with the navmesh.

**Comment by kaincenteno** [comment]
@Xaver-DaRed  can you change this to a Draft given the bug with Purakoko falling

Nvm was able to change it to draft :)

**Comment by zach2good** [comment]
Whats going on with this PR?

**Comment by kaincenteno** [comment]
> Whats going on with this PR?

It was tested with coordinates captured from retail.
Unsure if there's an issue with navmesh or xi.path.patrol as purakoko falls from the bridge then goes back up. Any extra eyes are appreciated to look into this issue for improving xi.path

**Comment by kaincenteno** [comment]
checked purakoko's rotation again on a capture from retail and she doesnt deviate when walking, she walks in a straight line so she shouldn't be falling off the bridge for 1-2 seconds 😓

**Comment by kaincenteno** [comment]
I think the reason why purakoko falls of the steep bridge might be related to also why the mobs roaming on the stairs are falling off map, something wonky with navmeshes for paths that are too steep @zach2good 
https://github.com/LandSandBoat/server/issues/1948

**Comment by claywar** [comment]
Closing this in favor of #2988

**Pull request closed without merging**
