### PR TITLE
[Dynamis Jeuno] Group Spawning

### PR DESCRIPTION
**Pull request by Kayanesa**
Added a REFILL_MOB_GROUP to spawn monster in different grouping instead of all individual spawn. Created the table of possible spawn.
All following documentation
https://www.dropbox.com/s/p3zpuq93bs2vw90/Dynamis%20Jeuno%20IDs%20Groups%20Mechanics.zip?dl=0
It also line up with retail video of the zone.
Also added NM spawn condition for both group NM and Place holder NM type.
Will solve #1108
Remade PR but base on server base

Edit Added info
This Pr create a table of mob(REFILL_MOB_GROUP) that spawn only one mob from each group created. It need the change made on PR #1503 to work correctly. PR 1503 remove the mob timer and change the mob spawn type from "0" timer to "128".
Dynamis lua is used to read the mob table(REFILL_MOB_GROUP) and pop the appropriate mob.

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by kaincenteno** [comment]
great job :D

**Comment by Era-Lusiphur** [comment]
Pulled and tested this out. I am not seeing a functional change to how the mobs spawn. There's still too many up, if the intent was to group them and rotate through possible spawns. @MarianArlt had made some fairly good maps for Dynamis-Jeuno and I verified them (will have to locate them again for reference). This specific shot, as an example going from pretty certain memory, should have a middle group of 3 mobs/NMs and a couple off to the sides.

image

**Comment by Kayanesa** [comment]
That's to be expected you need the other pr #1503 that one remove the timer for the mob so right now you have mob on timer and the group mob poping.

**Comment by TeoTwawki** [comment]
in the future please describe things - I don't like following a drop box link to get the basics of your intent

**Comment by TeoTwawki** [comment]
> There's still too many up, if the intent was to group them and rotate through possible spawns.

worth noting you could hijack/misuse the existing lotto pop system to pull that off, but I'd rather that not become widespread as another solution is in the pipes, just very very backlogged. It involves some sql table re-arranging.

**Comment by Kayanesa** [comment]
I will try to be clearer. Just for clarity did you mean in the lua or in my pr description that you find lacking?

**Comment by TeoTwawki** [comment]
> I will try to be clearer. Just for clarity did you mean in the lua or in my pr description that you find lacking?

Pr description doesn't really explain what the pr is attempting to do beyond "fixes this linked issue". I can look at your code and see what you are actually doing, but if your code and your intentions don't match I wouldn't be able to explain without following more links to figure out what you meant to do.

**Comment by kaincenteno** [comment]
Hi @Kayanesa 

I appreciate the hardwork you did researching and testing Jeuno Dynamis =) 
Can you please update the PR description as requested so your work can be merged :D

Thank you :D

**Comment by TeoTwawki** [comment]
> Hi @Kayanesa
> 
> I appreciate the hardwork you did researching and testing Jeuno Dynamis =) Can you please update the PR description as requested so your work can be merged :D
> 
> Thank you :D

Thats not why it hasn't merged. it depends on his other pr that hasn't merged yet. I don't have time to review currently. Be patient Kain.

**Comment by kaincenteno** [comment]
> > Hi @Kayanesa
> > I appreciate the hardwork you did researching and testing Jeuno Dynamis =) Can you please update the PR description as requested so your work can be merged :D
> > Thank you :D
> 
> Thats not why it hasn't merged. it depends on his other pr that hasn't merged yet. I don't have time to review currently. Be patient Kain.

Ahhh got it lol xD thought that more info was needed. Thanks Teo :D

**Comment by Kayanesa** [comment]
It wont take much time but if I saw a change this week correctly I will need to update this before the push.
this
dynamis.refillMobGroupOnDeath(mob, player, isKiller, 1200) -- 20 min
is becoming this
xi.dynamis.refillMobGroupOnDeath(mob, player, isKiller, 1200) -- 20 min
But I'm not sure if it's needed or not

**Comment by Kayanesa** [comment]
So ya just double checked and they removed dynamis from the file for xi.dynamis
in push #1557

**Comment by TeoTwawki** [comment]
Partially superseded by #3709 but closing this mainly due to its age and conflict state. Further work can happen in a new PR.

**Pull request closed without merging**
