### PR TITLE
Add template note to not resolve your own comment threads

### PR DESCRIPTION
**Pull request by TeoTwawki**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
Github is ignoring [the problem](https://github.com/orgs/community/discussions/18458), and people keep doing this and its irritating especially if they just disagreed with a requested change and then "close" the conversation. Hopefully this note reduces people closing them before we're ready.

## Steps to test these changes
None.

### CODE REVIEW

**Comment by zach2good** [comment]
I don't think this belongs in the main template, we need to keep it as small as humanly possible. Just yeet this into the contributor guides?

**Comment by TeoTwawki** [comment]
> I don't think this belongs in the main template, we need to keep it as small as humanly possible. Just yeet this into the contributor guides?

Won't get noticed. Did this big and in their face intentionally. In a perfect world I wouldn't even have to say it let along put in the main template. I'm trying to be polite about it while removing any excuse of "oh I didn't know."

**Comment by TeoTwawki** [comment]
Per private discussion, converted to checkbox. also rebased to 1 commit.

We could not automate this.

**Review by Xaver-DaRed — APPROVED** [review]

**Comment by zach2good** [comment]
This will need this chunk updated:
https://github.com/LandSandBoat/server/blob/base/.github/workflows/github.yml#L44-L62

Or slightly modified to instead normalize and then count un-filled boxes

**Review by zach2good — APPROVED** [review]

**Pull request merged**
