### PR TITLE
Add piece of shiromochi

### PR DESCRIPTION
**Pull request by cmastro24**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Adds the food piece of shiromochi.  Updates the items_usable.sql and the associated luas.

## Steps to test these changes
Eat food, verify stats are correct on equip screen and /checkparam <me>.  Use antacid, verify stats were removed.

### CODE REVIEW

**Comment by cmastro24** [comment]
I messed up my branch trying to squash the commits and had to start over.

**Comment by cmastro24** [comment]
Any update on this?

**Comment by cmastro24** [comment]
I hope I did this right, I never did a squash before.

**Comment by TeoTwawki** [comment]
> I hope I did this right, I never did a squash before.

unfortunately no, squash would leave you with only 1 commit on the pr, not 10. after you do it you want to force push. a lot of ppl get tripped up when they try a regular push and get a message saying the remote has other work in it and "helpfully" suggests pulling. because that just brings back those now zombie commits + a merge.

**Comment by cmastro24** [comment]
Thank you, how can I fix this.  I'm using git from the command line.  Would it be better to create a new branch with just my changes and push that?

**Comment by WinterSolstice8** [comment]
You can use `git rebase -i head~11` and set the commits from "pick" to "squash"

but you might need to rebase first to get rid of the extra commits

**Review by Xaver-DaRed — APPROVED** [review]

**Review by TeoTwawki — APPROVED** [review]

**Pull request merged**
