### PR TITLE
[Cleanup]Standardize AF Quest Names

### PR DESCRIPTION
**Pull request by hooksta4**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
Standardizes all current Artifact Quests into [JOB]AF[1-3]Quest_Name
Adjusted quests that were not using player:getMainLvl() >= xi.settings.main.AF[X]_QUEST_LEVEL

Standardizes naming Convention
## Steps to test these changes
None should be noted. Renamed files.

### CODE REVIEW

**Review by Xaver-DaRed — APPROVED** [review]
I'm gonna approve couse I was the one who started this trend.

However, from this point on, I believe we should stick to just "Those questlines everyone does". Aka, Limit breaks and AFs

**Comment by claywar** [comment]
Apologies, but a rebase will be required here due to corrections in that quest script

**Comment by hooksta4** [comment]
> Apologies, but a rebase will be required here due to corrections in that quest script

Did I finally do it correctly?

**Comment by hooksta4** [comment]
> I'm gonna approve couse I was the one who started this trend.
> 
> However, from this point on, I believe we should stick to just "Those questlines everyone does". Aka, Limit breaks and AFs

Yea I don't think there are any more quest series that are more than a few long that would really warrant these. The ones that come to mind are already done, The Onions series, Rycharde chef... I mean maybe the ToAU mythic questline?

**Pull request merged**
