### PR TITLE
Updates to synth_recipes.sql

### PR DESCRIPTION
**Pull request by FuzzyWereBeast**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by TeoTwawki** [comment]
tick the checkboxes and yer good. ci is going to run the sql but I already know its gonna say it passes

**Comment by FuzzyWereBeast** [comment]
Done

**Review by TeoTwawki — DISMISSED** [review]

**Comment by TeoTwawki** [comment]
if you add more to the same PR before I can merge it, it invalidates the review and approval and I have to reread it. it takes longer each time you do that, so you want to wait a bit (in cases where its not the same file, you can use a 2nd branch and have 2 open at once)

I would have merged this just now but I came back and saw it has new stuff. Maybe Zach or Clay will have time to check it over the weekend, I'm not sure what my weekend is going to be like yet.

**Comment by TeoTwawki** [comment]
p.s. I do appreciate the enthusiasm tho :)

**Comment by FuzzyWereBeast** [comment]
Still new to how github works. I thought I was submitting a new request. I'll need to look into how to do what you suggest.

**Review by claywar — APPROVED** [review]

**Comment by claywar** [comment]
Looks like CI wasn't happy with one of those lines, once that's resolved we'll run the check again and hopefully its good to go:
`ERROR 1644 (45000) at line 4561: [table:synth_recipes] - `Ingredient2` is larger than Ingredient3`

**Comment by claywar** [comment]
Almost, now its complaining about the same line for 1 vs 2
`ERROR 1644 (45000) at line 4561: [table:synth_recipes] - `Ingredient1` is larger than Ingredient2`

**Comment by TeoTwawki** [comment]
due to some as yet unfixed past idiocy synth mats have to be orders from lowest ID to highest ID. a previous "fix" for the terrible core logic around this simply enforced this at the sql level

**Comment by RAIST5150** [comment]
Yeah... something that amused me as I was verifying item numbers.  They are always running left to right from lowest ID to highest.

It actually helps when verifying though, since items_basic.sql is listed the same way.  My searches automatically move to each item as I type them, so I really only have to refocus position in the file for the first item ID.

**Pull request merged**
