### PR TITLE
Add Move Speed latent as Item Mod

### LINKED ISSUE #4766: 🐛 getMaxGearMod() does not account for latent effects
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

All/Any

## Branch affected by issue

`base`

## Steps to reproduce
Equip a nation Aketon. With the speed rework, gear uses said function to get the highest value of a specific modifier, comparing each piece of gear one by one, calling `getModifier()` (defined in item_equipment.cpp)

We do not have a similar function for "get latent if latent should apply"

## Expected behavior

If a latent SHOULD apply, `getMaxGearMod()` should return the value of the requested modifier.

### LINKED ISSUE #5810: 🐛 Movement Speed Latent Effect Broken
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

Add Destrier Beret:

```
!additem 11811
```

Equip on job under level 31, note unchanged speed.

## Expected behavior

Latent effects should be checked for speed enhancements.

### PR DESCRIPTION
**Pull request by cocosolos**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Adds `Mod::MOVE_SPEED_GEAR_BONUS` to list of mods that should apply to the item instead of the player. 

Fixes #4766
Fixes #5810

Under 31:
image
Over 30:
image

## Steps to test these changes

```
!additem 11811
!changejob war 30
/equip head "Destrier beret"
!changejob war 31
```

### CODE REVIEW

**Comment by cocosolos** [comment]
Aketon works as well, and doesn't stack with the beret.

**Review by WinterSolstice8 — APPROVED** [review]

**Comment by cocosolos** [comment]
Found an issue with this when wearing and removing multiple pieces of latent speed gear. Looking into it.

**Comment by cocosolos** [comment]
I'm not sure what's causing this issue and won't be able to look into it until tomorrow, but here's how to reproduce:

1. Be in a starting city, level 30 or lower.
2. Equip nation aketon THEN destrier beret.
3. Set level to 31.
4. Remove aketon THEN beret.
5. Re-equip beret, item still has speed mod.

Latents need to be refreshed more often for time and level based latents, so that might end up fixing this issue. Currently you need to remove the item for it to lose its mod (Destrier beret level, ninja kyahan time). But this might also be unrelated to that, since this particular issue only seems to happen when adding and removing items in a certain order.

If anyone has any idea what's going on let me know, otherwise I'll try to investigate more tomorrow.

**Comment by MowFord** [comment]
This is likely the result of using `!changejob` vs using a nomad moogle or gaining xp naturally. You could probably emulate it via `!addexp` to confirm but i'm almost positive this isn't an issue under normal circumstances.

You confirmed in your OP that using `!changejob` doesn't refresh latents so it makes sense there'd be this edge case.

**Comment by cocosolos** [comment]
> This is likely the result of using `!changejob` vs using a nomad moogle or gaining xp naturally. You could probably emulate it via `!addexp` to confirm but i'm almost positive this isn't an issue under normal circumstances.
> 
> You confirmed in your OP that using `!changejob` doesn't refresh latents so it makes sense there'd be this edge case.

I actually did test by manually adding exp and I still had to re-equip to get the latent to remove. I don't think any of the existing latent update functions cover this latent so should be easy to fix. I'm more concerned about the item itself not losing the mod under certain circumstances.

**Comment by cocosolos** [comment]
Okay I added "level above and below" to `CheckLatentsJobLevel` so it gets checked on exp gain and used `charutils::RemoveAllEquipMods` and `charutils::ApplyAllEquipMods` around some Lua bindings instead of directly calling `CheckLatentsJobLevel`. I think either approach works but this is the pattern used in `levelRestriction` so just went with that. Looks like everything works as expected now.

**Comment by Xaver-DaRed** [comment]
Question: What happens when you equp, say, an Destrier beret under lvl 30 with a kupo suit with this change?

**Comment by cocosolos** [comment]
It correctly only uses one of them, and you can mess around with changing your level and adding/removing different combos and it should all work correctly. Same with ninja kyahan at night gives the bigger boost and takes precedence over any of the 12% pieces. Kupo suit should override beret since all the max mod stuff already works correctly, it's just these latents were applying to the player instead of the gear like other movement speed items.

**Review by Xaver-DaRed — APPROVED** [review]

**Pull request merged**
