### PR TITLE
[sql] Added Army's Paeon V to / Audit drop list of Coastal Sahagin in SSG

### PR DESCRIPTION
**Pull request by EpicTaru**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Adds Army's Paeon V to drop list.

Performed an audit of all other drops for this mob based upon TH0 data from FFXIDB, adjusting the drops to also utilize the established ``@variables``.

Following drops removed from drop list based upon not being listed for the mob on FFXIDB:
* Shall Shell
* Pamtam Kelp
* Bastore Sardine
* Quus

Info on the stolen item (Gold Beastcoin) is per FFXIclopedia/BG-wiki.

## Steps to test these changes

Killing this mob before this PR is merge means that you will never get Scroll of Army's Paeon V from the mob.

Killing this mob after this PR is merged means that you will have the same chance of that scroll dropping as well as multiple other scrolls.

Because of this audit, Treasure Hunter may be more recommended vs. prior to this audit.

### CODE REVIEW

**Review by claywar — APPROVED** [review]
Overall lower, so seems reasonable given the ref data.

**Comment by EpicTaru** [comment]
Indeed. Appeared that the old source for the drop rates was FFXIclopedia.

**Comment by EpicTaru** [comment]
And now that I fully understand how to correlate the data on FFXIDB and the ``@variables``, I can slowly start auditing other mob drops

**Comment by zach2good** [comment]
Careful who you tag, (at)variables is someone's username 👀

**Comment by EpicTaru** [comment]
DerpTaru strikes again! Sorry to whoever you are! 

DerpTaru has been flogged and caffeinated.

**Comment by TeoTwawki** [comment]
you can wrap in backticks to avoid tagging people in commit messages like that. Example:
> Also performed an audit of all other drops for this mob based upon TH0 data from FFXIDB, adjusting the drops to also utilize the established `@variables`

**Pull request merged**
