### PR TITLE
[dbtool] Automatically pick up migrations

### PR DESCRIPTION
**Pull request by zach2good**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Review by claywar — APPROVED** [review]

**Comment by cocosolos** [comment]
At this point it probably doesn't matter much, but  `extend_mission_log` needs to be run before `mission_blob_extra` and `cop_mission_ids` or you could end up with some malformed mission logs. `os.scandir` reads in arbitrary order so you could rename `extend_mission_log.py` to something like `0extend_mission_log.py` then sort before processing with `sorted(os.scandir("migrations"), key=lambda e: e.name)`.

**Comment by zach2good** [comment]
I did have some concerns about this, and considered prepending new
migrations with 1_, 2_ etc.

Ill probably end up doing it, just to be on the safe side

**Comment by cocosolos** [comment]
AFAIK it's only that one migration that needs to run first since the other 2 rely on the size of the mission blob (this is admittedly not very safe or future proof, my bad), but I haven't really looked into the newer ones.

**Comment by cocosolos** [comment]
Actually after looking at it again `extend_mission_log` needs to run first, then `mission_blob_extra`, then order doesn't really matter after those 2.

**Pull request merged**
