### PR TITLE
Updated Marid drop list Bhaflau Thickets

### PR DESCRIPTION
**Pull request by GravesXI**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

 drop rate info i got from http://ffxidb.com/zones/52/marid

### CODE REVIEW

**Comment by Xaver-DaRed** [comment]
the marid hair looks fine.
the tusk however, may require some math. whenever an item in ffxidb has a higher % than 100, it means it can drop multiples of said item

**Comment by Skerxan** [comment]
I'm pretty sure Marid Tusks only drop when you break their tusks thru crits.

**Comment by GravesXI** [comment]
sorry new to this i meant to made a new pull list for other but it added it here and not sure how to take it off

**Comment by TeoTwawki** [comment]
> sorry new to this i meant to made a new pull list for other but it added it here and not sure how to take it off

https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by GravesXI** [comment]
got rid of tusk till can rework the drop with breaking tusk

**Comment by TeoTwawki** [comment]
> got rid of tusk till can rework the drop with breaking tusk

Couple of ways we could go about that - Like use multiple droplists and on tusk break set the list to the other ID. Existing bindings don't work to well for modifying an existing droplist on a fly, but we could change that without to much trouble I think. Tusk breaking is a sub animation set, so we'd just do it at that time. I suggest leaving that for a separate PR after we work out the details. Maybe starts a [discussion](https://github.com/LandSandBoat/server/discussions) thread for it.


###### _(if you change "the list" if affects other instances of the mob than the one you are fighting, and we have problems un-inserting the new entry, as well as the method you might expect to be amending rates causes a duplicate to be created instead)._

**Review by Xaver-DaRed — APPROVED** [review]
For now, this is good. A different PR can be opened for tusks once a system is thought of/implemented

**Pull request merged**
