### PR TITLE
[core] Add UUID util

### PR DESCRIPTION
**Pull request by zach2good**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

To be used later for item disambiguation

```cpp

#include "common/uuid.h"

...

    ShowInfo(uuid::GenerateUUID());
```

```
[08/29/23 15:40:23:299][connect][info] 40dba40e-8784-4650-8eef-6f51957c58d4 (ConnectServer::ConnectServer:74)
[08/29/23 15:40:23:299][connect][info] 91e64cc5-477d-410d-97b1-d48810ecc93d (ConnectServer::ConnectServer:75)
```

### CODE REVIEW

**Review by TeoTwawki — DISMISSED** [review]
I'm assuming it'll still be ok after you're done force pushing formatting over it

**Review by claywar — APPROVED** [review]

**Comment by zach2good** [comment]
I brought in the content of `crashoz/uuid_v4` into a single header, since that repo builds the examples by default on import and it was starting to be a pain in the ass. I might submit some changes back to them to fix it, but for now, Win64+Linux gets the SIMD code, and Win32+OSX gets the manual code

**Comment by zach2good** [comment]
I'll probably need to add in more compiler flags to force this behaviour, since people out there use strange architectures that don't have AVX2 and friends

**Comment by zach2good** [comment]
I've opted to rip out the fancy SIMD code for now, with a TODO to maybe add it back in later. The majority of our UUID generation will be happening in MariaDB with `UUID()` anyway

**Pull request merged**
