### PR TITLE
BaseSell from retail

### PR DESCRIPTION
**Pull request by illzbee**
captured BaseSell from retail

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Updates BaseSell from retail values.

### CODE REVIEW

**Comment by zach2good** [comment]
Which NPC did you get these values from?

**Comment by illzbee** [comment]
> Which NPC did you get these values from?

Leyla Port Jueno

**Comment by UynGH** [comment]
Hello.

As I recall, Leyla is not a non-fame based NPC regarding sell prices. Can you check with Challoux, still in Port Jeuno at (I-8), instead, please?

Thank you!

**Comment by illzbee** [comment]
I get the same price from Challoux

**Comment by UynGH** [comment]
Then it's good to go. Thank you!

**Review by zach2good — APPROVED** [review]

**Review by claywar — APPROVED** [review]

**Pull request merged**
