### PR TITLE
Shadows of the Mind ISNM

### PR DESCRIPTION
**Pull request by jmcmorris**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Implements the Shadows of the Mind ISNM battlefield. This also does three small additional changes.

1. Adds Gil to Making a Mockery ISNM rewards
2. Adds missing message ID for Imperial Order breaking
3. Adds setMaxHP binding for lua entities

## Retail Proof

[https://ffxiclopedia.fandom.com/wiki/Shadows_of_the_Mind](https://ffxiclopedia.fandom.com/wiki/Shadows_of_the_Mind)
[https://ffxiclopedia.fandom.com/wiki/Phantom_Puk](https://ffxiclopedia.fandom.com/wiki/Phantom_Puk)
[https://wiki.ffo.jp/html/6679.html](https://wiki.ffo.jp/html/6679.html)
[Wiggo's Capture](https://discord.com/channels/443544205206355968/609478860593037395/609481576606072854)
[Melo's Capture](https://discord.com/channels/443544205206355968/609478860593037395/1275830223463649412)

## Steps to test these changes

`!zone <Jade Sepulcher>`
`!addkeyitem 808`
Go to the door and enter the Shadows of the Mind battlefield
Test the battlefield according to the above retail data

### CODE REVIEW

**Comment by CatsEyeXI** [comment]
I was curious to see a diff as I was the person that originally worked on this, but it looks like the mobskills are new Luas in this PR, where they were originally created in #5502

**Comment by jmcmorris** [comment]
> I was curious to see a diff as I was the person that originally worked on this, but it looks like the mobskills are new Luas in this PR, where they were originally created in #5502

Why don't any of these changes show up in LSB?

**Comment by jmcmorris** [comment]
Oh, I see they are not in base but instead in a branch. That PR was for implementing it into the old battlefield system. This PR is for the new battlefield.

**Comment by CatsEyeXI** [comment]
ah, yup, hadn't realized that... thanks

**Comment by jmcmorris** [comment]
> ah, yup, hadn't realized that... thanks

Sorry for the duplicate efforts!

**Comment by CatsEyeXI** [comment]
> > ah, yup, hadn't realized that... thanks
> 
> Sorry for the duplicate efforts!

all good -- all working towards the same goal

**Review by claywar — APPROVED** [review]

**Review by Xaver-DaRed — APPROVED** [review]

**Pull request merged**
