### PR TITLE
[core] Dynamic Module Load Order & Basic Dynamic NPCs

### PR DESCRIPTION
**Pull request by zach2good**
[I'm only... 7 years late...](https://forums.dspt.info/viewtopic.php?f=5&t=2385)

image
image
image
image

**Notes**
- We can toggle green/grey names by changing `allegiance` from MOB to PLAYER.
- We can enable _some sort of targeting menu_ by setting `name_prefix to 8.
- Ghosts! `name_vis` to 128.
- New player flag: `m_flags` to 65536.

**TODO** 
- Lots of experimenting with packet `0x00E (Entity Update)`, get some help from [Windower docs](https://github.com/Windower/Lua/blob/dev/addons/libs/packets/fields.lua#L1423-L1449)
- Rewrite `0x00E`, it's so fractured and broken. We can clean this up.
- It _must_ be possible to trigger these as if they were NPCs. We kind of _need_ to find this for seasonal event emulation.
- Test out as battle mobs. This will let me get some sort of non-shifting Ambuscade running.
- Rewrite how we handle `targid` in `zone_entities`. Again, pretty fractured. We can clean this up.
- Use the new API to write seasonal event modules.

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by jeffnavy14** [comment]
I understand this is a work in progress but how would you go about attaching a lua for the specific custom NPC?

**Comment by zach2good** [comment]
No idea, this is what I meant by:

> It must be possible to trigger these as if they were NPCs. We kind of need to find this for seasonal event emulation.

Still needs more research

**Comment by zach2good** [comment]
(this isn't in yet)

Velyn found the flag for me for "triggerable-ness", so it'll be possible to make dynamic and interactable NPCs. I'll probably wrap it behind something like this:
```lua
npc:setTriggerable(true)
```

**Comment by zach2good** [comment]
I've added a module example for how to insert an NPC into a zone, and then attach regular event handlers to it.

**THIS IS HIGHLY EXPERIMENTAL. IF YOU START USING THIS NOW IT WILL BREAK. I GUARANTEE IT.**

image

https://github.com/LandSandBoat/server/pull/1110/files#diff-41b756c71a3877be221938da97d70a0ef3b79b6c33c5a5215531ae5a357b8611

**Comment by kaincenteno** [comment]
oooooo :smile:  will this be something that can be used to fix all the mobs in monastic cavern and dynamis jeuno that have lots of mobs that are supposed to spawn in a rotation that are currently spawned at the same time? :smile:

**Comment by Xaver-DaRed** [comment]
No. This isn't related to that, at all.

**Comment by zach2good** [comment]
I don't remember if I left clues at the end of the stream when I was working on this:

When dynamic mobs are spawned, they die instantly. It _looks_ like they're trying to die/despawn and wander off to a spawnpoint that is being set to 0,0,0 or 1,1,1 etc. This can be circumvented with `mob:setUnkillable()` and then all battle and targeting functions start to work as intended, as the mob tries to wander "home".

Probably just a matter of adjusting the AI behaviour flags on spawn.

**Comment by TeoTwawki** [comment]
> I don't remember if I left clues at the end of the stream when I was working on this:
> 
> When dynamic mobs are spawned, they die instantly. It _looks_ like they're trying to die/despawn and wander off to a spawnpoint that is being set to 0,0,0 or 1,1,1 etc. This can be circumvented with `mob:setUnkillable()` and then all battle and targeting functions start to work as intended, as the mob tries to wander "home".
> 
> Probably just a matter of adjusting the AI behaviour flags on spawn.

try printing its home pos - where does it think home is (including zone) ? 

I remember on stream to tried to set one, and it didn't seem to use it. All mobs that are prevented from despawn will walk home. Non NMs normally despawn instead of walking home, but all mobs "go home" one way or another when they don't have a target to pursue. That's really the only behavior that I recall the core having that relates to this.

**Comment by zach2good** [comment]
OK, I'm happy for this to go in now. I've reduced the scope to just be the most basic NPCs possible, plus some module rewrites that I figured out while I was working on this.

I've left a lot of notes all over the place for future readers, that's intentional!

**Comment by zach2good** [comment]
(Plz squash on merge, my commits are bullshit for this)

**Review by claywar — APPROVED** [review]

**Pull request merged**
