### PR TITLE
Add new module for era item cooldowns

### PR DESCRIPTION
**Pull request by zach2good**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Follow up from https://github.com/LandSandBoat/server/pull/3098

- Makes nomad_cap AoE
- Add new module for era item cooldowns

## Steps to test these changes

Tested the queries locally

### CODE REVIEW

**Comment by zach2good** [comment]
Ruh roh, somethings up with the new bot

**Comment by zach2good** [comment]
Ah, this doesn't take into account my new changes, it's still looking for 4x boxes (one in the comment), and I removed the comment. Disregard the bot until that PR merges.

**Comment by zach2good** [comment]
https://github.com/LandSandBoat/server/pull/3105

**Comment by KnowOne134** [comment]
Some more if interested is all xp ring cool down, treat staff 2 signal and tactics pearls

**Comment by TeoTwawki** [comment]
should do the older cooldowns for exp rings in same module?

**Review by Xaver-DaRed — APPROVED** [review]

**Pull request merged**
