### PR TITLE
items: Ensure Nomad cap can be used as AoE per Era

### PR DESCRIPTION
**Pull request by hilts-vaughan**
https://ffxiclopedia.fandom.com/wiki/Nomad_Cap?oldid=892683

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [ ] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [ ] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by hilts-vaughan** [comment]
Didn't test, sorry. Trivial flag change.

**Review by zach2good — APPROVED** [review]

**Comment by zach2good** [comment]
> As per era

Am I missing something here, the era page looks almost exactly the same as the modern page?

**Comment by TeoTwawki** [comment]
The only "era" related change is the cooldown. it was always aoe on retail. but per the wiki diff it went from 72hrs to 20hrs cooldown.

It was likely not flagged aoe in our sql data due to past problems with aoe items functioning correctly.

**Comment by hilts-vaughan** [comment]
Commit name is just bad.  I was originally going to try and contribute an era mod for it as well for cooldowns (it used to be several days!) but didn't really have the time to dig into how to do it.

I can reword the commit it everything else looks fine (or you can and force push it)

**Comment by zach2good** [comment]
Thats a decent idea for a module actually, I can hook that up 👍 (I'll close this PR and co-author you into the new module)

**Pull request closed without merging**
