### PR TITLE
Add synth recipe for Omelette Sandwich

### PR DESCRIPTION
**Pull request by GravesXI**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits
This wasn't in the game i got my info from bg since it was the only one with a skill level https://www.bg-wiki.com/ffxi/Om._Sandwich

### CODE REVIEW

**Review by Xaver-DaRed — APPROVED** [review]
Items and quantities are correct.
Both BG wiki and JP wiki seem to agree aswell.
https://www.bg-wiki.com/ffxi/Om._Sandwich
https://wiki-ffo-jp.translate.goog/html/38042.html?_x_tr_sch=http&_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=sc

**Review by TeoTwawki — CHANGES_REQUESTED** [review]
image

Need commit messages to be more descriptive than "update file". [Please use `git commit --amend` to change the message.](https://www.w3schools.com/git/git_amend.asp) PR titles also need to be descriptive but I see Zach changed it for you. You can use that same message of `Add synth recipe for Omelette Sandwich` for the commit message.

**Comment by GravesXI** [comment]
I can't amend it so just going to close

**Comment by TeoTwawki** [comment]
There is no reason this had to be closed to fix it, if you don't know how to use git ask for help next time

**Pull request closed without merging**
