### PR TITLE
Correct Rainbow Cape desynthesis result

### PR DESCRIPTION
**Pull request by rdmkyran**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Corrects desynth. recipe for Rainbow Cape

Source: https://ffxiclopedia.fandom.com/wiki/Rainbow_Cape#Desynthesis_Recipes

Clothcraft (94/105)
Yield: Rainbow Thread x 3
HQ 1: Rainbow Thread x 4
HQ 2: Rainbow Thread x 5
HQ 3: Rainbow Thread x 6
Lightning Crystal
1 x Rainbow Cape

## Steps to test these changes
!setskill clothcraft 95
!additem rainbow_cape
!additem lightning_crystal

Desynth the rainbow cape

### CODE REVIEW

**Comment by TeoTwawki** [comment]
https://www.bg-wiki.com/ffxi/Rainbow_Cape
image

Looks like someone needs to test it for science, and then we can update whichever wiki was wrong. A problem with corroborating sources these days is so many users copy data from one site over to another, so best way to "know" is to just try things on retail. We'll need a high lv crafter for this. My gut says its likely BG that got it wrong, I've been fixing a lot of wrong craft data over there.

**Comment by Era-Lusiphur** [comment]
> 

Just checked this as well at the same time. JP wiki's listing agrees with Clopedia. FFXIAH only lists the possible x6 result, which I suppose agrees with the possible HQ3 at the worst. I just adjusted BG's listed results to agree with the other resources.

https://wiki.ffo.jp/html/4889.html

**Comment by TeoTwawki** [comment]
Being as this looks like an off-by-one situation and its not game breaking, I'm tentatively pre-approving and willing to see this merge with the promise that eventually somebody does a spot check in retail and gets a picture of -either- a result of 6 or 2.

**Review by TeoTwawki — APPROVED** [review]

**Comment by TeoTwawki** [comment]
> > 
> 
> Just checked this as well at the same time. JP wiki's listing agrees with Clopedia. FFXIAH only lists the possible x6 result, which I suppose agrees with the possible HQ3 at the worst. I just adjusted BG's listed results to agree with the other resources.
> 
> https://wiki.ffo.jp/html/4889.html

so I guess you missed what I said about corroborating sources being somewhat sketchy, and just contributed to the whole trend of not checking actual retail (now that all sources say same thing, who will ever know to look?) I'm not even blocking merge - I just would like somebody to eventually check this sorta thing

**Comment by RAIST5150** [comment]
Though it isn't a capture from retail, it was "documented" a while back in the talk page over at xiclopedia:

Screenshot_20230413-211941_Samsung Internet

https://ffxiclopedia.fandom.com/wiki/Talk:Rainbow_Cape

**Review by WinterSolstice8 — APPROVED** [review]

**Pull request merged**
