### PR TITLE
[core] [cmake] [sol] Enable Sol exceptions, remove custom LuaJIT build

### PR DESCRIPTION
**Pull request by WinterSolstice8**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Enable Sol exceptions (removal of `-DSOL_NO_EXCEPTIONS=1`)
Remove custom LuaJIT build that needed `-DLUAJIT_NO_UNWIND=1` for x86_64
## Steps to test these changes

setup:
build as normal, run game as normal, login as normal

testing:
Edit an existing lua script by adding whitespace somewhere that won't error, see it reload and no crash.
Edit an existing lua script and force it to error, see it attempt to reload and no crash.
Run "delmodnil" custom command to force an error, see it error in log with no crash.
Edit an existing _global_ lua script such as ChocoboRaising.lua, add whitespate somewhere, see it reload, no crash.
Edit an existing _global_ lua script such as ChocoboRaising.lua, and force it to error see it reload, no crash.

delmodnil.lua as follows:
```
-----------------------------------
-- func: delmodnil
-- desc: Tests passing nil to delMod to see if it crashes linux system
-----------------------------------

require("scripts/globals/status")

cmdprops =
{
    permission = 1,
    parameters = ""
}


function onTrigger(player)
    player:delMod(xi.mod.REGEN, nil)
end
```

### CODE REVIEW

**Comment by WinterSolstice8** [comment]
Drafting because apparently there are new exceptions thrown by Sol we need to handle now, makes sense since we turned on exceptions from Sol

**Comment by RAIST5150** [comment]
Kain spotted this tonight after rebuilding on xiweb (base).  Thought I'd run it by you here first before going to a new issue, just in case?

```
xigame_1  | [07/20/22 02:36:07:890][map][error] luautils::onSpellCast: stack index 2, expected number, received nil: not a numeric type (bad argument into 'bool(unsigned short, const sol::basic_object<sol::basic_reference<false>> &)')
xigame_1  | stack traceback:
xigame_1  |     [C]: in function 'hasStatusEffect'
xigame_1  |     ./scripts/globals/spells/summoning/fenrir.lua:28: in function <./scripts/globals/spells/summoning/fenrir.lua:25> (OnSpellCast:2475)
```

**Comment by WinterSolstice8** [comment]
Different problem, go ahead and make an issue

**Comment by WinterSolstice8** [comment]
Undrafting as a resolution has been found

**Comment by zach2good** [comment]
While you're here, can you alter all the `lua.script` and `lua.safe_script` to not take the `sol::default_pass_on_error` argument, or whatever it is. This global flag should negate the need for it.

**Review by zach2good — APPROVED** [review]

**Comment by WinterSolstice8** [comment]
Tested:
hot reload bad script
```
07/19/22 23:52:57:887][map][error] luautils::CacheLuaObjectFromFile: Load global error: scripts/globals/chocobo_raising.lua: ./scripts/globals/chocobo_raising.lua:91: table index is nil
stack traceback:
        ./scripts/globals/chocobo_raising.lua:91: in main chunk
        [C]: in function 'require'
        [string "package.loaded["scripts/globals/chocobo_raisi..."]:1: in main chunk (CacheLuaObjectFromFile:540)
```
hot reload good script:
```
[07/19/22 23:53:07:487][map][info] [FileWatcher] GLOBAL scripts/globals/chocobo_raising.lua -> "scripts/globals/chocobo_raising" (CacheLuaObjectFromFile:544)
```

`delmodnil`:
```
[07/20/22 00:06:53:879][map][error] cmdhandler::call: (delmodnil) error: stack index 3, expected number, received nil: not a numeric type (bad argument into 'void(short unsigned int, short int)')
stack traceback:
        [C]: in function 'delMod'
        ./scripts/commands/delmodnil.lua:16: in function <./scripts/commands/delmodnil.lua:15> (call:321)
```

**Review by zach2good — APPROVED** [review]
Nice work 👍

**Pull request merged**
