### PR TITLE
[SQL] Fix Deae Gratia missing drain effect

### PR DESCRIPTION
**Pull request by ampitere**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Daea Gratia should have an additional HP drain effect but it's currently missing from the items mods. There isn't a whole lot of information on exact proc chance or how much damage it does in retail but there are other similar weapons with the same additional effect implemented (Bloody Rapier, Bloody Sword, Carnage Rapier, Carnage Blade, etc.).

## Steps to test these changes

1. !additem 18856
2. !changejob 1 75
3. Equip club
4. Attack a mob

### CODE REVIEW

**Comment by TeoTwawki** [comment]
I actually have one of these on retail and this is close, but the highest proc I got out of it was 14 most swings getting 10 or 12 (resists).

**Comment by ampitere** [comment]
> I actually have one of these on retail and this is close, but the highest proc I got out of it was 14 most swings getting 10 or 12 (resists).

Tweaked down to 12 for now.

**Comment by TeoTwawki** [comment]
> Tweaked down to 12 for now.

Sorry you didn't know but we want to use peak value and then resist functions should take it wrong there. _Hopefully_ that is why that one sword already in the mod list has 20 (most drain items got 5 or 10, from a quick looksie). We've got some issues to work out with how these get mathed but if we use the upper limit of what it can do we should be able to fix the proper at some point.

**Comment by ampitere** [comment]
> > Tweaked down to 12 for now.
> 
> Sorry you didn't know but we want to use peak value and then resist functions should take it wrong there. _Hopefully_ that is why that one sword already in the mod list has 20 (most drain items got 5 or 10, from a quick looksie). We've got some issues to work out with how these get mathed but if we use the upper limit of what it can do we should be able to fix the proper at some point.

Tweaked to 14!

**Review by TeoTwawki — APPROVED** [review]

**Review by EpicTaru — APPROVED** [review]

**Review by Xaver-DaRed — APPROVED** [review]

**Pull request merged**
