### PR TITLE
[meta] Add utility to generate changelogs

### PR DESCRIPTION
**Pull request by zach2good**
Slapped this together on my lunchbreak, once this is in we can set up a github action/job for it to run and publish every 2 weeks

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by zach2good** [comment]
Example:
image

**Review by claywar — APPROVED** [review]

**Review by TeoTwawki — APPROVED** [review]
image

**Comment by kaincenteno** [comment]
That's so great for communication of changes 😃

**Comment by Era-Lusiphur** [comment]
Great execution. This way, titles can be babysit as PRs come in and otherwise no other thought or effort has to be given to it.

**Comment by zach2good** [comment]
^ Added the first parts of a "publish changelog" action

- Will run on the 1st and 15th of the month, walking back until it finds the previous 15th or 1st, and using that number of days to calculate the length of the changelog
- Doesn't publish yet, as we're still discussing how we're going to handle that

**Pull request merged**
