### PR TITLE
[core] Intialize uninitialized members, don't access out of bounds memory, add constructors, small memcpy fixes, fix various warnings

### PR DESCRIPTION
**Pull request by WinterSolstice8**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Initialize previously uninitialized members, memcpy fixes, fix various warnings, add tons of constructors to prevent uninitialized members.

## Steps to test these changes

Load xi_map with valgrind and get less "jump based on uninitialized member" notifications than before. ~~This is not a "functional" PR, but intended to help other debug tools such as valgrind report more "real" problems.~~

Test a bunch of stuff to make sure it still works:
- [x] Lobby
- [x] Logging in
- [x] Unity Rankings
- [x] Fishing ~~(including size/weight of catch)~~ (most fish are zeroed)
- [x] Trust Gambits/Trusts
- [x] Pathfinding (navmesh)
- [x] Battlefields
- [x] Looks on mob/npc/dynamic entity
- [x] Instances
- [x] Linkshell encode/decode
- [x] Item Signature encode/decode
- [x] Guild shop
- [x] Status Effects
- [x] Merit menu
- [x] Map regions
- [x] ROE
- [x] Treasure pool/lotting
- [x] Pets
- [x] Dynamic Entity in town + pathing

### CODE REVIEW

**Comment by WinterSolstice8** [comment]
Converted to draft because of needed testing with Unity

**Comment by zach2good** [comment]
Before this goes in, every area you've touched has to be tested :P

(I have done work like this before and gotten bitten later down the line for not testing everything thoroughly)

**Comment by WinterSolstice8** [comment]
I checked everything I could think of, made a checklist in the first post. If there's anything else worth testing, let me know. Seems everything works as I expect.

**Review by zach2good — APPROVED** [review]
If CI passes, and you've gone through that checklist, all we can do is unleash this on the codebase and hope for the best. Looks good to me though!

**Review by claywar — APPROVED** [review]

**Review by Xaver-DaRed — APPROVED** [review]

**Pull request merged**
