### PR TITLE
Interaction - Battlefields: ToAU Regions

### PR DESCRIPTION
**Pull request by claywar**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
* Converts existing battlefields in ToAU regions to Interaction Framework
* Adds battlefieldEntry and setupBattlefield functions for additional calls for onBattlefieldEnter and onBattlefieldInit
* Fixes Century of Hardship exitNpcs definition
* Updates Omens logic to spawn Flans prior to engage
* Adds additional mob spawn points for area 1 NPCs in Talacca Cove

## Steps to test these changes
Enter/Win/Exit/Lose battlefields.  Testing note: For Omens, add a for loop for battlefieldEntry function to iterate from 1, 17 in varying increments for additionalEntered value

### CODE REVIEW

**Comment by hooksta4** [comment]
I realize you wrote Converts existing, but out of curiosity, are you also doing the ones that are not implemented yet? Such as Against All Odds, Breaking the Bonds of Fate, Puppetmaster Blues, etc at a later date?

**Comment by claywar** [comment]
> I realize you wrote Converts existing, but out of curiosity, are you also doing the ones that are not implemented yet? Such as Against All Odds, Breaking the Bonds of Fate, Puppetmaster Blues, etc at a later date?

Completely out of scope for now, as I want to remove the old system in place.  I'll eventually create the skeletons for each one, but have no desire to implement the battle mechanics or tune existing battlefields with poor implementations.

**Comment by hookstar** [comment]
Understandable. I have a couple of those quests done in IF just not the battlefield portions (at least not fully fleshed out) it's under the old system so I'll abandon those and look to implement in battlefield framework. Should have lots of examples to go off now that you have done a tons worth of work with these. Cheers.

**Comment by claywar** [comment]
> Understandable. I have a couple of those quests done in IF just not the battlefield portions (at least not fully fleshed out) it's under the old system so I'll abandon those and look to implement in battlefield framework. Should have lots of examples to go off now that you have done a tons worth of work with these. Cheers.

None of what I have changed impacts the 32001 event finish, and all is currently handled in mission scripts.  Ideally, _no_ quest or mission interactions outside of requirements should ever happen inside of the battlefield scripts, so not sure what you're abandoning.

If its not converted, put it in the battlefield.  If it is, then it has no place in it.

**Comment by hooksta4** [comment]
I mean the quests that have battlefields, that currently do not exist in any capacity, I have started to do a few of them in zone/bcnm. I will stop that and move to battlefield/zone is what I am saying. The reason I was asking is I didn't want to duplicate efforts if you were going to be doing ones that were missing.

**Comment by claywar** [comment]
> I mean the quests that have battlefields, that currently do not exist in any capacity, I have started to do a few of them in zone/bcnm. I will stop that and move to battlefield/zone is what I am saying. The reason I was asking is I didn't want to duplicate efforts if you were going to be doing ones that were missing.

Gotcha, trust me I have no intention of touching anything outside of whats done currently for a bit, but I appreciate you moving toward the new standard.

**Review by Xaver-DaRed — APPROVED** [review]

**Review by zach2good — APPROVED** [review]

**Pull request merged**
