### PR TITLE
Correct recipe for "Silver Mail" used crystals

### PR DESCRIPTION
**Pull request by TonzoffunCE**
This recipe uses Earth/Terra crystals, not Fire/Inferno crystals.

You referenced both JPWiki and ffxiclopedia for this recipe, yet on both sites, the recipe calls for Earth/Terra crystals, not Fire/Inferno.
JPWiki: http://wiki.ffo.jp/html/10565.html
ffxiclopedia: https://www.ffxiah.com/item/12553/silver-mail

**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

You referenced both JPWiki and ffxiclopedia for this recipe, yet on both sites, the recipe calls for Earth/Terra crystals, not Fire/Inferno.
JPWiki: http://wiki.ffo.jp/html/10565.html
ffxiclopedia: https://www.ffxiah.com/item/12553/silver-mail

## Steps to test these changes

Edit the sql entry from Fire crystal (4096) to Earth crystal (4099), and Inferno crystal (4238) to Terra crystal (4241).

### CODE REVIEW

**Comment by EpicTaru** [comment]
@TonzoffunCE you need to edit the body of the post (click the 3 **. . .** and click **Edit**) and remove the space after the **x** in the checkboxes (make **[x ]**  look like **[x]**) in these:

> [x ] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
[x ] I have tested my code and the things my code has changed since the last commit in the PR and will test after any later commits.

In order for github-actions bot to play nice, lol.

**Comment by TonzoffunCE** [comment]
> @TonzoffunCE you need to edit the body of the post (click the 3 **. . .** and click **Edit**) and remove the space after the **x** in the checkboxes (make **[x ]** look like **[x]**) in these:
> 
> > [x ] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
> > [x ] I have tested my code and the things my code has changed since the last commit in the PR and will test after any later commits.
> 
> In order for github-actions bot to play nice, lol.

Thanks! Sorry -_-

**Comment by TonzoffunCE** [comment]
Fixed title length.

**Review by WinterSolstice8 — APPROVED** [review]

**Comment by TeoTwawki** [comment]
CI is complaining more about the commit message than the github title derived from it. It wants us to line break at or before 72nd char.

Git Amend can adjust the message, then you'll have to force push over the same branch.

`git commit --amend`

`Git push --force`

**Comment by WinterSolstice8** [comment]
"commit title is too long"
you need to use `git commit --amend` on commandline or your favorite GUI to amend the commit, the PR is not what the error message is about.

edit: Teo beat me, I should read first lol

**Comment by TonzoffunCE** [comment]
Okay, I'm just going to close this and do it from scratch because I did the PR through the github website, and I'm not sure how to do a git commit --amend through the website. I will simply do it like I normally would via Git Bash. Sorry for the confusion, apologies!

**Comment by TeoTwawki** [comment]
the website is kinda garbage and doesn't give an amend option. Strongly recommend getting a local git client but if you like I can reopen and fix this one for you as a one time deal.

Easy learning curve: git4windows + tortoisegit

**Comment by TonzoffunCE** [comment]
For sure, I'm just gunna use local git client going forward, thanks Teo :)

**Comment by TeoTwawki** [comment]
oh, I took "for sure" as go ahead and do it lol, just saw you open the other one.

**Comment by TonzoffunCE** [comment]
lol, sorry.. I should have never used the github website, I just didn't fully understand the expectations before creating the PR :(. The new PR should be appropriate :)!

**Review by Xaver-DaRed — APPROVED** [review]

**Pull request merged**
