### PR TITLE
[SQL] Update Mob skills and Mob skills lists for all Ark Angle Trusts

### PR DESCRIPTION
**Pull request by GravesXI**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

[SQL] Update Mob skills and Mob skills lists for all Ark Angle Trusts

This PR updates and fixes the Animation ID's and Weapon skill (Skill chain) id's

The information for the Skill chain id's was referenced through BGwiki based on Element

These abilities were tested on a fresh LSB pull with the SQL update and verified to be "Working as intended"

As these capture files are larger than expected with videos I have uploaded a single capture while the remainder will be put into a ZIP file for those who would request the information

(For privacy reasons I wish to not disclose my Retail Player information, if request please ask for the link information)

Co-Authored-By: N3ckB3ard <98081508+N3ckB3ard@users.noreply.github.com>

### CODE REVIEW

**Review by Xaver-DaRed — DISMISSED** [review]

**Comment by TeoTwawki** [comment]
trouble with git?

**Comment by GravesXI** [comment]
yeah so i closed to fixed it all and just going to resubmit after i get it all taken care of

**Comment by TeoTwawki** [comment]
suggest leaving base as 1:1 with our and creating additional branches for prs. if you  force push overtop the same branch as your pr used, it will auto update it on github regardless of its past history. So you can effectively delete commits by pushing new contents over it and pretend nothing happened.


In fact, nothing happens to my branches all the time. You didn't see nothin. If you think you saw something, you can't prove it! Thats my story and I am sticking to it.

**Comment by GravesXI** [comment]
i normally do make a branch but this was a fresh repo and was going to submit this with the other that worked on this with me didnt realize a lot of it was out of order so closed to fix everything and do the right way this time lesson learned lol

**Pull request closed without merging**
