### PR TITLE
[core, trust] Enable Trust AOE JA's and add stub Trust: Qultada logic

### LINKED ISSUE #617: Trust: Qultada, Phantom Roll only affects Trust. Possible Gambits Container issue?
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

As title states, I've been trying to become more familiar with the code and figured I'd take a crack and some starting logic for Qultada. I realized that while I can get him to roll, the effects of the rolls only apply to Qultada himself. I could not find any other instances in the current code where a TRUST job ability impacts the entire party.
```

		mob:addSimpleGambit(ai.t.SELF, ai.c.NOT_STATUS, xi.effect.CORSAIRS_ROLL, ai.r.JA, ai.s.SPECIFIC, xi.ja.CORSAIRS_ROLL)
		mob:addSimpleGambit(ai.t.SELF, ai.c.NOT_STATUS, xi.effect.CHAOS_ROLL, ai.r.JA, ai.s.SPECIFIC, xi.ja.CHAOS_ROLL)
		mob:addSimpleGambit(ai.t.TARGET, ai.c.ALWAYS, 0, ai.r.RATTACK, 0, 0, 10)


```

### PR DESCRIPTION
**Pull request by zach2good**
Fixes https://github.com/LandSandBoat/server/issues/617

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Review by Xaver-DaRed — APPROVED** [review]
LGTM
PR and condition aproved

**Comment by zach2good** [comment]
I tried a little bit to get Double Up and some other logic working, but that'll either require some COR specific additions to gambits in core, or to skirt gambits entirely by only using event listeners.

So, leaving Qultada dumb like the BRD trusts for now

**Comment by zach2good** [comment]
His damage output is pretty good though

**Comment by CatsEyeXI** [comment]
Thanks for the work Zach....

**Pull request merged**
