### PR TITLE
Escha zone settings

### PR DESCRIPTION
**Pull request by jarmengaud**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

Fixes:
#709 

(incorrect Escha zone settings)

### CODE REVIEW

**Comment by Xaver-DaRed** [comment]
Just so we are clear, this allows:
- Trusts (0x800)
- Pets (0x080)
- Tractor (0x010)
- Mazurka (0x008)

Total 0x898 aka 2200 in decimal.
correct?

**Comment by claywar** [comment]
Reasonable to me.  I can confirm that Pets and Trusts at minimum are allowed

**Review by Xaver-DaRed — APPROVED** [review]

**Review by claywar — APPROVED** [review]

**Comment by Omnione** [comment]
Can confirm i have been using 2200 in my escha branch and seems to work as intended

**Comment by jarmengaud** [comment]
Thanks a lot!

**Pull request merged**
