### PR TITLE
Add title reward for skewer sam

### PR DESCRIPTION
**Pull request by mumencoder**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Player will now receive the title 'Beakbender' when defeating the NM Skewer Sam. https://ffxiclopedia.fandom.com/wiki/Skewer_Sam

## Steps to test these changes

!spawnmob 17596507
!gotoid 17596507

### CODE REVIEW

**Comment by Xaver-DaRed** [comment]
That file needs a require for titles added

**Comment by TeoTwawki** [comment]
this didn't have to be closed to update it, and could have been reopened rather than making a new one

**Comment by mumencoder** [comment]
Yeah I switched forks and it deleted everything associated to it.

**Comment by TeoTwawki** [comment]
Yeah, in the future please just ask for help sorting your git out. It's almost always retrievable even if it looks gone at your end.

Maybe make a separate practice repo to learn git things. While github only lets you fork once, you can make "organizations" and fork to those easy, or make a whole new repo unrelated to us to practice things with.

**Comment by mumencoder** [comment]
It was a very specific issue, I was on TR11 which forked from LSB but it wouldnt let me PR to ASB so i had to switch to the TabulaRasaXI fork which does derive from ASB to do so. And it wouldnt let me fork ASB either separately. Not good!

**Comment by TeoTwawki** [comment]
> It was a very specific issue, I was on TR11 which forked from LSB but it wouldnt let me PR to ASB so i had to switch to the TabulaRasaXI fork which does derive from ASB to do so. And it wouldnt let me fork ASB either separately. Not good!

work flow issues. there are ways to accomplish it but you shouldn't have to. sorta thing I could show you if we needed to do it but I can't for the life of me put into words. In any case if you ever find yourself unable to fix a branch, we're pretty good about rescuing stuff just let us know you need help :+1:

**Pull request closed without merging**
