### PR TITLE
Change mob_family_system table structure to include "super family"

### PR DESCRIPTION
**Pull request by TeoTwawki**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

Family = Korrigan, lycopodium etc.
SuperFamily = Mandragora
Ecosystem = Plantoid

Plumbing to actually use this will be in a followup. The core queries don't yet use the columns so nothing functional has changed other than a handful of mistakes I corrected and moving "Unclassified" to ID zero.

Also changed casing of `familyid` to `familyID` and `systemid` to `ecosystemID` in just this one table. in pools and mods tables they are still lowercase - for now. I want to see fixed the casing of all table fields in every table someday, but not today.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
was not expecting a conflict..hadn't seen updated to the table

**Comment by TeoTwawki** [comment]
Ahhh  I hadn't pulled since before the meeble.

**Comment by TeoTwawki** [comment]
Rebased for Meeble Zach placed in middle of file out of sequence.
_begins rolling up a newspaper_

**Review by Xaver-DaRed — APPROVED** [review]
LGTM

**Pull request merged**
