### PR TITLE
db: Add ResultSetWrapper type

### PR DESCRIPTION
**Pull request by zach2good**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Changes syntax from:
```cpp
    auto zoneId = rset->getUInt("pos_zone");
```

to

```cpp
    auto zoneId = rset->get<uint16>("pos_zone");
```

Related issues: 
https://github.com/LandSandBoat/server/issues/4577
https://github.com/LandSandBoat/server/issues/6355

Testing
- [x] Login: Connect, Select Character, Enter game
- [x] Login: Create new character
- [x] Login: Delete character
- [x] Search: /sea all
- [x] Search: List and buy AH item
- [x] World: Send self a /tell
- [x] World: Send others a /tell
- [x] World: Party mechanics
- [x] Map: First time Login and CS
- [x] Map: Zoning
- [x] Map: GM commands, givegil, zoning, ah, etc.
- [x] Map: Stats are as they should be
- [x] HTTP Server works
- [x] Message Server works
- [x] Daily Tally works
- [x] Conquest System "works" as before
- [x] Synergy recipes are loaded
- [x] PUP attachments are loaded
- [x] Status effects work
- [x] Currency menus work
- [x] Augments work
- [x] Leave running overnight, see if there are ping things, etc.
- [x] You can enter and leave monstrosity correctly as your monster
- [x] Database metadata like names and versions are available to db::
- [x] Validation, reconnect, pinging, etc.
- [x] Charset validation
- [x] Keepalive settings
- [x] Char encoding
- [x] Autocommit func helpers
- [x] Transactions
- [x] Sprintf in stmt and query
- [x] Profiling

### CODE REVIEW

**Comment by zach2good** [comment]
While I'm here I'm also going to convert the SQL queries in charutils to be preparedstmts: https://github.com/LandSandBoat/server/issues/4577

**Comment by zach2good** [comment]
For my own peace of mind, I'm probably also going to add a test executable that communicates with a temporary test database, and writes/reads things into the db and confirms they've made it back OK.

I can also do comparative testing with the current db stuff. Once everything is confirmed, I can push harder to replace the existing system.

TODO:
- String escaping
- Validation/reconnection/pinging
- Charset stuff
- Keepalive settings
- Encoding
```
    std::string GetDatabaseName();
    std::string GetClientVersion();
    std::string GetServerVersion();
```
- Query helpers with fmt and sprintf built in
- autocommit
- transaction stuff
- profiling tools

**Comment by zach2good** [comment]
Even if I'm considering moving to a different SQL connector lib in the future, this is still useful as a layer of abstraction on top so the main code only changes once and I can futz with the underlying driver code

**Comment by zach2good** [comment]
Ready for review, I've gone through my testing list and everything is working as expected. Leaving it overnight tonight to see how it handles things

**Review by claywar — APPROVED** [review]

**Pull request merged**
