### PR TITLE
Remove duplicate `xi.zone.RESIDENTIAL_AREA` keys.

### LINKED ISSUE #221: `xi.zone` contains 4 duplicate keys for `RESIDENTIAL_AREA`.
I believe the Lua behavior will be to just accept the last entry for the duplicate key.

Currently it's set to four values `189`, `199`, `214`, `219`. I believe `219` will be used.

https://github.com/LandSandBoat/server/blob/094ec9f022916bc86b8d0efee166b626ec560c2c/scripts/globals/zone.lua#L289-L319

### PR DESCRIPTION
**Pull request by mrhappyasthma**
Lua tables take the last key in the initializer, so all of the earlier
keys were just being overwritten.

Also updated one comment that referred to the underlying value. (These
types of comments are brittle, as seen in this case, since they can
become stale. But I left it since it was pre-existing).

Fixes https://github.com/LandSandBoat/server/issues/221

TESTED=Verified using a `print` statement that in Lua the `xi.zone.RESIDENTIAL_AREA` was printing `219`. I also confirmed the Lua table behavior in a separate local sandbox test.

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by TeoTwawki** [comment]
History lesson from old man Teo: this was because somebody way back in dsp times was convinced that there are multiple zones for it for each place you can enter from for the shadowrealm wotg zones. They were _wrong_ but it slipped in. In truth residential zones aren't their own zone at all they are effective "sub-zones" and this is why they have all the textIDs and Cs Event IDs of the zone you enter from. We don't have a genuine implementation of sub-zonage so we kinda force it to give the client the info it expects and it "just works". For script purposes we still needed the zone defined though, making the duplicate keys a problem. /endLesson

:older_adult

Edit: if you teleport into those zone IDs, you get a replicate - its not a real mh, all the text ID and CS ID are missing, because its just a dummy copy for the model.:

**Review by TeoTwawki — APPROVED** [review]

**Comment by zach2good** [comment]
I'm happy someone else jumped on this one, I was unsure of the history, or if this was right. 👍

**Review by zach2good — APPROVED** [review]

**Comment by mrhappyasthma** [comment]
Very informative. Thank you for that context.

Although even if one believed that each residential area was its own unique zone with a unique ID, it would still need a unique key to be inside a Lua table.

(Also it's a bit strange that duplicate keys in a Lua table constructor is not an error... but alas, it works fine and just overwrites earlier entries.)

**Comment by TeoTwawki** [comment]
> 
> 
> Very informative. Thank you for that context.
> 
> Although even if one believed that each residential area was its own unique zone with a unique ID, it would still need a unique key to be inside a Lua table.
> 
> (Also it's a bit strange that duplicate keys in a Lua table constructor is not an error... but alas, it works fine and just overwrites earlier entries.)

its crazy that it happened when its 

A) so easy to prove/disprove

and B) you obviously can't have the same name for a variable or key in lua...derp. They just overwrite/replace when already there so normal Lua behavior is to rather than error simply update the value when it hits another instance of `name = number` defined.

**Comment by mrhappyasthma** [comment]
I would guess the underlying Lua implementation is designed to be simple and fault tolerant. But it is a detectable type of programmer error.

e.g.

```
myTable = {
  A = 'A',
  B = 'B',
  A = 'C',  -- You could detect internal duplicate keys while processing this, and at least show a warning... But ¯\_(ツ)_/¯
}
```

I suspect this is actually being handled internally like:

```
myTable = {}
myTable.A = 'A'
myTable.B = 'B'
myTable.A = 'C'  -- Perfectly valid overwrite.
```

**Pull request merged**
