### PR TITLE
Add mobMod to offset distance to a target mob closes in on

### PR DESCRIPTION
**Pull request by TeoTwawki**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
PR #2888 appears abandoned with requested edits not happening. This PR attempts to rescue that work while holding onto the original commits and attribution contained therein. https://github.com/LandSandBoat/server/pull/3751/files?diff=unified&w=1

Best reviewed with whitespace off, as I adjusted alignment when I renamed the modifier.

## Steps to test these changes
Spawn and aggro Claret. It should try and move on top of the player.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
Click draft during creation, github ignores it and I get the bot message anyway -_-

**Comment by CactuarXI** [comment]
I adapted the older stale commit of this into my server. One change you might need in `mob_controller.cpp, line 683`

```
            else if (CanMoveForward(currentDistance))
            {
                if (!PMob->PAI->PathFind->IsFollowingPath())
                {
                    // out of melee range, try to path towards
                    if (currentDistance > PMob->GetMeleeRange())
                    {
                        // try to find path towards target
                        PMob->PAI->PathFind->PathInRange(PTarget->loc.p, attack_range - 0.2f, PATHFLAG_WALLHACK | PATHFLAG_RUN);
                    }
                }
```

I changed 

`if (currentDistance > PMob->GetMeleeRange())`

to 

`if (currentDistance > closeDistance)`

otherwise, it creates a situation where the mob won't move closer to the player to the desired offset until the player move out of the mobs attack range.

Example: Mob aggro, moves up to player, player can keep backing up to the edge of the mob's attack range and the mob won't update it's move logic until out of melee range. Once the player leaves the mob's melee range then mob will move to proper offset as per the mod but then the player can back out again and possibly avoid potential aura effects if the radius is smaller than the mob's melee range.

**Comment by TeoTwawki** [comment]
@CactuarXI good to know. testing still in progress so we'll watch for that and adjust.

**Comment by TeoTwawki** [comment]
I'm probably going to have to account for the difference between attackRange (the variable) and GetMeleeRange(its source value) when the modifier is not in play. With no modifier involved, attackRange is offset from GetMeleeRange by 0.2

**Comment by TeoTwawki** [comment]
https://user-images.githubusercontent.com/6871475/232337691-432d40b4-d7e0-485b-8d96-5eddcf70f294.mp4

**Comment by TeoTwawki** [comment]
All set and tested.

The merge commits are harmless - I preferred having them over rebasing the other persons commit and winding up w/me sharing attribution on it. Pls do not squash.

**Comment by TeoTwawki** [comment]
note: no migration needed, mob family system is not a protected table

**Review by zach2good — APPROVED** [review]

**Review by Xaver-DaRed — APPROVED** [review]

**Pull request merged**
