### PR TITLE
Implement ENM Holy cow; Correct Bearclaw Pinnacle entrance required

### PR DESCRIPTION
**Pull request by CriticalXI**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

- Implement the ENM Holy Cow
- It is now required to be at the correct Bearclaw Pinnacle entrance now depending on the ENM or CoP mission.

## Steps to test these changes

Attempt to fight Apis and ensure that he has differing attack and damage taken depending on which 2hr animation is played.

### CODE REVIEW

**Review by Xaver-DaRed — APPROVED** [review]

**Review by claywar — APPROVED** [review]

**Comment by claywar** [comment]
Just need to resolve these merge conflicts, and seems good to go

**Comment by CriticalXI** [comment]
I've cleared up the conflicts, should hopefully be good to go now.

**Comment by Xaver-DaRed** [comment]
We need one last change:

`THE_PARTY_WILL_BE_REMOVED = 7410,`
Claywar just checked, it should be 7414 since june update

Update: Dealt with.

**Comment by CriticalXI** [comment]
> 

Got that fixed

**Comment by TeoTwawki** [comment]
:prayer_beads: :cow: 

Always happy to see missing ENM get done <3

**Pull request merged**
