### PR TITLE
Add Mod to Shapers Shawl and Fix Artificers ring. Issue #1103

### PR DESCRIPTION
**Pull request by hooksta4**
Shaper's Shawl Skill up 25% https://www.bg-wiki.com/ffxi/Shaper%27s_Shawl
Artificer ring had noHQ mods when it shouldnt.

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Review by Xaver-DaRed — DISMISSED** [review]

**Comment by Skerxan** [comment]
Idk if Artificier's ring should get the skill+1 mod since that would also increase HQ chance.

**Comment by hooksta4** [comment]
SYNTH_SUCCESS                   = 851, -- Rate of synthesis success

**Comment by hooksta4** [comment]
Oh I see I mislabeled the title - its not skill +1 but rather synth success +1

**Comment by Xaver-DaRed** [comment]
For future PRs.

If you are going to tackle several different issues, create different PRs instead of pushing it to an already open, reviewed and aproved PR.

**Comment by hooksta4** [comment]
> For future PRs.
> 
> If you are going to tackle several different issues, create different PRs instead of pushing it to an already open, reviewed and aproved PR.

Is it possible to pull them back?

**Comment by Xaver-DaRed** [comment]
Dont
It is possible, but leave it like it is

**Comment by hooksta4** [comment]
Ill get it eventually! Thanks for all your diligent work, it is much appreciated.

**Review by Xaver-DaRed — APPROVED** [review]
Re-Reviewed. Changes seem fine.

**Pull request merged**
