### PR TITLE
[trust] Add Quest and Impl. for Trust: Maat

### PR DESCRIPTION
**Pull request by zach2good**
As it turns out, I've already set up Trust: Maat. I just left out some of his moves pending captures. MrSent sent me the captures I need... so... here's Maat!

image

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by zach2good** [comment]
Video here to aid with searching
https://www.youtube.com/watch?v=5ys-t_LjeY0

**Comment by zach2good** [comment]
Ru'Lude Gardens doesn't have an event dump, so through some careful trial and error I have found the following CSs:

Cherukiki Trust CS: 10235
Jamal: 10236
Maat Trust CS: 10241

**Comment by zach2good** [comment]
Appears as though we don't have `npcUtil.giveReward`

**Comment by zach2good** [comment]
Ready 👍

**Review by claywar — APPROVED** [review]

**Pull request merged**
