### PR TITLE
[MariaDB] Update to MariaDB Connector v3.1.10

### PR DESCRIPTION
**Pull request by zach2good**
- Added tools/build_mariadb_dep.bat
- Added auto-copy dll at configure-time
- Replaced MySQL headers with the packaged headers from MariaDB
- Started renaming MySQL to MariaDB, where appropriate

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by zach2good** [comment]
Need people with old OS's to test this:
- WinXP (Do we support it? I don't think we do?)
- Win7
- Win8
- Win10

I built with `Visual Studio 2022 (v143)` and `Windows SDK 10.0.19041.0`

**Comment by TeoTwawki** [comment]
> WinXP (Do we support it? I don't think we do?)

dsp dropped support for it like 2016 ish, before lsb or even topaz was born

**Review by TeoTwawki — APPROVED** [review]

**Review by claywar — APPROVED** [review]

**Comment by zach2good** [comment]
Gonna test more configurations of builds before I merge this

**Comment by zach2good** [comment]
Based on my findings in this comment: https://github.com/LandSandBoat/server/issues/1286#issuecomment-1042649605
I'm going to add blocking re-connect to this PR.

Logic:
```
Ping
if ping fails, try to reconnect and ping 10 times at 1-second intervals
if that fails, log and kill the server
```

**Comment by zach2good** [comment]
Set SQL ping to 5 seconds, so there's a little overlap, but it looks stable:

```
[02/17/22 10:10:19:277][map][info][info] Pinging SQL server to keep connection alive... (Sql_P_KeepaliveTimer:243)
[02/17/22 10:10:19:277][map][info][info] Pinging SQL server to keep connection alive... (Sql_P_KeepaliveTimer:243)
[02/17/22 10:10:24:277][map][info][info] Pinging SQL server to keep connection alive... (Sql_P_KeepaliveTimer:243)

(stop MariaDB service)

[02/17/22 10:10:24:278][map][info][sql] Lost connection to server during query (Sql_Ping:202)
[02/17/22 10:10:24:278][map][info][sql] Trying to reconnect to the database (1/10) (Sql_Ping:207)
[02/17/22 10:10:26:340][map][info][sql] Can't connect to server on '127.0.0.1' (10061) (Sql_Ping:223)
[02/17/22 10:10:27:351][map][info][sql] Trying to reconnect to the database (2/10) (Sql_Ping:207)
[02/17/22 10:10:29:392][map][info][sql] Can't connect to server on '127.0.0.1' (10061) (Sql_Ping:223)
[02/17/22 10:10:30:398][map][info][sql] Trying to reconnect to the database (3/10) (Sql_Ping:207)
[02/17/22 10:10:32:435][map][info][sql] Can't connect to server on '127.0.0.1' (10061) (Sql_Ping:223)
[02/17/22 10:10:33:435][map][info][sql] Trying to reconnect to the database (4/10) (Sql_Ping:207)

(start MariaDB service)

[02/17/22 10:10:33:436][map][info][info] Pinging SQL server to keep connection alive... (Sql_P_KeepaliveTimer:243)
[02/17/22 10:10:33:436][map][info][sql] Lost connection to server during query (Sql_Ping:202)
[02/17/22 10:10:33:436][map][info][sql] Trying to reconnect to the database (1/10) (Sql_Ping:207)
[02/17/22 10:10:35:424][map][info][info] Pinging SQL server to keep connection alive... (Sql_P_KeepaliveTimer:243)
[02/17/22 10:10:35:424][map][info][info] Pinging SQL server to keep connection alive... (Sql_P_KeepaliveTimer:243)
[02/17/22 10:10:40:428][map][info][info] Pinging SQL server to keep connection alive... (Sql_P_KeepaliveTimer:243)
[02/17/22 10:10:40:428][map][info][info] Pinging SQL server to keep connection alive... (Sql_P_KeepaliveTimer:243)
```

**Comment by zach2good** [comment]
```
[02/17/22 10:12:32:776][map][info][sql] Can't connect to server on '127.0.0.1' (10061) (Sql_Ping:223)
[02/17/22 10:12:33:782][map][info][sql] Trying to reconnect to the database (7/10) (Sql_Ping:207)
[02/17/22 10:12:35:814][map][info][sql] Can't connect to server on '127.0.0.1' (10061) (Sql_Ping:223)
[02/17/22 10:12:36:822][map][info][sql] Trying to reconnect to the database (8/10) (Sql_Ping:207)
[02/17/22 10:12:38:872][map][info][sql] Can't connect to server on '127.0.0.1' (10061) (Sql_Ping:223)
[02/17/22 10:12:39:885][map][info][sql] Trying to reconnect to the database (9/10) (Sql_Ping:207)
[02/17/22 10:12:41:940][map][info][sql] Can't connect to server on '127.0.0.1' (10061) (Sql_Ping:223)
[02/17/22 10:12:42:953][map][info][sql] Trying to reconnect to the database (10/10) (Sql_Ping:207)
[02/17/22 10:12:44:964][map][info][sql] Can't connect to server on '127.0.0.1' (10061) (Sql_Ping:223)
[02/17/22 10:12:45:973][map][critical][fatalerror] Could not reconnect to the database 10 times! Exiting. (Sql_Ping:229)

[process exited with code 3221225477]
```

**Comment by zach2good** [comment]
To test before this is ready to go:
- Windows: Fresh cmake command line build (debug) -> Run
- Windows: Fresh cmake command line build (release) -> Run
- Windows: Cmake build debug, swap to release and build, swap back to debug and build -> Run
- Windows: Cmake build debug, swap to release and build, swap back to debug and build -> Run
- Windows: Generate sln, build debug -> Run
- Windows: Generate sln, build release -> Run
- Windows: Generate sln, build debug, swap to release and build, swap back to debug and build -> Run
- Windows: Generate sln, build release, swap to debug and build, swap back to release and build -> Run
- Linux: Just a regular build and run, is already covered by CI

Under all these scenarios, the relevant DLLs should be copied into root just before the build starts.

**Comment by zach2good** [comment]
Handling this in my other PR: https://github.com/LandSandBoat/server/pull/1327

**Pull request closed without merging**
