### PR TITLE
Garrison Cleanup

### PR DESCRIPTION
**Pull request by RunAwayDSP**
Fixed Text ID Renamed to GARRISON_BASE

Fixed Settings converted ; to ,

Fixed droplist with  UNCOMMON

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by zach2good** [comment]
Careful how you use '@' in comments and commits, you're tagging some poor unrelated user:
image

**Review by zach2good — APPROVED** [review]
Looks fine, once that commit message is fixed to not tag a GH user 👍

**Comment by RunAwayDSP** [comment]
Fixed the tag

**Comment by zach2good** [comment]
You must have missed a force-push, it's still there:
image

**Comment by RunAwayDSP** [comment]
now that Im back from work this should be corrected...

**Review by claywar — APPROVED** [review]

**Review by zach2good — APPROVED** [review]

**Pull request merged**
