### PR TITLE
Import Nyzul global from #1478

### PR DESCRIPTION
**Pull request by claywar**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?
* Imports Nyzul global from #1478
* Renames appraisalUtil.Origin to appraisalUtil.origin

## Steps to test these changes
Not exposed to the player at this time

### CODE REVIEW

**Comment by TeoTwawki** [comment]
`appraisalUtil` - are there appraisal things that are not util needing the namespace `appraisal`? it just feels so awkward.

**Comment by zach2good** [comment]
I believe thats just a remnant of how KO laid things out, to be somewhat project agnostic. We could change it if we wanted

**Comment by claywar** [comment]
I'm onboard with just simplifying to `appraisal`

**Review by Xaver-DaRed — APPROVED** [review]

**Comment by TeoTwawki** [comment]
k, hadn't seen the rest yet to know if the term was "free"

**Review by TeoTwawki — APPROVED** [review]

**Pull request merged**
