### PR TITLE
[chore] Replace int8* "strings" with std::string

### PR DESCRIPTION
**Pull request by WinterSolstice8**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Replace int8* "strings" with std::string
## Steps to test these changes

Linkshells:
check lsmes, upgrade/downgrade pearlsack, kick, get linkshell list
check equipped name on player via /check

Parties:
/pcmd leader, /pcmd kick, /acmd kick, pcmd leader, get party list

Item signatures:
signing items, /check on signed items displaying, /check in bazaar items displaying

ZMQ messages:
/p, /l messages, `gm CharacterName 5` command in map console

Lua stuff:
get name of pet, get name of ability, no errors talking to NPCs, using abilities, pets using abilities, 

use /tells

Things I haven't covered, but are also used in general gameplay/startup.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
Death to int8 strings! 
image

**Comment by WinterSolstice8** [comment]
Tested everything I could think of that would be directly observable as junk strings and not just produce an error in the log, ready for review

**Review by zach2good — APPROVED** [review]
I pulled this down locally and had a poke around, looks good 👍

**Review by claywar — APPROVED** [review]

**Comment by zach2good** [comment]
image

**Pull request merged**
