### PR TITLE
[core] change getAllianceSize() to actually get alliance size

### LINKED ISSUE #6496: Function getAllianceSize() Returns Party Size
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows11

## Branch affected by issue

Base

## Steps to reproduce

I made two parties, two in each with 4 characters total. I formed the two parties into one alliance. When I call getAllianceSize() it returns 2. I also get 2 when I call getPartySize().

## Expected behavior

The description of the function is that it returns the amount of people in the alliance.
"Purpose : Returns the number of members in the alliance"
I would expect that it would return 4 members.

### PR DESCRIPTION
**Pull request by WinterSolstice8**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

change getAllianceSize() to actually get alliance size

Closes #6496 
## Steps to test these changes

see
`!exec print(player:getAllianceSize())` return sane values

### CODE REVIEW

**Review by Xaver-DaRed — APPROVED** [review]

**Comment by Xaver-DaRed** [comment]
Theres issues that have to be solved. Data type conversions

**Comment by zach2good** [comment]
2x party of 2, make an alliance, `!exec print(player:getAllianceSize())`, -> 4

All good 👍 

image

**Comment by zach2good** [comment]
With the casting:
```cpp
uint8 CLuaBaseEntity::getAllianceSize()
{
    if (m_PBaseEntity->objtype == TYPE_NPC)
    {
        ShowWarning("CLuaBaseEntity::getAllianceSize() - NPC passed to function.");
        return 1;
    }

    auto* PBattle      = static_cast<CBattleEntity*>(m_PBaseEntity);
    uint8 alliancesize = 1;

    if (PBattle->PParty != nullptr)
    {
        if (PBattle->PParty->m_PAlliance != nullptr)
        {
            // Reset to use as counter..
            alliancesize = 0;
            for (const CParty* PParty : PBattle->PParty->m_PAlliance->partyList)
            {
                alliancesize += static_cast<uint8>(PParty->members.size());
            }
        }
        else
        {
            return static_cast<uint8>(PBattle->PParty->members.size());
        }
    }

    return alliancesize;
}
```

**Comment by WinterSolstice8** [comment]
casting should be fixed

**Pull request merged**
