### PR TITLE
Cache GM commands into xi.commands, remove global CI exceptions for command functions

### PR DESCRIPTION
**Pull request by claywar**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
* Caches GM commands into xi.commands to no longer need to reload from disk every time one is executed
* Removes unused ScopeGuard class after changing command handler
* Removes global exceptions for cmdprops, onTrigger, fileExists, and error from CI

## Steps to test these changes
* Use a GM command in commands
* Use a GM command in modules
* Reload a GM command in modules
* Reload a GM command in commands
* Add a new GM command in commands
* Add a new GM command in modules

### CODE REVIEW

**Comment by zach2good** [comment]
Additional things to check:
- Make sure GM levels are honoured
- Make sure GM levels are honoured when back-to-back commands with different levels are called
- Make sure hot-reloading, back-to-back commands, and changing GM levels from console/GM commands/db editing don't allow elevated privileges

**Review by zach2good — APPROVED** [review]
By their very design, I know that these changes are safe, but I'm sure downstream would feel more at ease after some testing and confirmation

**Comment by claywar** [comment]
image

**Comment by claywar** [comment]
After hot reload of command, changing exec to GM 5, character at GM 4
image

Also tested back to back commands with different levels between reload, all permissions were preserved.

**Pull request merged**
