### PR TITLE
[Quest] The Fanged One Interaction Framework

### PR DESCRIPTION
**Pull request by hooksta4**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
Had an issue with my rebase - ended up closing https://github.com/LandSandBoat/server/pull/5381
and redoing it here.

Converts the quest The Fanged One (RNG Flag) to Interaction Framework

Adds functionality for Old Sabertooth to path in the hallway.
Adjusted the poison effect to ~2%/tic as per the capture.
Added listener to Old Sabertooth (in the mob lua file) to capture if players damaged the mob. If they do, they incur a 5 min wait timer to respawn.
Replaced NPC lua events into DefaultActions.lua
Capture shows black tiger fang being traded and taken during quest.

## Steps to test these changes
Be on any job 30+ and speak with Perih Vasha.

Capture located at
https://www.youtube.com/watch?v=FWtjEDaDG7s

### CODE REVIEW

**Review by Xaver-DaRed — APPROVED** [review]

**Comment by hookstar** [comment]
Circling back to see if there was anything else needed for this to get merged?
 Thanks

**Comment by hooksta4** [comment]
Just a quick follow up for status on this?

**Comment by hooksta4** [comment]
Wanted to get a quick update - is there anything else needed for this?

**Comment by hookstar** [comment]
@claywar can i get you to give a looksie at this one. please? Thanks.

**Pull request merged**
