### PR TITLE
Faust wandering and only facing North and East

### PR DESCRIPTION
**Pull request by m241dan**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Changes Faust to be more retail accurate. The only possible "hole" here is that I don't know if he wanders back in stages or wanders straight home after aggro'ing and killing someone or them zoning.

## Steps to test these changes

1. Go to The Shrine of Ru'Avitau
2. !pos 740 0 -99
3. Watch Faust walk around and not act like he's supposed to, and then frown to yourself

### CODE REVIEW

**Comment by CatsEyeXI** [comment]
Faust is currently popping off of the map.. I'm not sure if you've come across this but thought i'd mention it..

image

image

**Comment by m241dan** [comment]
> Faust is currently popping off of the map.. I'm not sure if you've come across this but thought i'd mention it..
> 
> image
> 
> image

Using this PR?

**Comment by CatsEyeXI** [comment]
Nope, I wasn't sure if this was supposed to address that

**Comment by m241dan** [comment]
> Nope, I wasn't sure if this was supposed to address that

It doesn't because that was 100% not happening for me.

**Comment by CatsEyeXI** [comment]
> > Nope, I wasn't sure if this was supposed to address that
> 
> It doesn't because that was 100% not happening for me.

Just trying to due my due diligence, sir. I searched for open PR's before opening an issue for it and came across this.

**Comment by m241dan** [comment]
> > > Nope, I wasn't sure if this was supposed to address that
> > 
> > 
> > It doesn't because that was 100% not happening for me.
> 
> Just trying to due my due diligence, sir. I searched for open PR's before opening an issue for it and came across this.

Yah, that's certainly weird. If you manually inspect your database, what's his starting position?

**Comment by CatsEyeXI** [comment]
> > > > Nope, I wasn't sure if this was supposed to address that
> > > 
> > > 
> > > It doesn't because that was 100% not happening for me.
> > 
> > 
> > Just trying to due my due diligence, sir. I searched for open PR's before opening an issue for it and came across this.
> 
> Yah, that's certainly weird. If you manually inspect your database, what's his starting position?

image

**Comment by m241dan** [comment]
> > > > > Nope, I wasn't sure if this was supposed to address that
> > > > 
> > > > 
> > > > It doesn't because that was 100% not happening for me.
> > > 
> > > 
> > > Just trying to due my due diligence, sir. I searched for open PR's before opening an issue for it and came across this.
> > 
> > 
> > Yah, that's certainly weird. If you manually inspect your database, what's his starting position?
> 
> image

And I'm out of helpful responses, because that looks good lol.

Does it happen every time?

**Comment by CatsEyeXI** [comment]
> > > > > > Nope, I wasn't sure if this was supposed to address that
> > > > > 
> > > > > 
> > > > > It doesn't because that was 100% not happening for me.
> > > > 
> > > > 
> > > > Just trying to due my due diligence, sir. I searched for open PR's before opening an issue for it and came across this.
> > > 
> > > 
> > > Yah, that's certainly weird. If you manually inspect your database, what's his starting position?
> > 
> > 
> > image
> 
> And I'm out of helpful responses, because that looks good lol.
> 
> Does it happen every time?

I'll keep an eye on it.. It was only reported to me recently... Could it be a player POS hacking and Faust tried to follow?

**Comment by m241dan** [comment]
> > > > > > > Nope, I wasn't sure if this was supposed to address that
> > > > > > 
> > > > > > 
> > > > > > It doesn't because that was 100% not happening for me.
> > > > > 
> > > > > 
> > > > > Just trying to due my due diligence, sir. I searched for open PR's before opening an issue for it and came across this.
> > > > 
> > > > 
> > > > Yah, that's certainly weird. If you manually inspect your database, what's his starting position?
> > > 
> > > 
> > > image
> > 
> > 
> > And I'm out of helpful responses, because that looks good lol.
> > Does it happen every time?
> 
> I'll keep an eye on it.. It was only reported to me recently... Could it be a player POS hacking and Faust tried to follow?

I don't know your players, and would hate to speak ill of them, but that seems likely...

**Comment by Mortalelite** [comment]
I have tested this and not happening either, he spawns where suppose to.

**Comment by CatsEyeXI** [comment]
> I have tested this and not happening either, he spawns where suppose to.

thanks for confirming... could very well be player shenanigans...

**Comment by m241dan** [comment]
> > I have tested this and not happening either, he spawns where suppose to.
> 
> thanks for confirming... could very well be player shenanigans...

Hey, good on you for doing your due deligence instead of just posting.

**Review by zach2good — APPROVED** [review]

**Pull request merged**
