### PR TITLE
[core] Add null check for PGuildShop in SmallPacket0x0AA

### PR DESCRIPTION
**Pull request by CatsEyeXI**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [?] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Adds security checks to `SmallPacket0x0AA` for guild being null.

### CODE REVIEW

**Comment by zach2good** [comment]
Co-authored-by works like this:

Your commit message:
```
Something like a title

(optional) a more detailed description

Co-authored-by: name <email>
Co-authored-by: name2 <email2>
```

**Comment by RunAwayDSP** [comment]
I approve this title I am 99% sure we should use it for anything zach helps with


I could be wrong but im okay being wrong

**Comment by CatsEyeXI** [comment]
believe it or not i am actively smashing my head against a wall trying to interactively rebase this

**Review by WinterSolstice8 — APPROVED** [review]
looks good to me

**Pull request merged**
