### PR TITLE
Fixes issue #818 - Gaze moves won't affect blinded targets.

### PR DESCRIPTION
**Pull request by TeoTwawki**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Review by Xaver-DaRed — APPROVED** [review]

**Comment by TeoTwawki** [comment]
will reopen this if it wind sup being proven, I just found a source disputing this mechanic.

**Comment by zach2good** [comment]
If this ends up being contested, or wanted but not accurate, it would make an easy module

**Comment by TeoTwawki** [comment]
> If this ends up being contested, or wanted but not accurate, it would make an easy module

From what I can tell this is one of those enduring myth deals like crafting compass direction. I think it'd be a nice module, and went ahead of use the code form this PR on my own server for now because I thought it was kind of neat and to hopefully encourage some alchemy.

**Comment by claywar** [comment]
Agreed.  There is on conclusive evidence for this being true, though I remember the rumors back in the day.

**Pull request closed without merging**
