### PR TITLE
Adjust max value only math.random() to be inclusive of upper value

### PR DESCRIPTION
**Pull request by claywar**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?
Adjusts math.random(maxVal) to include maxVal

## Steps to test these changes
Loop math.random(4) repeatedly until a value of 4 is returned

### CODE REVIEW

**Review by Xaver-DaRed — APPROVED** [review]

**Review by TeoTwawki — APPROVED** [review]

**Comment by TeoTwawki** [comment]
_Teo's urge to commit violence over the results of `math.random(100)` finally subsides_

**Review by zach2good — APPROVED** [review]
Are we ready for potential weeks of horror? 👀

**Comment by TeoTwawki** [comment]
> Are we ready for potential weeks of horror? eyes

let them come. I have an axe.

**Comment by cocosolos** [comment]
> Are we ready for potential weeks of horror? 👀

Maybe smaller breakage than you might expect, I think this is actually [how it originally worked](https://github.com/LandSandBoat/server/commit/2526b658288e9bbccfca8a9d11dc97864244ef01#diff-eeb9cc690647d9c2f5d1415ca5da922f2bbba9b3d3867d51035264276ac2fc05L342) before the Sol refactor anyway so anything predating that should work and has actually been broken (unless fixed in the interim).

**Pull request merged**
