### PR TITLE
[WIP][core] Mark areas that break CSs

### PR DESCRIPTION
**Pull request by zach2good**
TODO: Do an actual fix. This just removes the problem areas! No idea what the further ramifications of this are 

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by kaincenteno** [comment]
what is breaking CSs? (sorry i didnt understand this PR and would love to understand it)

**Comment by claywar** [comment]
Its a draft, and is here just for reference.

**Comment by zach2good** [comment]
A quick writeup of whats going on here:

**Packet flow**
1) When a cutscene starts the server sends the client the information for that cs, and the client starts playing the cs.
2) When there are options or updates, the client sends packets back to the server and `PChar->m_event` is checked to see if it matches what the client sent.
3) When the cs ends, the same update packet is sent by the client, with a different flag. `PChar->m_event` is checked, and if everything matches up, the cs will end as expected.

**Problem:**
If you are attacked, or a mob you are on the enmity list for dies while you're in a cs, your `PChar->m_event` is reset. So when the ending packet arrives nothing will match up and you're left in a state of limbo. 

**This PR:**
Just to prove a point, stops those resets happening entirely - and the black screens go away because the event information isn't incorrectly wiped.

**But wait...**
When I say the event information is wiped, I really mean that the _current_ event information is reset and then overwritten by a potential new event - leaving the original information that the client has dangling. I've only shifted the problem to the incoming event, away from the original event.

The real solution here is to keep track of all events that are requested and only remove them `onZone`, when a hard-release packet arrives, or when the correct ending packet for that event arrives. That's what the "actual implementation" of this will be. I have some snippets from Ino that give me a good place to start from.

The danger here is that anything written poorly will allow players to cheese mechanics. If you make _all_ cutscenes dump all hate and make a player invulnerable, players will abuse that - I'm told this is a way retail players first beat AV back in the day.

On the other hand, there are cutscenes that _need_ to do that. So, this has to be applied iteratively to any cutscenes that need the special properties, on a case-by-case basis.

**Comment by TeoTwawki** [comment]
I'd like to propose making actual use of [the "in event" flag already in the enumeration](https://github.com/LandSandBoat/server/blob/443b51122bf01a150ab574798d63468567f05651/src/common/mmo.h#L42), and bake setting it into an alternate event start command. say, `player:startMovieEvent(csid, {misc arguments} )` if we have the in_event flag on the player, make'em agro immune (validTarget returns false) and don't screw their m_event. If no flag? _event skipped_ and forcibly release from event, let'em get their rears kicked.

**Comment by zach2good** [comment]
Superceded by https://github.com/LandSandBoat/server/pull/653
Hooray!

**Pull request closed without merging**
