### PR TITLE
NM_LOTTERY_COOLDOWN is not enabled

### PR DESCRIPTION
**Pull request by mikeyuzu**
bug fix

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to Topaz Next's [Limited Contributor License Agreement](https://github.com/DerpyProjectGroup/topaz/blob/info/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/DerpyProjectGroup/topaz/blob/info/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

Spelling mistake
NM_LOTTERYCOOLDOWN -> NM_LOTTERY_COOLDOWN

### CODE REVIEW

**Comment by TeoTwawki** [comment]
this is the last time I am saying it: ***you are basing your work on the wrong branch***

**Comment by TeoTwawki** [comment]
image
In order to be safe for all branches, work must not be based out of freedom branch. 

stable -> freedom = ok!
freedom -> stable = broken!

When I set base to `allegedly-stable` I should ONLY see the new work, not other changes in the freedom branch. It breaks the workflow. I have asked you to base work on stable multiple times on multiple pull requests now.

**Comment by mikeyuzu** [comment]
sorry.
I seem to be fundamentally misunderstanding.
I'm sorry to have taken the trouble.
I will study again...

**Comment by TeoTwawki** [comment]
> 
> 
> sorry.
> I seem to be fundamentally misunderstanding.
> I'm sorry to have taken the trouble.
> I will study again...

@mikeyuzu on your fork, make a new branch that is **identical** to https://github.com/DerpyProjectGroup/topaz/tree/allegedly-stable and put your changes to it. this allows me to merge your change into all branches here, and not just freedom only. Freedom will get new content first normally but work cannot start from it, because then it contains other changes too. Understand?

**Comment by mikeyuzu** [comment]
@TeoTwawki 
Thank you.
I missed the allegedly-stable branch even though it was pointed out many times.

**Comment by Xaver-DaRed** [comment]
@mikeyuzu 
This is a learning experience. It's ok, none of us get it right all the time.

**Pull request closed without merging**
