### PR TITLE
[Quest] Ducal Hospitality

### PR DESCRIPTION
**Pull request by jamesbradleym**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Implement's quest Ducal Hospitality from [ASB Commit](https://github.com/AirSkyBoat/AirSkyBoat/commit/314d11c49e6c2ecca274dd079418da3160511ff7) with bug fix for duplicate first reward.

## Steps to test these changes

- Speak with Taillegeas in Ru-Lude Gardens with >= 4 Jueno fame and A Vessel Without a Captain quest completed.
- Find requested items
- ??
- Profit

### CODE REVIEW

**Comment by zach2good** [comment]
Looks like you're heavily in need of a rebase

**Comment by zach2good** [comment]
Relevant file: https://github.com/LandSandBoat/server/blob/ca0fa7ea4487add285c9e060a959468c51eeeca1/scripts/quests/jeuno/Ducal_Hospitality.lua

Generally, I don't see anything wrong with the actual new quest file apart from this (but I'm not a quest expert):
```lua
utils.ternary(player:hasCompletedMission(xi.mission.log_id.COP, xi.mission.id.cop.THE_WARRIORS_PATH), 1, 0),
```

This is quite hard to read, compared to the Lua-ism that we use in many many places of:
```lua
local warriorsPathComplete = player:hasCompletedMission(xi.mission.log_id.COP, xi.mission.id.cop.THE_WARRIORS_PATH) and 1 or 0
... then use warriorsPathComplete in your statement, etc. ...
```

**Comment by jamesbradleym** [comment]
> Looks like you're heavily in need of a rebase

B'ah, I missed this when I ran out the door after fetching. Will resolve!

**Comment by jamesbradleym** [comment]
https://github.com/LandSandBoat/server/pull/5340

**Pull request closed without merging**
