### PR TITLE
Boost doesn't even have any tick code in its effect script

### PR DESCRIPTION
**Pull request by TeoTwawki**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [:crossed_fingers: ] that I've _**tested my code honest sir and things my code changed what can possibly go wrong anyway**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Review by Era-Lusiphur — APPROVED** [review]

**Review by zach2good — APPROVED** [review]

**Review by claywar — COMMENTED** [review]
Might be out of scope for this PR, but the duration for boost isn't 180s (ref: https://forum.square-enix.com/ffxi/threads/52969?p=599066#post599066)

**Comment by TeoTwawki** [comment]
> 
> 
> Might be out of scope for this PR, but the duration for boost isn't 180s (ref: https://forum.square-enix.com/ffxi/threads/52969?p=599066#post599066)

very out of scope, because boost now works very differently and not only has duration changed, but the whole effect itself has been changed.

old:

https://www.bg-wiki.com/index.php?title=Boost&oldid=102
> Duration: | 0:03:00
Recast Time: | 0:00:30
Raises user's attack by 12.5% and increases damage of Chi Blast
Effect stacks with subsequent uses of the ability.</li>
Effect wears off after the next attack, Chi Blast, speaking to an NPC, or after three minutes from the initial use.

new:

https://www.bg-wiki.com/ffxi/Boost
> Duration | 4.0 x Your current attack delay. Minimum duration: 5 sec
Recast | 00:00:60
    Autoattack delay will triple while active.
        This is affected by various sources of delay reduction
    The next autoattack will deal increased damage and generate increased TP if it connects, but never multi-attacks.
        Damage is multiplied by (820/256 + STR/400) and 400% increase in TP for level 99 Monk main, combining the entire attack round into one swing (so 800% of one fist).
        Damage is multiplied by (444/256 + STR/400) and 200% increase in TP for Monk sub
            Sources of additional base damage (like Sneak Attack or Trick Attack) are applied after this multiplication.
    While active, the next weapon skill used will deal increased damage proportional to the time waited after activating Boost.
        For a level 99 Monk, this is approximately 1.4x damage if used at the end of the Boost timer Verification Needed.
        You do not receive the extra TP if a weaponskill is used.
    Effect stacks with Weapon Skills and other damaging Job Abilities such as Jump.Verification Needed
    Increases damage of Chi Blast (see page for details).Verification Needed
    Effect immediately wears off if weapon is changed.

New version is needlessly complicated while not being all that useful in game so far (currently leveling monk on retail, I'm almost 50, and boost more often than not simply screws me out of damage I could have done when a trust finishes off a mob before my ws macro finishes... And then I have to wait for it to wear off to engage the next mob. YAY.

**Comment by ShiyoKozuki** [comment]
Boost is completely useless in retail, but if you want 1:1 emulator you should "eventually" do it.

**Comment by TeoTwawki** [comment]
> 
> 
> Boost is completely useless in retail, but if you want 1:1 emulator you should "eventually" do it.

good candidate for a module so we can pretend this horrid change never happened >.>

**Pull request merged**
