### PR TITLE
[sql][lua]Add 108-Knot Quipu item, add missing despoiled items to items.lua global

### PR DESCRIPTION
**Pull request by EpicTaru**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

- Adds 108-Knot Quipu item to relevant mobs (mobs/drop rate per FFXIDB)
  - Garlaige Citadel [S] and Sauromugue Champaign [S]
    - **Yagudo Abbot** - MobIDs `17178829`, `17178839`, `17178846`, `17448964`, `17448983`, `17449025`
    - **Yagudo Lutenist** - MobIDs `17178834`, `17178845`, `17178849`, `17448976`, `17449001`, `17449020`
    - **Yagudo Missionary** - MobIDs `17178830`, `17178840`, `17178843`, `17448973`, `17449002`, `17449019`
    - **Yagudo Prior** - MobIDs `17178832`, `17178838`, `17178847`, `17448969`, `17448984`, `17449026`
    - **Yagudo Pythoness** - MobIDs `17178835`, `17178841`, `17178850`, `17448977`, `17449003`, `17449023`
    - **Yagudo Zealot** - MobIDs `17178831`, `17178837`, `17178852`, `17448962`, `17449005`, `17449021`
  - Garlaige Citadel [S] only
    - **Yagudo Templar** - MobIDs `17448971`, `17449000`, `17449022`
  - Sauromugue Champaign [S] only
    - **Yagudo Inquisitor** - MobIDs `17178833`, `17178844`, `17178848`
- Re-organized, where possible, the drop lists the relevant mobs were a part of, either by grouping the relevent mobs together in a droplist or by grouping mobs NOT relevant to this item drop into different drop lists (but had the same drop items).
  - Audited all the drop lists (and converted to the usage of the drop percentage variables) that the mobs relevant to this item were included in **as well as** any non-relevant drop lists that were touched in this audit by the previously mentioned movements of the relevant mobs out of them.
- Added 3 new droplists where no suitable re-organization of drop lists was possible.
- Updated drop list IDs in *mob_groups.sql* of relevant/non-relevant mobs to match movements made in *mob_droplist.sql*.
- Added ROAST_CARP and ROAST_PIPIRA despoiled items to items.lua global file (items were discovered missing from the global file during the testing phase of the above changes).
- Typo correction in the **comment** of Wild Cudgel item (DropID 1338) in *mob_droplist.sql* (I randomly passed by it during my work on this PR and discovered the typo). 
  - No DropID data changes, just a correction of the comment.

## Steps to test these changes

- Prior to pulling down this PR, unmercilessly slaughter the above mobs that should drop the 108-Knot Quipu item and kill them as many times as you want, they will _**knot**_ ever give you the item, even if you kill them more or less than **108** times....just **qui**t whenever you are satisfied they aren't gonna drop it, **p**ick **u**p your gear, head here, and pull down this PR.....

- After pulling down this PR, give these above indicated mobs one more chance and kill any of them for the 108-Knot Quipu item (disclaimer that it MAY take more than ONE chance for the mobs to drop said item, depending on your Treasure Hunter level and what side of the bed RNGesus woke up on) (usage of the ``!respawnmob`` command is suggested).

I can provide audit criteria for the drop rates used if needed, not going to list all the criteria in this part of the ticket.

EDIT (03/11/2023) - Added MobID goodness for all of the relevant mobs that drop the 108-Knot Quipu item.

### CODE REVIEW

**Review by Xaver-DaRed — APPROVED** [review]
LGTM

**Comment by TeoTwawki** [comment]
Since I saw a lot of bottled pixie removal, Il share which Yags should all drop bottled pixie as there may be overlap wioth changed lists:

| mob | zone | zID
| ------------- | ------------- |------------- |
| Yagudo Zealot | Garlaige Citadel [S] | 164 |
| Yagudo Zealot | Sauromugue Champaign [S] | 98 |
| Yagudo Theologist | Fort Karugo-Narugo [S] | 96 |
| Yagudo Sentinel | Castle Zvahl Baileys [S] | 138 |
| Yagudo Sentinel | Meriphataud Mountains [S] | 97 |
| Yagudo Sentinel | Castle Oztroja [S] | 99 |
| Yagudo Scribe | West Sarutabaruta [S] | 95 |
| Yagudo Priest | Fort Karugo-Narugo [S] | 96 |
| Yagudo High Priest | Castle Zvahl Baileys [S] | 138 |
| Yagudo High Priest | Meriphataud Mountains [S] | 97 |
| Yagudo High Priest | Castle Oztroja [S] | 99 |
| Yagudo Condottiere | West Sarutabaruta [S] | 95 |

**Comment by EpicTaru** [comment]
In the scope of this PR, of all of the above you mentioned, @TeoTwawki, the Yagudo Zealots were directly audited (as they are some of the relevant mobs that drop the 108-knot Quipu item).  The Yagudo Sentinels in Meri Mountains [S] and and Castle O [S] were also indirectly audited as their drop list was touched to move other relevant mobs out of it.  Within the scope of this PR, I did not touch the drop list for the Yagudo Sentinel in Castle Z B [S] (as I didn't have to move any of the relevant mobs out of that drop list) or any of the other Yagudo mobs you listed below the 3 Yagudo Sentinels.

For all of the mobs that I mentioned were audited (either directly or indirectly), their drop rate of the Bottled Pixie was adjusted/converted to the variable usage. 

Part of my audit specifically regarding the adjustment/removal of the Bottled Pixie item also involved checking of FFXIclopedia/BG-wiki of all of the relevant/non-relevant mobs.  None of them, on neither FFXIclopedia or BG-wiki, IF they listed the Bottled Pixie item, were also shown on FFXIDB as being a mob that dropped that item.  Any of them that specifically showed it as a drop on FFXIclopedia either had a 0/xx drop rate with the additional comment that the drop rate may not be accurate due to the low total number of attempts; that or their drop rate on FFXIclopedia was already lower than the TH0 rate that showed for them on FFXIDB.

@TeoTwawki, do you wish for me to do a full audit of ALL the mobs that have drop rates of the Bottled Pixie item and push said audit changes onto this PR?  There are FAR more mobs  (45 in total, 32 of which are outside of the scope of this PR) currently outside of the scope of this PR that drop that item (according to FFXIDB).

**Comment by TeoTwawki** [comment]
@EpicTaru I was just tossing info that may or may not be relevant for stuff you may or may not want to do, either in this pr or in future ones. Any lists not touched by this pr already can wait but I thought the list was handy to have.

**Comment by TeoTwawki** [comment]
@EpicTaru worth noting:
> FFXIclopedia either had a 0/xx drop rate

I used ffxi db, which has better reliability but imperfect; specifically I used the _[item page](http://ffxidb.com/items/2525)_ from them which may not fully match the mob pages it links to, but made sure they were all non-zero for recorded drops.

**Comment by TeoTwawki** [comment]
image

**Review by TeoTwawki — APPROVED** [review]

**Pull request merged**
