### PR TITLE
[Shops] Audited Royal Armoury

### PR DESCRIPTION
**Pull request by Skerxan**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Audited the 2 shop NPCs in Northern Sandy. Arlenne & Tavourine of Royal Armoury.

- Fixed prices
- Fixed nation conquest requirements
- Fixed order of items
- Added missing weapons (Bronze Spear, Brass Spear, Spear)

I compared BGwiki to JPwiki and noticed that JPwiki has the updated list of the July 2011 patch. (They even list the changes on their shop page.) 
Also the JP list has a note that their prices are the base prices untouched by fame etc. (The numbers also make alot more sense.)
I also ordered the items according to the JPwiki because they usually use the retail list instead of the LSB ordering by conquest/ID.) Not gonna touch the formatting otherwise.

Sources:
- https://www.bg-wiki.com/ffxi/Tavourine
- https://wiki-ffo-jp.translate.goog/html/9245.html?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en-US
- https://www.bg-wiki.com/ffxi/Version_Update_(07/11/2011)

## Steps to test these changes

Check out the shops.

### CODE REVIEW

**Comment by Xaver-DaRed** [comment]
No tabs, Skerxan.

**Comment by Xaver-DaRed** [comment]
Arlienne stock and prices at fame lvl 5, non citizen:
imagen
imagen

Tavourine stock and prices at fame lvl 5, non citizen:
imagen
imagen

As you can see, my buying prices, even at lvl 5 fame are higher. Wikis, am I right?

**Comment by Skerxan** [comment]
> No tabs, Skerxan.

I didn't use tabs? Only spacebar in Notepad++.

**Comment by TeoTwawki** [comment]
> > No tabs, Skerxan.
> 
> I didn't use tabs? Only spacebar in Notepad++.

enable "show symbol" -> "space and tab" because you definitely have tabs

**Comment by Skerxan** [comment]
> As you can see, my buying prices, even at lvl 5 fame are higher. Wikis, am I right?

Sigh, I just wanted to add the items and thought i might as well do the whole thing.

**Comment by Skerxan** [comment]
- Fixed the tabs.
- Decided to create a new retail character for 0 fame because I wanna know now.
- Updated prices.
- Cry because Sandy is 3rd in conquest but confirms that the available items are correct.
- The prices for 1st & 2nd place items need to be updated when Sandy is 1st but should still be closer to their real value than before the commit.
- Attached retail screenshots.

conquest
tavourine
arlenne

**Comment by Skerxan** [comment]
I couuuuld delete and recreate a new character on every server until i find one with Sandy 1st... Am I so stupid and do that and watch that beginning CS every time? Let's find out.

**Comment by TeoTwawki** [comment]
fun fact: fame can be negative, and fame zero at npcs that utilize it may not come up the same as npcs that use no fame\* (matters for baseSell but not shops sell price)

That's why we've been directing people to that NPC in Jeuno in that comment in the file. Poke me on discord, I can get on retail and help you.

<sub><sup>\*</sup> Citation/verification needed</sub>

**Comment by Skerxan** [comment]
> I couuuuld delete and recreate a new character on every server until i find one with Sandy 1st... Am I so stupid and do that and watch that beginning CS every time? Let's find out.

Aight, I did this today for all shops in Sandy (except guilds & region vendors). For conquest place 3, 2 & 1. Follow-up PR's will follow after this one is accepted.

Here are the screenshots:

Tavourine Sandy place 2:
tavourine_2nd

Tavourine Sandy place 1:
tavourine_1st

Arlenne Sandy place 2:
arlenne_2nd

Arlenne Sandy place 1:
arlenne_1st

**Comment by Skerxan** [comment]
> fun fact: fame can be negative, and fame zero at npcs that utilize it may not come up the same as npcs that use no fame* (matters for baseSell but not shops sell price)
> 
> That's why we've been directing people to that NPC in Jeuno in that comment in the file. Poke me on discord, I can get on retail and help you.
> 
> * Citation/verification needed

Negative fame is indeed not something I have heard before. 
Item sell prices are definitely another beast I want to tackle after the shop audits. Will let you know when we can do it!

**Comment by Skerxan** [comment]
Ready for review.

**Comment by Xaver-DaRed** [comment]
EDIT: You are correct. No need to define 2 shop inventories.

Other than that, this looks good. Props for going the extra mile, man

**Comment by Skerxan** [comment]
Thanks man.
Isn't that part defined in shop.lua?

```
   -- send nation shop dialog to player
    -- stock cuts off after 16 items. if you add more, extras will not display
    -- stock is of form { itemId1, price1, place1, itemId2, price2, place2, ... }
    --     where place is what place the nation must be in for item to be stocked
    -- nation is a xi.nation ID from scripts/globals/zone.lua
    nation = function(player, stock, nation)
        local rank = GetNationRank(nation)
        local newStock = {}
        for i = 1, #stock, 3 do
            if
                (stock[i + 2] == 1 and player:getNation() == nation and rank == 1) or
                (stock[i + 2] == 2 and rank <= 2) or
                (stock[i + 2] == 3)
            then
                table.insert(newStock, stock[i])
                table.insert(newStock, stock[i + 1])
            end
        end

        xi.shop.general(player, newStock, nation)
    end,
```

Pretty sure non-Sandorians can't buy Place 1 items from Sandy, etc? Or has this been debunked?

**Comment by TeoTwawki** [comment]
there should still be a parameter most shops don't use that handled nation ranking stuff. I don't recall it having been retired. I had to get creative with a few shops in tavnazia because I was too lazy to expand that into higher values to handle non-nation rankage tho so i did conditionals there.

ed: I see you found that

**Comment by Xaver-DaRed** [comment]
Edited my previous comment. The shop already handles it.

**Review by Xaver-DaRed — APPROVED** [review]

**Review by TeoTwawki — APPROVED** [review]

**Pull request merged**
