### PR TITLE
add instance commands to check and adjust progress and stage

### PR DESCRIPTION
**Pull request by KnowOne134**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by zach2good** [comment]
I wonder could this be named better? We have `!instance` which sets your instance, or kicks you out of one. SetInstanceProgress/Stage maybe?

**Comment by KnowOne134** [comment]
On eden it's separated as 2 commands
!setProgess
!setStage

**Comment by KnowOne134** [comment]
can make them 2 different commands if you want, was just trying to simplify/ merge
!setInstanceProgress, !setInstanceStage? or !setStage, !setProgress good enough?

**Comment by zach2good** [comment]
I wonder if there's other post-75 content that has stages or progress that
we would want to overload or differentiate these commands for

Maybe setStage and srtProgress are fine

**Comment by KnowOne134** [comment]
i use it for assault and in salvage

**Review by zach2good — APPROVED** [review]
🚀

**Review by claywar — APPROVED** [review]

**Pull request merged**
