### PR TITLE
[Fix] item_basic table manual import

### PR DESCRIPTION
**Pull request by Xaver-DaRed**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

Fixes this... thing, the red dot, that makes Heidi cry when trying to manualy import this table.
imagen

### CODE REVIEW

**Comment by zach2good** [comment]
Might be a nice idea to add a check for this character (that keeps sneaking in) to the `sql.sh` CI check

**Comment by TeoTwawki** [comment]
Byte Order Mark. Which should not be a problem for Heidi and made me think Heidi has a bug. Just looked and yeah, known issue that the dev is going to ignore (its been 11 years).

**Comment by TeoTwawki** [comment]
@Xaver-DaRed add this to our `.editorconfig` right above `[*.lua]` :
```yaml
[*.sql]
charset = utf-8
```

That -should- make git itself strip the BOM off sql files anytime they are touched by git, and by any editor reading the config from our repo (vs, np++)

**Comment by TeoTwawki** [comment]
@Xaver-DaRed my bad I should not have had curly braces in that, sorry!

**Review by TeoTwawki — APPROVED** [review]

**Pull request merged**
