### PR TITLE
Replace mysql python module with mariadb

### PR DESCRIPTION
**Pull request by cocosolos**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Replaces call to mysql connector with mariadb.

## Steps to test these changes

Run the new migration without mysql module installed.

### CODE REVIEW

**Comment by WinterSolstice8** [comment]
I understand that this seems to be a good idea for us given we use MariaDB, but why did this PR come about? Was there some issue you were having?

**Comment by cocosolos** [comment]
> I understand that this seems to be a good idea for us given we use MariaDB, but why did this PR come about? Was there some issue you were having?

Someone in Discord was having an issue installing the server since MySql connector is no longer a requirement and dbtool fails to run when this migration tries to import it.

**Review by TeoTwawki — APPROVED** [review]

**Review by WinterSolstice8 — APPROVED** [review]
LGTM

**Review by zach2good — APPROVED** [review]

**Review by Xaver-DaRed — APPROVED** [review]
Ooops

**Pull request merged**
