### PR TITLE
Create Alrauverat npc for abyssea - attohwa

### PR DESCRIPTION
**Pull request by Daywhite83**
Create the lua for Alrauverat, whos purpose in Abyssea - Attohwa is to warp players to the lower part near conflux No. 8

**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
Adds function to Alrauverat in abyssea - attohwa. Her purpose is to warp players down from conflux 8

## Steps to test these changes
Go to the npc in abyssea - attohwa, use her to go the lower level

### CODE REVIEW

**Comment by zach2good** [comment]
Unfortunately, GitHub is super keen on trying to make links to issues and PRs wherever it can. Can you change `#8` to `no.8` or similar to get rid of that link?

EDIT: In the commit message *

**Comment by TeoTwawki** [comment]
another way around github autolinkage is to enclose things in 
```
`backticks`
```

**Comment by Daywhite83** [comment]
i cant seem to be able to edit that message

**Comment by WinterSolstice8** [comment]
> i cant seem to be able to edit that message

`git commit --amend` in the commandline will let you edit that commit, or use a GUI like gitkraken and amend the commit to help you out

**Review by zach2good — APPROVED** [review]

**Pull request merged**
