### PR TITLE
[core] Add !build command

### PR DESCRIPTION
**Pull request by zach2good**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Adds the !build command, available to all players.

https://github.com/LandSandBoat/server/issues/1928

## Steps to test these changes

`!build`

image
^Taken with long-hash, we use short-hash now

image

### CODE REVIEW

**Review by WinterSolstice8 — APPROVED** [review]
Cool cmake sorcery 👍

**Comment by zach2good** [comment]
Will wait on the others to see this before merging 👍

**Review by claywar — APPROVED** [review]

**Review by Xaver-DaRed — APPROVED** [review]

**Review by TeoTwawki — APPROVED** [review]
works for me, probably cleaner than what I'd have come up with

**Comment by TeoTwawki** [comment]
going to steal `!ver` for displaying client related versioning then

**Comment by zach2good** [comment]
It's not very hard to capture logging in client's version from the login server and later store it on PChar, if you wanted to print: Server expected client version | Current client version = Match/unmatched

**Pull request merged**
