### PR TITLE
Update incorrect AH flags on some items

### PR DESCRIPTION
**Pull request by bope12**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

ark angel statue's, bonbori, festival dolls and hachiryu_sune-ate should not be listed in the ah list
Stacks of COR cards should be AH-able

### CODE REVIEW

**Review by zach2good — APPROVED** [review]
https://ffxiclopedia.fandom.com/wiki/Hachiryu_Sune-Ate

Seems legit 👍

**Review by claywar — APPROVED** [review]

**Comment by TeoTwawki** [comment]
> https://ffxiclopedia.fandom.com/wiki/Hachiryu_Sune-Ate
> 
> Seems legit +1

`Goblin Box, Not auctionable, Equippable, Not vendorable, Not sendable, Rare`

bg actually gives full flags in their items templates, as extracted from client - handy

**Review by TeoTwawki — APPROVED** [review]

**Comment by bope12** [comment]
> > https://ffxiclopedia.fandom.com/wiki/Hachiryu_Sune-Ate
> > 
> > Seems legit +1

> `Goblin Box, Not auctionable, Equippable, Not vendorable, Not sendable, Rare`
> bg actually gives full flags in their items templates, as extracted from client - handy

MYSTERY_BOX NOAUCTION CANEQUIP NOSALE NODELIVERY RARE
Yup! our flags were set right it just would show when people viewed on the AH but they could not list it

(Apologies for the accidental edit! I was trying to quote reply and somehow hit edit by mistake! - Teo)

**Comment by TeoTwawki** [comment]
> Yup! our flags were set right it just would show when people viewed on the AH but they could not list it

aye :+1:  

Just gonna leave this here for random future readers as an example of how the flags even work:
```c++
// 47172 decimal (db value) = 0xB844 in hex, which our flags are defined as

// And these are the flags in that value:
ITEM_FLAG_MYSTERY_BOX  = 0x0004
ITEM_FLAG_NOAUCTION    = 0x0040,
ITEM_FLAG_CANEQUIP     = 0x0800,
ITEM_FLAG_NOSALE       = 0x1000,
ITEM_FLAG_NODELIVERY   = 0x2000,
ITEM_FLAG_RARE         = 0x8000
// Add 'em up and you get 0xB844
```
Edit : 
https://imgs.xkcd.com/comics/dyslexics.png

**Pull request merged**
