### PR TITLE
Seekers of Adoulin Missions: Chapter 1 and Chapter 2

### PR DESCRIPTION
**Pull request by zach2good**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by zach2good** [comment]
Just done a full playthrough of this (using `!pos`, obviously, since colonisation skills don't work yet), everything seems OK apart from the instance fight, which I'll work on this weekend... maybe...

**Comment by zach2good** [comment]
```
[09/14/21 22:03:41:847][map][warning][warning] CMagicState::ValidCast Mob (17838147) tried to cast magic with no mp! (CMagicState::HasCost:239)
[09/14/21 22:03:44:647][map][warning][warning] CMagicState::ValidCast Mob (17838149) tried to cast magic with no mp! (CMagicState::HasCost:239)
[09/14/21 22:04:05:866][map][warning][warning] CMagicState::ValidCast Mob (17838149) tried to cast magic with no mp! (CMagicState::HasCost:239)
[09/14/21 22:04:16:244][map][warning][warning] CMagicState::ValidCast Mob (17838147) tried to cast magic with no mp! (CMagicState::HasCost:239)
[09/14/21 22:04:28:646][map][warning][warning] CMagicState::ValidCast Mob (17838149) tried to cast magic with no mp! (CMagicState::HasCost:239)
[09/14/21 22:04:36:256][map][warning][warning] CMagicState::ValidCast Mob (17838147) tried to cast magic with no mp! (CMagicState::HasCost:239)
[09/14/21 22:04:53:048][map][warning][warning] CMagicState::ValidCast Mob (17838149) tried to cast magic with no mp! (CMagicState::HasCost:239)
[09/14/21 22:05:05:862][map][warning][warning] CMagicState::ValidCast Mob (17838147) tried to cast magic with no mp! (CMagicState::HasCost:239)
[09/14/21 22:05:22:254][map][warning][warning] CMagicState::ValidCast Mob (17838149) tried to cast magic with no mp! (CMagicState::HasCost:239)
[09/14/21 22:05:36:249][map][warning][warning] CMagicState::ValidCast Mob (17838147) tried to cast magic with no mp! (CMagicState::HasCost:239)
[09/14/21 22:05:51:847][map][warning][warning] CMagicState::ValidCast Mob (17838149) tried to cast magic with no mp! (CMagicState::HasCost:239)
[09/14/21 22:06:06:251][map][warning][warning] CMagicState::ValidCast Mob (17838147) tried to cast magic with no mp! (CMagicState::HasCost:239)
[09/14/21 22:06:12:656][map][warning][warning] CMagicState::ValidCast Mob (17838149) tried to cast magic with no mp! (CMagicState::HasCost:239)
```
I KNEW IT!

**Comment by zach2good** [comment]
TODO (before ready for review/playthroughs/merge):
- Fill in skill chain information for new mob moves
- Fill in Arciela's fight logic / HP / Skills / Spells
- Fill in Win / Fail logic for instance fight
- Check entry / exit logic for instance fight
- Handle any (important) TODOs I've left behind

**Comment by zach2good** [comment]
TODO:
- Add complementary module to override (and skip) imprimaturs-spent checks (same as my idea for skipping nation quests in WOTG)

**Comment by claywar** [comment]
This might need to be rebased considering the commits shown.

**Comment by claywar** [comment]
CI isn't happy due to the monstertpmoves->mobskills global changes.  Everything's tabled up now

**Comment by zach2good** [comment]
Rebased, should be good to go now 👍

**Review by claywar — APPROVED** [review]

**Pull request merged**
