### PR TITLE
Correct spelling for Royal Saute in item_basic.sql to make it usable again as noted in issue #836

### PR DESCRIPTION
**Pull request by RAIST5150**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by RAIST5150** [comment]
Had a time correcting this one line in this file... too big to do it in the web interface, and editors I tried using locally in Windows kept stripping the special characters for gender.  The one that finally did it without stripping special characters, of all things... was freaking NOTEPAD!!!.

**Comment by TeoTwawki** [comment]
hit me up on discord tomorrow after 5pm eastern. going to show you how to rebase and do timeline surgery on this, as we cannot have this in history showing file deleted and re-added and that's a skill you will want to have. It's easy once you've done it a few times. Also looks like you back pulled because your remote and local copies weren't in sync. I can show you how to avoid that in the future.

**Comment by RAIST5150** [comment]
Yeah... I didn't check the box to do a PR with the first one, which defaulted to adding it directly to my base... which meant I didn't get to see all the changes and go back to fix that.  Once that broke, couldn't figure out adirect way to get it back to the original version (no roll back or anything like that).

Probly should have just dumped the whole fork and started all over again I guess.

TBH... going forward, I only plan to touch easier stuff.  Just wanted to clear this issue up as it had been sitting there quite a while.

I also didn't realize it would show the full paper trail of what went in on my repo.  If you would rather though, can scrap this PR and all to do it more proper to keep the history cleaner.

**Review by claywar — APPROVED** [review]

**Comment by TeoTwawki** [comment]
I'll teach you how to roll back. its pretty easy. The rebase feature let you pick a new point in time to apply changes to as well, kinda like having a time machine and bringing your future toolbox with you to fix the past.

**Review by TeoTwawki — CHANGES_REQUESTED** [review]
there shall be rebase.

**Comment by claywar** [comment]
"And Saint Attila raised the code up on high, saying, 'O Lord, bless this thy code, that with it thou mayst blow thine enemies to tiny bits, in thy mercy.' And the Lord did grin. And the people did feast upon the lambs, and sloths, and carp, and anchovies, and orangutans, and breakfast cereals, and fruit bats, and large chulapas. And the Lord spake, saying, 'First shalt thou take out the Holy PR. Then shalt thou count to three, no more, no less. Three shall be the number thou shalt count, and the number of the counting shall be three. Four shalt thou not count, neither count thou two, excepting that thou then proceed to three. Five is right out. Once the number three, being the third number, be reached, then lobbest thou thy Holy Code of Antioch towards thy foe, who, being naughty in My sight, shall rebase it.'

**Comment by TeoTwawki** [comment]
Hey, that Vorpal Bunny had it coming.

**Review by TeoTwawki — APPROVED** [review]
all gooder nao :+1

**Pull request merged**
