### PR TITLE
[core] MOVE MESSAGE SERVER TO XI_WORLD PROCESS

### PR DESCRIPTION
**Pull request by zach2good**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

- Move message server to world server
- Add stubs for future systems

### CODE REVIEW

**Comment by zach2good** [comment]
What other "global" systems are there that would benefit from being rewritten and moved onto world server? (logic that happens independent of a zone)

**Comment by Xaver-DaRed** [comment]
If I had to guess...
- Transports (Airships, boats, etc)
- Guild patterns
- Conquest, to a certain point. Beisigued, campaign would go here aswell. But we dont have them
- Weather

**Comment by zach2good** [comment]
Party and Alliance system

**Comment by zach2good** [comment]
Ready for review

Of interest:
- Changes and notes in login_auth

**Review by claywar — APPROVED** [review]
Seems reasonable to me.  Can't remember which, but either lgtm used to, or CodeQL may complain about lack of header guards (even though they're not needed)

**Pull request merged**
