### PR TITLE
Wyvern skill list updates

### LINKED ISSUE #792: Skoffins don't use their family TP moves
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: everything

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Skoffins (Wyverns) currently don't use any TP moves.

https://ffxiclopedia.fandom.com/wiki/Skoffin
https://ffxiclopedia.fandom.com/wiki/Talk:Skoffin
https://ffxiclopedia.fandom.com/wiki/Category:Wyverns

### PR DESCRIPTION
**Pull request by TeoTwawki**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
Closes #792

Skoffins had an invalid skill list ID in their mob pool. Simorg was missing several of its breaths (he's an NM that gets all the different breaths, where usually a Wyvern only gets one or two of them). Hurricane breath is commented out because it basically doesn't exist yet. I don't think that NM is even spawnable yet, didn't check. Other mobs already have these skills tho, so they should work fine if he is.

Also added some commenting to the SQL rows including rows I didn't add/change.

I noticed Guivres skill list is identical to a standard Wyvern meaning it is a duplicate. And Bune also uses the Standard Wyvern skill list directly. Out of scope for this PR to mess with that, but if someone else wants to they can repurpose the IDs for NMs that aren't 100% duplicate skill lists in the future.

## Steps to test these changes
Go feed a Skoffin some TP, watch it go.

### CODE REVIEW

**Review by WinterSolstice8 — APPROVED** [review]

**Comment by LacunaXI** [comment]
Additionally Watch Wyvern in Mamook have a skill list that is blank. They should just have standard wyvern TP moves.

**Comment by TeoTwawki** [comment]
> Additionally Watch Wyvern in Mamook have a skill list that is blank. They should just have standard wyvern TP moves.

tacked them on as well. did a quick search and every wyvern with no skills (because ID 268 has nothing) will now use list 266. it might be wrong for some of them, but that's better than loot pinata's at least now they can fight back.

**Comment by LacunaXI** [comment]
> > Additionally Watch Wyvern in Mamook have a skill list that is blank. They should just have standard wyvern TP moves.
> 
> tacked them on as well. did a quick search and every wyvern with no skills (because ID 268 has nothing) will now use list 266. it might be wrong for some of them, but that's better than loot pinata's at least now they can fight back.

Excellent. Thank you. I believed it better to say than have a separate PR.

**Comment by TeoTwawki** [comment]
> Excellent. Thank you. I believed it better to say than have a separate PR.

It was definitely a good time to catch them, I was already here and nobody opened issues for the others. The skoffin issue was ancient and I was trying to clear some old back burner things-teo-said-he-was-gonna-do off my plat this weekend 👍

**Pull request merged**
