### PR TITLE
Add mod NULL_BREATH_DAMAGE

### LINKED ISSUE #2338: 🔨 null damage modifiers and breath damage - possibly new modifier needed, or existing ones adjusted
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [X] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Describe the feature

Need mod to occasionally nullify breath damage NULL_BREATH_DAMAGE

by percent like NULL_PHYSICAL_DAMAGE

### PR DESCRIPTION
**Pull request by illzbee**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Adds mod NULL_BREATH_DAMAGE to occasionally nullify breath damage

## Steps to test these changes

Take breath damage with porog cask+1 mods equiped

### CODE REVIEW

**Comment by TeoTwawki** [comment]
#2338 had unanswered questions, which is why I had not simply done this. Retail accurate behavior needs know, and I've not seen a single item that says it does this specifically without also nulling another damage type. For all I know, we need a single mod that nulls any and all types of damage -or- the existing element ones should also be covering breath damages of their element. I said as much both hen I asked you to open the issue, and again when you didn't include that info in the issue and had to post it a 2nd time. Here it is a 3rd time:

> things that literally cannot be done we're much more forgiving on than things people simply didn't do. use physical and magic nulls, and raise an issue calling out this item by name so it isn't forgotten. I had actually just posted to Xaver-DaRed back on the discussion about elemental nulls, because I think unlike the generic magic one I am not sure they should care about the source of an element. But we should probably just one mod that covers "all types of damage". It's also possible breath bypasses this mechanic.

And no, not having this mod does not mean your pr can't be merged.

**Comment by Xaver-DaRed** [comment]
I would also request that this new modifier is added to this documentation file
https://github.com/LandSandBoat/server/blob/base/documentation/mods_by_id.txt

**Comment by WinterSolstice8** [comment]
there's no evidence (in english text, mind you, occasionally the japanese text reveals more than what we got) that there is a null _breath_ damage modifier on any gear. What is this attempting to solve? what item, ability, etc wants this?

**Comment by illzbee** [comment]
> 

https://github.com/LandSandBoat/server/pull/2307#issue-1306977798

For the Poroggo Cass. +1
 “ Occasionally ignores damage taken “

**Comment by TeoTwawki** [comment]
> > 
> 
> [#2307 (comment)](https://github.com/LandSandBoat/server/pull/2307#issue-1306977798)
> 
> For the Poroggo Cass. +1 “ Occasionally ignores damage taken “

That doesn't actually answer anything. Nor does it indicate a need for null _breath_ damage. its more indicative of a need for a null _everything_ modifier if anything.

**Comment by illzbee** [comment]
> 

Yes I get this, this does is adds breath null into battle utilities and makes it usable via mods. Sorry if this should not close the issue I linked.

**Comment by TeoTwawki** [comment]
to be as simple as I can be:

will Poroggo Cass. +1 nullify _any_ damage type form _any_ source?

will a different item that nulls just fire, also nullify fire breath or eruca's incinerate?

**Comment by TeoTwawki** [comment]
the most likely scenario is not a need for breath specific modifier, its an "all damage" one, and maybe tweaks to the existing element ones

**Comment by TeoTwawki** [comment]
but none of it matters till someone takes time to go test it on the retail game

**Comment by illzbee** [comment]
> #2338 had unanswered questions, which is why I had not simply done this. Retail accurate behavior needs know, and I've not seen a single item that says it does this specifically without also nulling another damage type. For all I know, we need a single mod that nulls any and all types of damage -or- the existing element ones should also be covering breath damages of their element. I said as much both hen I asked you to open the issue, and again when you didn't include that info in the issue and had to post it a 2nd time. Here it is a 3rd time:
> 
> > things that literally cannot be done we're much more forgiving on than things people simply didn't do. use physical and magic nulls, and raise an issue calling out this item by name so it isn't forgotten. I had actually just posted to Xaver-DaRed back on the discussion about elemental nulls, because I think unlike the generic magic one I am not sure they should care about the source of an element. But we should probably just one mod that covers "all types of damage". It's also possible breath bypasses this mechanic.
> 
> And no, not having this mod does not mean your pr can't be merged.

-will a different item that nulls just fire, also nullify fire breath or eruca's incinerate?-
I did not test this on crawlers only on dragons but "Elemental null" on retail does not null an elemental breath.

Ok and heres why I come in and say lets add this null breath mod so I do and open a pr.
A. Thought I was helping
B. adding NULL_BREATH only adds a few lines of code
C. at this point its only 1 item needing it
D. adding NULL_ALL_DMG would be adding a line of code to more damage typed in battle utilities then just one on breath for just 1 item to use...

**Comment by illzbee** [comment]
> > > 
> > 
> > 
> > [#2307 (comment)](https://github.com/LandSandBoat/server/pull/2307#issue-1306977798)
> > For the Poroggo Cass. +1 “ Occasionally ignores damage taken “
> 
> That doesn't actually answer anything. Nor does it indicate a need for null _breath_ damage. its more indicative of a need for a null _everything_ modifier if anything.

That was in response to 

[WinterSolstice8](https://github.com/WinterSolstice8) commented [1 hour ago](https://github.com/LandSandBoat/server/pull/2440#issuecomment-1201769506) • 
there's no evidence (in english text, mind you, occasionally the japanese text reveals more than what we got) that there is a null breath damage modifier on any gear. What is this attempting to solve? what item, ability, etc wants this?

Dont see how thats not answering that question but meh.

**Comment by illzbee** [comment]
> I would also request that this new modifier is added to this documentation file https://github.com/LandSandBoat/server/blob/base/documentation/mods_by_id.txt

Added in thanks.

**Comment by WinterSolstice8** [comment]
It sounds like all we need to do is test if "ignores damage" means what it says it means. If you have this on retail you could test it in brenner with Spirits Within (typeless breath damage) and against other breaths like Incinerate from Erucas, or really just any source. We can't just trust the text to do what it says it does, SE's fooled the playerbase quite a bit with bad descriptions like this.

fwiw, there are damage sources that aren't magic, physical or breath. The description implies "all" sources, but it's not easy to get hit by the sources that aren't those 3 -- these are things such as Unfaltering Bravado from Kyou which doesn't appear to be able to be mitigated by MDT/BDT/PDT, but _might_ work with this. The problem isn't so much adding this mod in the PR as it is understanding which one we actually need from testing, if any. It may not even null breath damage.

**Comment by TeoTwawki** [comment]
> Dont see how thats not answering that question but meh.

It articulated no reasoning at all and simply linked to an item that may not even be needed for. **That's how.**

> D. adding NULL_ALL_DMG would be adding a line of code to more damage typed in battle utilities then just one on breath for just 1 item to use...

Except we may need to cover other edge cases that just adding breath with the other 2 might not. 

Edit: winter said it better.

**Comment by zach2good** [comment]
This is getting handled in another PR, closing

**Pull request closed without merging**
