### PR TITLE
Trust: Lion II

### PR DESCRIPTION
**Pull request by CatsEyeXI**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
Implements Trust: Lion II.
This variety of Lion II casts Utsusemi (already implemented)
These moves are not AoE like Lion I's.
She can also hold up to 3000 TP waiting to close skillchains, and has some banter when using Powder Keg.
This PR hinges on #4912 for implementation of mobskill scripts.

https://www.bg-wiki.com/ffxi/Cipher:_Lion_II

## Steps to test these changes
!zone Dragon's Aery
!trustengage her and watch Lion II cycle through her moves.

### CODE REVIEW

**Comment by zach2good** [comment]
If you don't have access to this on retail you can use the trust message debug utils to figure out the voice notes:
https://github.com/LandSandBoat/server/blob/base/scripts/globals/trust.lua#L445

**Comment by zach2good** [comment]
Lion II voice lines: 
image

I'm not sure if these at the bottom of the page are hers, or the next Trust:
image

**Comment by zach2good** [comment]
> I'm not sure if these at the bottom of the page are hers, or the next Trust: image

This second group is Prishe II's lines, no need to be concerned with

**Comment by zach2good** [comment]
For Lion vs Lion II, the only differences the wikis mention is casting Utsu, and Lion II's WSs being different. It's safe to assume that they're both THF/NIN because of the dual-wield look, but maybe Lion II's base damage will have to come down. Needs testing and comparison, especially if you're submitting them both at the same time

**Comment by CatsEyeXI** [comment]
> For Lion vs Lion II, the only differences the wikis mention is casting Utsu, and Lion II's WSs being different. It's safe to assume that they're both THF/NIN because of the dual-wield look, but maybe Lion II's base damage will have to come down. Needs testing and comparison, especially if you're submitting them both at the same time

her cipher is in login points right now, i just bought it, ill do some retail testing and report back.

**Comment by CatsEyeXI** [comment]
https://www.youtube.com/watch?v=35dPykMtUcg
Confirmed that Lion II appears to do less weaponskill damage

**Comment by CatsEyeXI** [comment]
I believe the answer here, is not to reduce Lion II's damage (which is already pretty low), but to raise Lion's but just a bit. Here are some comparisons.

Lion I, Pirate Pummel: 
image

Lion I, Walk the Plank
image

Lion I, Powder Keg
image

Lion I, Grapeshot
image

--

Lion II, Pirate Pummel
image

Lion II, Walk the Plank
image

Lion II, Powder keg
image

Lion II, Grapeshot
image

**Comment by zach2good** [comment]
What are their general melee damages like? Hopefully, it is as simple as buffing I

**Comment by CatsEyeXI** [comment]
Lion:
image

Lion II:
image

**Review by Xaver-DaRed — APPROVED** [review]

**Review by zach2good — APPROVED** [review]

**Comment by zach2good** [comment]
This is fine, but github is complaining about there being conflicts that need resolving - without listing what they are. Can you rebase and squash down to one commit please?

**Comment by CatsEyeXI** [comment]
i will certainly try... may the lord have mercy on what is about to happen to this PR

**Comment by CatsEyeXI** [comment]
yup, i knew that would happen.

**Comment by TeoTwawki** [comment]
it appears the lord was fresh out of mercy

**Comment by TeoTwawki** [comment]
> [CatsEyeXI](https://github.com/CatsEyeXI) deleted the trust_lion_ii branch [16 minutes ago](https://github.com/LandSandBoat/server/pull/4917#event-11853015412)

learn the difference between your local copy and the remote copy. you never need to delete the remote to fix a thing. ever.

**Pull request closed without merging**
