### PR TITLE
[SQL] Add missing 'Animated' Weapon drops in Dynamis-Xarcabard

### PR DESCRIPTION
**Pull request by CatsEyeXI**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
Adds missing fragment drops to animated weapons in Dynamis - Xarcabard

## Steps to test these changes
update tables, kill animated weapons, get fragment drops

### CODE REVIEW

**Comment by TeoTwawki** [comment]
looks like these are being handled by script, but I don't see where the item ID is being set.

https://github.com/LandSandBoat/server/blob/base/scripts/mixins/animated_weapon.lua

https://github.com/LandSandBoat/server/commit/cb9ddb3d9b71fca7af75c1784326f2b4fddfa78c#diff-a030517f00907fac7584ab24fde6d1887a8ac1a692263349b7c41efdcce6e121R17

https://github.com/LandSandBoat/server/commit/cb9ddb3d9b71fca7af75c1784326f2b4fddfa78c#diff-7c2d6518808398b612d2e8668cf354c22106a0d5719bbc370d9e18b20afb0cb8L1044

**Comment by TeoTwawki** [comment]
nvm, my blind ass sees it - passed to the mixin by the mob. so these are not missing.

**Comment by CatsEyeXI** [comment]
> looks like these are being handled by script, but I don't see where the item ID is being set.
> 
> https://github.com/LandSandBoat/server/blob/base/scripts/mixins/animated_weapon.lua
> 
> [cb9ddb3#diff-a030517f00907fac7584ab24fde6d1887a8ac1a692263349b7c41efdcce6e121R17](https://github.com/LandSandBoat/server/commit/cb9ddb3d9b71fca7af75c1784326f2b4fddfa78c#diff-a030517f00907fac7584ab24fde6d1887a8ac1a692263349b7c41efdcce6e121R17)
> 
> [cb9ddb3#diff-7c2d6518808398b612d2e8668cf354c22106a0d5719bbc370d9e18b20afb0cb8L1044](https://github.com/LandSandBoat/server/commit/cb9ddb3d9b71fca7af75c1784326f2b4fddfa78c#diff-7c2d6518808398b612d2e8668cf354c22106a0d5719bbc370d9e18b20afb0cb8L1044)

interesting, so if i understand correctly, once the weapon is engaged the loot should automatically be added to the loot list?

```lua
g_mixins.families.animated_weapon = function(weaponMob, options)
    weaponMob:addListener("ENGAGE", "ENGAGE_ANIMATED", function(mob, target)
        if mob:getAnimationSub() == 3 then
            mob:setLocalVar("shouldDropItem", 1)
        end
    end)
```

Edit: the reason for the PR was because we got a report they weren't dropping. So i'm trying to figure out the conditions under which it should drop...

**Comment by TeoTwawki** [comment]
> > looks like these are being handled by script, but I don't see where the item ID is being set.
> > https://github.com/LandSandBoat/server/blob/base/scripts/mixins/animated_weapon.lua
> > [cb9ddb3#diff-a030517f00907fac7584ab24fde6d1887a8ac1a692263349b7c41efdcce6e121R17](https://github.com/LandSandBoat/server/commit/cb9ddb3d9b71fca7af75c1784326f2b4fddfa78c#diff-a030517f00907fac7584ab24fde6d1887a8ac1a692263349b7c41efdcce6e121R17)
> > [cb9ddb3#diff-7c2d6518808398b612d2e8668cf354c22106a0d5719bbc370d9e18b20afb0cb8L1044](https://github.com/LandSandBoat/server/commit/cb9ddb3d9b71fca7af75c1784326f2b4fddfa78c#diff-7c2d6518808398b612d2e8668cf354c22106a0d5719bbc370d9e18b20afb0cb8L1044)
> 
> interesting, so if i understand correctly, once the weapon is engaged the loot should automatically be added to the loot list?
> 
> ```lua
> g_mixins.families.animated_weapon = function(weaponMob, options)
>     weaponMob:addListener("ENGAGE", "ENGAGE_ANIMATED", function(mob, target)
>         if mob:getAnimationSub() == 3 then
>             mob:setLocalVar("shouldDropItem", 1)
>         end
>     end)
> ```
> 
> Edit: the reason for the PR was because we got a report they weren't dropping. So i'm trying to figure out the conditions under which it should drop...

I just told someone else that messaged me about it that I am not sure myself, and the scripting that was converted from setting drop ID to just telling it "drop this 100%" might have been legacy code from old dyna. I dunno I would need to see when these change their animation state and why or if the do at all and what the default is when you engage them right now - for all I know the transitions don't exist anymore.

**Review by EpicTaru — APPROVED** [review]

**Comment by CatsEyeXI** [comment]
closing due to superseded by #3559

**Pull request closed without merging**
