### PR TITLE
Add drg mob Call Wyvern

### LINKED ISSUE #158: Common DRG mobs aren't summoning their pets
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

They don't summon their pets on spawn, while roaming, or while in combat.

This only seems to affect DRG mobs.  BST, SMN, and PUP mobs all have their pets following them around.

Examples:

16990386 Mamool_Ja_Stabler (BST) has its Mamool_Jas_Raptor
16990396 Mamool_Ja_Pikeman (DRG) does not have its Mamool_Jas_Wyvern

16912405 Ulaern (BST) has its Aerns_Xzomit
16912418 Ulaern (SMN) has its Aerns_Elemental
16912406 Ulaern (DRG) does not have its Aerns_Wynav

Pets are correctly entered in mob_pets.sql for these example mobs.

### PR DESCRIPTION
**Pull request by Snugglesffxi**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

Adds Call Wyvern to mob drgs. Fixes #158

### CODE REVIEW

**Comment by Snugglesffxi** [comment]
@wrenffxi add me on discord <3

**Comment by TeoTwawki** [comment]
there is a problem: this behavior is -not- universal to all drg mos. Quite a few of them only use Call Wyvern as their 2hr.

**Comment by Snugglesffxi** [comment]
Oh! I totally forgot about that..., it's only NM mobs that use it as a 2hr right?

**Comment by TeoTwawki** [comment]
this is the last time we looked into it, it didn't make it into the project just a branch when the old project closed up
https://github.com/project-topaz/topaz/pull/957

**Comment by TeoTwawki** [comment]
>  Oh! I totally forgot about that..., it's only NM mobs that use it as a 2hr right?

some normal mobs just use it on a timer like you are trying to do. problem was we had no way to mark them yet, it didn't go by zone or by expansion so we need to think about how we want to settle this.

**Comment by Snugglesffxi** [comment]
Well, I don't think normal mobs  use 1/2hrs... if that's true I don't see this as much of a problem, though admittedly perhaps I've been on an era server for far too long so I can't be positive here, but according to both wikis there is a clear separation. If this holds true, then real issue being separating isNM should be applicable. Of course I'm definitely open to a more eloquent solution!

**Comment by TeoTwawki** [comment]
> 
> 
> Well, I don't think normal mobs use 1/2hrs... if that's true I don't see this as much of a problem, though admittedly perhaps I've been on an era server for far too long so I can't be positive here, but according to both wikis there is a clear separation. If this holds true, then real issue being separating isNM should be applicable. Of course I'm definitely open to a more eloquent solution!

yes but a lot of normal mobs don't get a wyvern at all either. and some of the NMs don't have it as a 2hr, they pop like a normie mob. its all over the place.

We'll likely need a mixin to cover it rather than doing this in the core.

**Comment by Snugglesffxi** [comment]
> yes but a lot of normal mobs don't get a wyvern at all either. and some of the NMs don't have it as a 2hr, they pop like a nromie mob. its all over the place.
> 
> We'll likely need a mixin to cover it rather than doing this in the core.

There are normal drg mobs that don't get a wyvern?

And yes I think that's a better solution. I'll reopen later if we come up with something better.

**Comment by TeoTwawki** [comment]
> There are normal drg mobs that don't get a wyvern?

yep, lots of them. Can tell them apart from wars that just look like drg by the lack of any war trait like DA and their boosted acc fro drg trait (or pin down their vit stat and compare)

**Comment by Snugglesffxi** [comment]
Is there an example of one you have off the top of your head? I think it's a lot of work but it can be done if I go through the tables of the wyvens and match each up to a mob then use mixin to specify each specific mobs that aren't nms since they wyven won't exist for mobs that don't have them. It's a long process though. What do you think?

**Comment by claywar** [comment]
I think what we really need to do is to isolate mob behaviors that are different (for DRG).  Off the top of my head, I can think of the following:
1. Mobs who spawn with wyvern (does this exist?)
2. Mobs who use call wyvern on spawn
3. Mobs who use call wyvern as 2h
4. Mobs who don't call at all
5. ???

This probably won't be a one and done process, but if we can define the mixins as necessary, it'll do the heavy lifting, and then its a matter of applying them as necessary.

**Comment by TeoTwawki** [comment]
Sorry but I will not be spending my evening sift through the mobs to list which ones do what. I've had a rough week and simply do not have the energy. Fortunately at least some of this was checked into already in the previous attempt which I linked and will now quote: 
> the old Orcish Dragoons in Monastic Cavern and they still have no Wyvern at all. 

and Ix'Aern actually spawns 3 at a time starting immediately on engage (but not idle, unlike most other drg mobs) and then on a relatively timer if they are killed O_O;;;

Like clay said lets get the types defined and build out a system, we can apply which one to the right mobs and worry about which ones get which after that - as long as we have one example to know a type exists, we are good to build it out.

**Comment by Snugglesffxi** [comment]
> Sorry but I will not be spending my evening sift through the mobs to list which ones do what. I've had a rough week and simply do not have the energy. Fortunately at least some of this was checked into already in the previous attempt which I linked and will now quote:
> 
> > the old Orcish Dragoons in Monastic Cavern and they still have no Wyvern at all.

Sorry to hear about your week, I was just wondering if you knew any off the top of your head, no need for a deep look. But yes now that you've said it those guys have _never_ had a pet! Makes you wonder if that was just an accident entirely.


> Like clay said lets get the types defined and build out a system, we can apply which one to the right mobs and worry about which ones get which after that - as long as we have one example to know a type exists, we are good to build it out.

Yes, I will keep looking into this, but I'm fairly certain I'll need to login to retail just to confirm a few things like If they ALL use call wyvern vs spawn with -- pretty sure its the former but we should try to be accurate as possible so i'll check,

**Comment by claywar** [comment]
This is definitely a great conversation, and an issue that should be resolved.  I think establishing this pattern will also work well for other mobs where we are inconsistent (worms!).

**Comment by TeoTwawki** [comment]
apologies again it just hit me that the question is if they are using an ability in the log vs "this animation happens and there is a pet". and for the non 2hr ones I do believe it is the latter. my brain is juts not all here :weary:

**Pull request closed without merging**
