### PR TITLE
Scheduled Persistence Plumbing

### LINKED ISSUE #2273: 🔨 Deprecate "addCharVar"
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Describe the feature

While porting https://github.com/LandSandBoat/server/pull/2067, I noticed that Eden doesn't have `addCharVar` or similar, which: "Increments PC's variable by an explicit amount". 

I think it adds unnecessary bloat the the get/set API and we should get rid of it.

### PR DESCRIPTION
**Pull request by zach2good**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Brings in a bunch of goodies from Eden, setting us up to have scheduled/delayed persistence, charvar caching, and charvar change announcements between processes.

Closes https://github.com/LandSandBoat/server/issues/2273

## Steps to test these changes

- Make sure that content that uses charvars (read & write) still work
- Make sure that content that uses servervars (read & write) still work

### CODE REVIEW

**Comment by zach2good** [comment]
Ready for test & review

**Review by claywar — APPROVED** [review]

**Comment by zach2good** [comment]
Won't merge this until we've cleaned up https://github.com/LandSandBoat/server/issues/2122 and friends

**Comment by zach2good** [comment]
Eden merged this recently and have a bunch of fixups they found, so I'll need to port those too

**Comment by zach2good** [comment]
Requesting some help testing this one. 

Need to go through: A bunch of things that use getCharVar, setCharVar, incrementCharVar, Chocobo Digging, Guild Stuff, Server Var stuff

**Comment by zach2good** [comment]
Gone through: https://github.com/LandSandBoat/server/wiki/The-Testing-Checklist

So far only issue is that the moghouse exposition didn't get triggered

**Comment by zach2good** [comment]
I tried moghouse expo with a new character on main and it seems to be broken there too, so this branch is _probably_ as good to go as it can be

**Pull request merged**
