### PR TITLE
[build] Enable EDITANDCONTINUE on Win Debug builds

### PR DESCRIPTION
**Pull request by zach2good**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

- Bumps minimum CMake version, this is the version that ships with VS2019, so we should be good across the board
- Adds some more flag logging at startup, including linker flags - very useful (for me at least)
- Forces LTO off for Windows Debug build configurations from Big Visual Studio (where EDITANDCONTINUE is supported)
- Makes IPO options+flags clearer and more searchable
- Fixes long standing issue where we check for CMAKE_CONFIGURATION_TYPES instead of CMAKE_BUILD_TYPE
- Fixes unknown strangeness in our CMake setup where /Zi always appears, so we override it in the one situation we want /ZI 

## Steps to test these changes
```
⚠️ ⚠️ ⚠️ 
THIS IS ONLY ENABLED FOR DEBUG BUILDS LAUNCHED FROM FULL VISUAL STUDIO!
IF YOU TRY AND USE THIS ON A LIVE SERVER I WILL LAUGH AT YOU UNTIL THE END OF TIME AND OFFER NO HELP EVER AGAIN!
⚠️ ⚠️ ⚠️ 
```

Do some hot-reloading*.

*NOTE: Not everything is supported. If you want to add prints you can use `fmt::format`, our regular logging is too spicy to be added to hot-reloading files.

```
⚠️ ⚠️ ⚠️ 
THIS IS ONLY ENABLED FOR DEBUG BUILDS LAUNCHED FROM FULL VISUAL STUDIO!
IF YOU TRY AND USE THIS ON A LIVE SERVER I WILL LAUGH AT YOU UNTIL THE END OF TIME AND OFFER NO HELP EVER AGAIN!
⚠️ ⚠️ ⚠️ 
```

### CODE REVIEW

**Review by claywar — APPROVED** [review]

**Comment by zach2good** [comment]
Putting a hard hold on this, as it requires a lot of testing and experimenting, and an accompanying wiki page explaining how/when to use it. 

and more scary warnings not to ever use it while hosting actual players.

**Comment by TeoTwawki** [comment]
> THIS IS ONLY ENABLED FOR DEBUG BUILDS LAUNCHED FROM FULL VISUAL STUDIO!
IF YOU TRY AND USE THIS ON A LIVE SERVER I WILL LAUGH AT YOU UNTIL THE END OF TIME AND OFFER NO HELP EVER AGAIN!

🤣 

Get to laughing at many servers of the old dsp age, where that was enabled and they used it to last minute save themselves from crashes but we laughed at anyone running in debug mode.

**Review by TeoTwawki — APPROVED** [review]
preemptive approval pending that testing you posted about, coz i know you are good for it 👍

**Comment by zach2good** [comment]
I'm having an issue across _all my branches_ for xi_map startup that I can't locate. This PR builds and works fine on the other executables, so it's good to go.

**Comment by zach2good** [comment]
(Others aren't having that issue, so it's something with my local env)

**Pull request merged**
