### PR TITLE
[sql] Mhaura moogle visible underneath Laughing Bison

### PR DESCRIPTION
**Pull request by MowFord**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Unsure what this moogle's intended use is, but it's definitely not supposed to be visible. There's no references to the NPC id anywhere, nor is there a lua file for it. Probably an asset for some cutscene. This PR simply sets the flag to hide it.

image

using `!npchere` to move laughing bison:

image

### CODE REVIEW

**Comment by zach2good** [comment]
Someone probably has a recent retail cap to see what the story is with this guy

**Review by TeoTwawki — APPROVED** [review]
he was just playing hide and seek with his mog friends, kupo

**Comment by TeoTwawki** [comment]
this pr might wind up held or invalidated due to client id updates being worked on

**Comment by MowFord** [comment]
> this pr might wind up held or invalidated due to client id updates being worked on

it's fine, I can do a quick rebase after that's all done

**Comment by MowFord** [comment]
> Someone probably has a recent retail cap to see what the story is with this guy

btw a kind soul got a capture from retail near laughing bison:

no npc id shift here

image

next ID only ever shows up in these partial updates, without even an NPC name

image

**Comment by claywar** [comment]
Holding on this for all shifts to be completed from the March update

**Pull request merged**
