### PR TITLE
[WIP] [JP] Fix Tier V RDM nukes

### PR DESCRIPTION
**Pull request by Xaver-DaRed**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

TODO: Allow RDM to cast tier V nukes, obtained from job point gifts.
Corrected some parameters of refresh III, but still disabled.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
We might have to do something extra for this seeing as other jobs can get it sooner, and a 99 rdm won't have it prior to the job points - meaning if you did blm up 1st and then rdm dings 99 these would show up as castable on the spell list.

**Comment by RAIST5150** [comment]
> 

Requirements field towards the end?  Not sure what would normally go there... perhaps a flag for whether the spell was merited and such?  If so, maybe there could be a flag for if the job points were spent?

**Comment by Xaver-DaRed** [comment]
The problem would persist. If we set a requirement in DB, it will transfer to all jobs

my guess would be to add an exception for job point gift spells here, in spell.cpp
```
// Check If user can cast spell
bool CanUseSpell(CBattleEntity* PCaster, CSpell* spell)
```

**Comment by claywar** [comment]
The ideal solution would be to handle it on a packet level, and also ensure on CanUseSpell.  Packet-side will make sure the client greys it out, but another thing we need to check for is if this is handled outside of the scroll requirement for BLM and SCH.  For example, if a RDM learns it through JP, do those jobs still need to eat the scroll?

**Comment by WinterSolstice8** [comment]
Found this PR when looking up how to implement Temper for RUN -- here's my 2 cents.

>For example, if a RDM learns it through JP, do those jobs still need to eat the scroll?

I don't have evidence of this other than my own personal testimony but I had a second account where I learned Tier V spells through GEO job points, and I did _not_ need any scrolls for BLM Tier V spells.  It's probably just part of SE's spaghetti code and/or simply ease of development to simply "learn" the spell to make it appear in your menu permanently. Since job points are permanent it doesn't make a lot of sense to unlearn how to cast a spell narratively. 

I think handling it in the packet area is the only way that makes sense. Jobs that can't cast these spells without job points should only be able to cast them under 2 conditions: Level 99 & have the appropriate amount of job points. 

Here's a picture of me on retail when on Rune Fencer showing that I don't "unlearn" Temper II (RDM JP), Tier VI nukes and other job point gift only spells when I'm not on the correct job.

image

 I assume the client knows that I can cast these when on the right job (at level 99), as in the current server emulator version I can _attempt_ to cast Temper on RUN 99, but the server rejects me. I assume that were I to learn Tier V spells and tried to cast them at RDM/GEO 99 my client might let me try to cast them. Unfortunately, I really can't test this. All those jobs already have the job point gifts. Maybe my alt account doesn't...

**Comment by WinterSolstice8** [comment]
How about something like this? Fully working example that compiles in VS2022. It would exist in Spell.cpp/Spell.h. Stuff is truncated/brief to make the idea more plain. It would reuse the existing SpelllID enum class, which we already have to maintain.

```
#include <map>

enum class SpellID : uint16_t
{
    Fire_V    = 148,
    Temper_II = 895,
};

enum JOBTYPE
{
    JOB_RDM = 5,
    JOB_GEO = 21,
};

struct GiftMap {
    static std::map<SpellID, std::map<int, int>> create_map()
    {
        std::map<SpellID, std::map<int, int>> m;
        m[SpellID::Fire_V][JOB_RDM]    = 100;
        m[SpellID::Fire_V][JOB_GEO]    = 100;

        m[SpellID::Temper_II][JOB_RDM] = 1200;
        return m;
    }
    static const std::map<SpellID, std::map<int, int>> SpellToGiftMap;
};

const std::map<SpellID, std::map<int, int>> GiftMap::SpellToGiftMap = GiftMap::create_map();


int main() //Pretend this is bool CanUseSpell(CBattleEntity* PCaster, SpellID SpellID) from /src/map/spell.cpp
{
    SpellID spell = SpellID::Fire_V;
    int PCasterJob = JOB_RDM;
    
    bool CanUse = false;
  /* bool CanUse = CanUseSpell(PCaster, spell);
     if (!CanUse)...  if we can't use the spell through the Spell.sql database...
     {
    */
        auto SpellHashmapItem = GiftMap::SpellToGiftMap.find(spell);
        if (SpellHashmapItem != GiftMap::SpellToGiftMap.end()) // Is a spell with a job:job point gift map
        {
            auto JobSpellHashmap = SpellHashmapItem->second;

            auto JobSpellHashmapItem = JobSpellHashmap.find(PCasterJob);
            if (JobSpellHashmapItem != JobSpellHashmap.end()) //Our job can cast the spell
            {
                int PCasterJobPoints = 100; //GetPCasterJobPoints
                int JobPointsRequired = JobSpellHashmapItem->second;
                if (PCasterJobPoints >= JobPointsRequired) //our job can cast the spell AND we have the job points for it.
                    CanUse = true;
            }
        }
  //}
    return CanUse;
}
```

Should be pretty fast given it's std::map, even if nested.

**Comment by WinterSolstice8** [comment]
This account on retail has RDM99 with 0 job points but learned Thunder V elsewhere (GEO job points)

image
you can see the RDM main only spell (haste 2), and that tier V spells are greyed out. I'm guessing the clientside gift list is the one that the client checks for what you can/can't cast.

If I try to bypass the menu and use the shortcuts addon (via gearswap direct packet injection) to cast Thunder V this happens:
image

**Pull request closed without merging**
