### PR TITLE
Convert Windurst Missions Batch 1

### PR DESCRIPTION
**Pull request by Era-Lusiphur**
Intend to cover up through 2-2 inside this batch. It's likely going to be a pretty large collection of changes, but I'll be posting commits publicly as I go so they can be criticized as I progress. Started running an alt through Windurst missions on retail because verification of optional dialogue was becoming problematic.

Notes so far:

**General**
- Was able to verify Windurst Walls nearby NPCs default dialogue prior to immigrating

**Windurst 1-1 : The Horutoto Ruins Experiment** 
- Merged PR for this one is here: #498 
- Had the opportunity to run back through and verify some of 1-1 as well as do some off-repo style requests.
- Per recent discussion with some folks, deleted the now useless Windy 1-1 Magical Gizmo NPC scripts.
- Encountered instance of a likely unintentional CS with Mokyokyo hitting the cutting room floor and not following the typical pattern. I have made a judgement call and restored and notated this. If reviewers don't like it, I can throw in the retail event and leave the lost content in a comment.

**Windurst 1-2 : The Heart of the Matter** 
 - Confirmed these Magical Gizmos have no DefaultAction outside of the mission, via checking after mission is completed and on a 2nd non-Windurst citizen character. Uncertain about prior to receiving the mana orbs from Apururu at the start of the mission. msgBase offset +12 reads "This appears to be a device that recharges Mana Orbs." Possibly unused? We originally had it displayed outside of the mission.
 - Confirmed where KIs were silently deleted.
 - Verified both possible endings of this quest thanks to Wiggo's capture of the orbs being lost and warping on my own character to capture the outcome of saving them. 

**Windurst 1-3: The Price of Peace**
 - Confirmed Yagudo NPCs' dialogue during and after the mission, for a Windurstian and Bastokan (who did previously complete the mission before immigrating back to Bastok). Also tested for double and triple tapping. Did not find an instance of Ghoo's event 51 or Laa's 46 triggering, so presuming it's cutting room floor dialogue. 
 - Confirmed new dialogue for Kenapa-Keppa.
 - Correct keyitem names for DRINK_OFFERING and FOOD_OFFERING to match in-game.

**Windurst 2-1: Lost for Words**
 - Corrected message text per retail capture for Fossil Rocks interactions.
 - Added/confirmed optional dialogue for Nanaa's cronies and the NPCs in the same room as Tosuka-Porika at various stages of the mission.

**Windurst 2-2: A Testing Time**
 - Changed the check for the mission being active from every mob killed in game to just non-NMs in Tahrongi Canyon and Buburimu Peninsula. This now occurs in zone-specific globals and is called from onMobDeath from just those mobs.
 - Added/confirmed optional dialogue for many school children and masters.
 - Was unable to 100% verify the killCounts needed for every CS. I kept the existing values in place.
 - Need to verify gate guard events post-mission, if any exist.

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Review by claywar — APPROVED** [review]

**Comment by Era-Lusiphur** [comment]
Added Windy 1-2: The Heart of the Matter. Tested both possible outcomes multiple times.

~~Noticed that Windurst Walls lacks the You Accepted the Mission text ID the other zones have. Pulled it up in POLutils, exported it, and couldn't find even a close match for the text.~~

~~Will have my retail character flag the next mission with him to try to observe what message is actually used there, if any. Re-arranged handleAcceptMission for both 1-1 and 1-2 for now so that it will just print an error to the log if you flag it with him and cause no problems for the player during testing.~~

Took care of this in commit below.

**Comment by Era-Lusiphur** [comment]
1-3 is not currently 100% and playable without GM commanding through, just committing work so far on it.

**Comment by Era-Lusiphur** [comment]
Missions 1-1 through 1-3 are ready for review / testing. Ran through them myself a few times, everything looks good. Moving forward.

**Comment by Era-Lusiphur** [comment]
Missions 2-1 and 2-2 ready for review / testing.

**Comment by claywar** [comment]
Combined this PR after resolving merge conflicts into #850 , closing this PR and tracking work there.

**Pull request closed without merging**
