### PR TITLE
GM command for banning or unbanning players from using /YELL

### PR DESCRIPTION
**Pull request by CatsEyeXI**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
Adds a GM command that allows for banning or unbanning of a player's yell privileges.

## Steps to test these changes
image

### CODE REVIEW

**Comment by CatsEyeXI** [comment]
sorry for the multiple force pushes, had an issue deciding what the command trigger should actually be.

**Comment by MowFord** [comment]
Btw a rebase will resolve your ci failure

**Comment by CatsEyeXI** [comment]
Maintainers: I'm not in any rush for you guys to merge this or anything, just wondering if you need anything from me, or if it's undesired. Either way completely fine, I just have some OCD about leaving stale branches out there. 🫶

**Review by WinterSolstice8 — APPROVED** [review]
Github seems to have removed my ability to restart CI on this PR so you might have to rebase and force push to get it to try again.

**Comment by CatsEyeXI** [comment]
> Github seems to have removed my ability to restart CI on this PR so you might have to rebase and force push to get it to try again.

all set, mister.

**Review by Xaver-DaRed — APPROVED** [review]

**Pull request merged**
