### PR TITLE
Search comments, preferred languages, and mentor search

### PR DESCRIPTION
**Pull request by InoUno**
Adds search comments, preferred languages, and mentor search.

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Review by claywar — APPROVED** [review]
Thanks Ino!  We'll need to create a migration script, but really appreciate this contribution!

**Review by zach2good — APPROVED** [review]
Siiiiiick, thanks!

**Comment by InoUno** [comment]
> Thanks Ino! We'll need to create a migration script, but really appreciate this contribution!

Ah, looks like I forgot to add those to the commit. Is it correctly understood that the `accounts_sessions` table doesn't need a migration, because it is updated automatically?

**Comment by claywar** [comment]
From a quick look, I think we just need to add languages to chars

**Pull request merged**
