### PR TITLE
[Lua] Add ZNM NPC to unique_event

### PR DESCRIPTION
**Pull request by hooksta4**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
Place holder for ZNM NPC's Sanraku and Ryo in unique_event. Will determine which dialog players will get upon talking to either NPC.

## Steps to test these changes
None at this time.

### CODE REVIEW

**Comment by zach2good** [comment]
These aren't fast-moving files, so why not just do the rest of the logic now too? Ekokoko is a full example of how this system works.

**Comment by hooksta4** [comment]
So I don't forget it.

**Comment by zach2good** [comment]
To clarify what I want from this PR: The latching logic for "I have spoken to Sanraku for the first time", and "I have spoken to Sanraku for subsequent times" - which is just a single if/else block if memory serves.

Using a single-line PR as a way for you not to forget that a feature exists is pointless.

**Comment by zach2good** [comment]
It's been 45 days since this PR you wanted to use as a reminder was opened, and there hasn't been any movement on it. It's just a single line - I'm going to close it. Feel free to return and do the first-talk chat changes with Sanraku (and his apprentice, whoever that was?) and back it with the uniqueEvent system.

**Pull request closed without merging**
