### PR TITLE
[SQL] Add "Gold Ring" Desynth

### PR DESCRIPTION
**Pull request by Xaver-DaRed**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Allows Gold Rings to be desynthed.
- https://www.bg-wiki.com/ffxi/Gold_Ring
- https://ffxiclopedia.fandom.com/wiki/Gold_Ring

## Steps to test these changes
Get a gold ring
Get a lightning crystal
Get lvl 60 in goldsmithing
Profit

### CODE REVIEW

**Comment by hookstar** [comment]
My repo went completely sideways for some reason. Ended up having to blow it up. Thanks for the save.

**Review by WinterSolstice8 — APPROVED** [review]

**Comment by Frankie-hz** [comment]
Should this go at the end of 29000? I believe the IDs are sorted/sectioned by craft

**Comment by TeoTwawki** [comment]
> Should this go at the end of 29000? I believe the IDs are sorted/sectioned by craft

when the full list was redone by tooling ages ago, it sort of happened to work out that way but as a word of warning the numbers are arbitrary and must never be re-sequenced just to keep them together with a category. If there is a hole from a mistake being removed, the hole can be filled in. Otherwise final/first free ID +1'd

**Comment by Xaver-DaRed** [comment]
No harm in having all goldsmithing desynths together when theres room for it.

Moved it there

**Comment by TeoTwawki** [comment]
right. we just don't gaf if in the future they don't stay together.

**Comment by Frankie-hz** [comment]
Oh I completely understand they are arbitrary numbers - might as well *try* to keep it going lol

**Comment by TeoTwawki** [comment]
yeah as long as there is gap to use (at this particular section...whole LOTTA gap o.O) but when we run outa gap, its not important

**Pull request merged**
