### PR TITLE
[navmesh] Reduce values for findNearestPoly search area

### PR DESCRIPTION
**Pull request by zach2good**
I did a live stream, I profiled some things. All the navmesh calls have gone from 200us to 50us (or less). 
Probably warrants some testing, but looks like a pretty easy win.

The extants passed to findNearestPoly appear to just be defining a box in which to search. We generate the vast majority of points that we're searching around, and later validating, by lerping between points given to us from detour's findPath, so they're very likely to be valid, or extremely close to a valid point 

So it seems to be safe to reduce this search area. 

There is a tiny chance this might affect wyrm's draw in. If they can search a massive area, they won't be able to validate a broken-add point to warp you to, so they'll work better. This is just untested conjecture though, could be worth a look. 

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by claywar** [comment]
cooltext385649371816577

**Comment by zach2good** [comment]
TODO: Post before/after measurements and do some testing in problem areas (that corner near the AH in Windurst Walls (or Waters?))

**Comment by zach2good** [comment]
image
image

**MTPC** is the average time per function call:

Before:
image

After:
image

**Comment by claywar** [comment]
I'd say thats significant

**Comment by zach2good** [comment]
As an additional test, I ran with 1/2/1 values, with an extension to 5/10/5 to the part of raycast which looks for the nearest walls, and the numbers were not significantly better:
image

**Comment by Era-Lusiphur** [comment]
Seen visible gains even without scoping with this adjustment. 10/10, would recommend.

**Comment by zach2good** [comment]
Still probably want more experimentation on the effects of reducing the search bounds on raycast - but the others would be safe bets to reduce to 5/10/5

EDIT: Lies, raycast does its own thing without worrying about extants: https://docs.unrealengine.com/4.26/en-US/API/Runtime/Navmesh/Detour/dtNavMeshQuery/raycast/

**Comment by zach2good** [comment]
Updated

**Review by TeoTwawki — APPROVED** [review]
makes sense to me given performance benchmark

**Pull request merged**
