### PR TITLE
[instance & quest] Light into the Darkness (WOTG Bastok Nation Quest 3)

### PR DESCRIPTION
**Pull request by zach2good**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by zach2good** [comment]
Kinda want to get this merged so that the SQL changes get in before they trip anyone up. This will still need some more follow up, and the instance system is still getting some bugs ironed out. (As well as cutscene blackscreens, which are now out of scope of this PR)

**Comment by zach2good** [comment]
Theres no vector for abuse for leaving this open: it doesn't play the CS yet, and it doesn't drop any loot 🤷

**Review by Era-Lusiphur — APPROVED** [review]
Pulled, tested. Nothing blows up. A good start for the instance. I would prevent normal PCs from entering while the quest line isn't hooked up, to avoid confusion until it's ready.

**Comment by zach2good** [comment]
Back to WIP, as I start writing the quest that's around this instance

**Comment by zach2good** [comment]
No longer WIP, ready for review

**Review by Xaver-DaRed — APPROVED** [review]

**Review by claywar — APPROVED** [review]

**Pull request merged**
