### PR TITLE
[modules] Add plumbing for basic Lua module system

### PR DESCRIPTION
**Pull request by zach2good**
All opinions and ideas welcome

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by zach2good** [comment]
As complete as a v1 should be. Stripped down to a single simple module (homepoint heal). Changed the API to to take the string name, instead of a table and a string, looks nicer.

Still need to test a little when my ports unlock themselves

**Comment by zach2good** [comment]
Tested:
- Heals when I touch a HP
- HP menu appears as normal
- If I add `print("Yay!")` into the module override -> `[08/17/21 21:08:05:623][map][info][lua] Yay!  (luautils::print:491)`

**Review by TeoTwawki — APPROVED** [review]
looks good to me

**Review by claywar — APPROVED** [review]

**Review by Xaver-DaRed — APPROVED** [review]
In memory of the great moustache.

**Pull request merged**
