### PR TITLE
Environment Variable Refactor + Remove Docker files

### PR DESCRIPTION
**Pull request by Sunderous**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Update settings.cpp to allow for arbitrary configuration of environment variables using the template XI_{outerKey}_{innerKey}.

Updates to the docker related files to configure everything through the environment, as well as add a reverse proxy to make server available from non-localhost boxes by default.

## Steps to test these changes

Ignoring the Docker stuff, if you set any environment variables before you start like XI_NETWORK_SQL_HOST, or XI_MAIN_SERVER_NAME, it should be automatically reflected in the logs and the runtime behavior when starting up the server.

### CODE REVIEW

**Comment by Sunderous** [comment]
Not trying to open up the Docker pandoras box again, but figured I'd submit the changes in full for review. Then if people agree the settings changes are a good idea, but don't want to deal with the docker stuff, I'll split it out into a separate branch and re-submit.

**Comment by WinterSolstice8** [comment]
These changes seem reasonable to core and CI passes. I can't in good faith blindly approve unless someone else chimes in that this works. I don't use docker and don't plan to use docker, and docker is unsupported as per our wiki. If this helps everyone, I will gladly approve.

**Comment by Sunderous** [comment]
My plan was to submit another 2 PRs (server+ wiki) once I had a chance to draft an updated wiki article that would:
- Remove the docker files from the main repo (add them to .gitignore if not supporting them at all).
- Add the example Dockefile + docker-compose to the wiki with some context.

Which I think is what was being leaned towards from the other discussion in this [PR](https://github.com/LandSandBoat/server/pull/2184).

If @zach2good or @TeoTwawki can chime in to verify that approach is fine, then I'll go ahead and just close this PR for now and submit a fresh one with the final changes for the server +wiki instead early this week. Thanks!

**Comment by zach2good** [comment]
> My plan was to submit another 2 PRs (server+ wiki) once I had a chance to draft an updated wiki article that would:
> 
> * Remove the docker files from the main repo (add them to .gitignore if not supporting them at all).
> * Add the example Dockefile + docker-compose to the wiki with some context.

👍 

The core changes look good, +1 for removing all the docker things and move to a wiki article

**Comment by zach2good** [comment]
I don't understand networking stuff, what does that reverse proxy do?

**Comment by Sunderous** [comment]
> I don't understand networking stuff, what does that reverse proxy do?

I'm only like 90% sure of this based on my observations so don't quote me haha. But by default if you startup a bunch of docker containers with compose, even if internally the code is binding to 0.0.0.0, that still only allows you to access those services on the same local machine you're running on because the default docker network isn't exposed to your LAN.

Don't quote me on that, I was changing a few things at the same time, but that was my impression.

The reverse proxy acts as an ingress point, that bridges an external docker network to the internal docker network. So you route all traffic to the proxy, and it decides what to do with it (which service/port to send it to within all the docker stuff).

This solves 2 problems: It lets you access the server from any other host on the network (this is what I wanted for my workflow, code on my linux laptop and run the server -> test on my windows machine where I have XI), and it makes it more secure because traffic can't hit the server/db directly so if you want to implement any security/encryption you only have to do it in one spot.

**Comment by Sunderous** [comment]
> > My plan was to submit another 2 PRs (server+ wiki) once I had a chance to draft an updated wiki article that would:
> > 
> > * Remove the docker files from the main repo (add them to .gitignore if not supporting them at all).
> > * Add the example Dockefile + docker-compose to the wiki with some context.
> 
> 👍
> 
> The core changes look good, +1 for removing all the docker things and move to a wiki article

Sounds good, I'll update this PR and submit the wiki changes as soon as I get a chance.

**Comment by Sunderous** [comment]
@zach2good @WinterSolstice8 

As per discussion, removed the docker files in this PR, opened a PR on the wiki to explain things and provide the examples:
https://github.com/LandSandBoat/lsb-wiki/pull/1

Let me know if that's suitable, I never know what tone to take with these things haha.

**Comment by zach2good** [comment]
Seems fine to me 👍

I don't really know our workflow for external additions to the wiki, that's probably a job for @TeoTwawki

I like the C++ changes in this PR, can you trim it down to just those in a single commit (interactive rebase, etc.)? We'll take them and then we're never on the hook for env vars again

**Comment by Sunderous** [comment]
> Seems fine to me 👍
> 
> I don't really know our workflow for external additions to the wiki, that's probably a job for @TeoTwawki
> 
> I like the C++ changes in this PR, can you trim it down to just those in a single commit (interactive rebase, etc.)? We'll take them and then we're never on the hook for env vars again

Because I'm an idiot, and did the default github sync with the upstream changes in the middle of this (twice), rebasing is turning into a nightmare, and I'm not a git guru. I'm going to close this PR, make 2 fresh branches and submit a PR for just the settings changes, and one for the docker removal.

**Pull request closed without merging**
