### PR TITLE
[Lua] inherit sneak/invis multiplier from global settings for tonko & monomi

### PR DESCRIPTION
**Pull request by CatsEyeXI**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Factor in global multiplier for ninjutsu sneak/invis

## Steps to test these changes

Cast Monomi/Tonko before and after change.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
iirc, didn't somebody remove it from the white magic spell? should prolly add it back if we're doing it for ninjutsu.

**Comment by CatsEyeXI** [comment]
> iirc, didn't somebody remove it from the white magic spell? should prolly add it back if we're doing it for ninjutsu.

I'll check these as well as spectral jig then

**Comment by Xaver-DaRed** [comment]
Honestly, I think those multipliers should be removed.
You can acomplish the same at this point by editing the parameter table. It gives as much or even more control over what spells do

**Comment by TeoTwawki** [comment]
> Honestly, I think those multipliers should be removed. You can acomplish the same at this point by editing the parameter table. It gives as much or even more control over what spells do

fair point about the params. also the durations were much shorter back when the setting was made

**Pull request closed without merging**
