### PR TITLE
[core] Implement mobs with bind attacking nearby players

### LINKED ISSUE #5541: 🔨 Implement attacking-closest-available-target for Bind
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Describe the feature

See description, bind AI doesnt match retail. The bound mob should target/rotate towards the closest available target and melee things that aren't necessarily the highest on their hate list

### PR DESCRIPTION
**Pull request by WinterSolstice8**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Implements the mob AI functionality where mobs will face towards their closest target when bound an attack them (assuming they are on the enmity list of the mob) as long as their primary target with the most enmity is too far away.

Closes #5541

## Steps to test these changes

Bind mob, get a lot of hate on it, move away from it, have another player stand near the mob, note it's not attacking that player, cure a player on the hate list, now the mob is will attack the player near the mob

### CODE REVIEW

**Review by claywar — APPROVED** [review]

**Review by Xaver-DaRed — APPROVED** [review]

**Comment by ampitere** [comment]
This is really cool, also works with pets.

**Comment by WinterSolstice8** [comment]
> This is really cool, also works with pets.

Hmm... not sure it's supposed to... aside from BST charmed pets, and a hard maybe for jugs...

**Comment by ampitere** [comment]
> > This is really cool, also works with pets.
> 
> Hmm... not sure it's supposed to... aside from BST charmed pets, and a hard maybe for jugs...

I was using a SMN avatar if that helps.

**Comment by WinterSolstice8** [comment]
Yeah I don't think it's supposed to do that. I dont have any confirmation except on normal mobs

**Pull request merged**
