### PR TITLE
Make geo_attack_boost and geo_accuracy_boost affect ranged att and acc

### PR DESCRIPTION
**Pull request by cmastro24**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
This patch adds ranged attack/accuracy to geo fury 

## Steps to test these changes

Create the changes to the geo_fury effect and geo precision effect (indy versions as well).  Equip a ranged weapon and test that both regular attack/accuracy and ranged attack/accuracy accurately get increased.  Verify that upon buff wearing that the accuracy/attack boost are removed.
https://www.bg-wiki.com/ffxi/Geo-Fury
https://www.bg-wiki.com/ffxi/Geo-Precision

### CODE REVIEW

**Comment by Xaver-DaRed** [comment]
Rebase properly. Most of those commits shouldnt be there

**Comment by cmastro24** [comment]
Yup sorry, I missed that.  I just pushed my new changes.

**Comment by cmastro24** [comment]
Again my fault, squash is new to me so my apologies

**Review by Xaver-DaRed — APPROVED** [review]
The changes themselves are ok

**Review by EpicTaru — APPROVED** [review]

**Review by WinterSolstice8 — APPROVED** [review]

**Pull request merged**
