### PR TITLE
Fix ci errors

### PR DESCRIPTION
**Pull request by CatsEyeXI**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

We've been getting errors in the CI check when checking formatting, I think this should correct that

## Steps to test these changes

CI check should no longer fail for Abyssea La Theine and Tethra NM

### CODE REVIEW

**Comment by kaincenteno** [comment]
@CatsEyeXI  this might need rebase from base? I see other commits on it not related to CI

**Comment by claywar** [comment]
Closing this PR, as it seems to be an incorrect target

**Comment by CatsEyeXI** [comment]
sorry about this folks

**Comment by CatsEyeXI** [comment]
> Closing this PR, as it seems to be an incorrect target

sorry >.<

**Pull request closed without merging**
