### PR TITLE
Added marid_hide to Marids in BhafThicket

### PR DESCRIPTION
**Pull request by CatsEyeXI**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

Marids in Bhaflau Thickets should drop Marid hides at 36.7% as per ffxidb

http://ffxidb.com/items/2151

### CODE REVIEW

**Comment by Xaver-DaRed** [comment]
For future reference, when using FFXIDB, one must use the TH0 column, not the global average.
FFXIwiki has drop rate at 8.8%
BG-Wiki has no drop rate info.
FFXIDB TH0 column has a 15% drop rate.
JP Wiki has no info.

Also, SE released this chart.
imagen

With all of this info, I would propose drop rate to be 15%, becouse FFXIDB TH0 and TH2 seem to align the best.

**Comment by zach2good** [comment]
+1 for the TH0 thing, thats pretty important

**Review by Xaver-DaRed — CHANGES_REQUESTED** [review]
This changes alone wont make any item drop from Marids in Bhaflau Thickets.

You need to add the dropID (4004 in this case) to the mob_groups table.

imagen

So 3 things:
- Change dropID from 4004 to 3206. Lets follow an order.
- Change droprate from 367 to 150.
- Add dropID 3206 to Bhaflau Marids in mob_groups table.

**Review by Xaver-DaRed — APPROVED** [review]

**Comment by TeoTwawki** [comment]
Regarding TH0, just to be clear I don't think we want to be directly using any websites recorded value. 

As Xaver was describing we want to use the overall information to get a good estimate of which TH "bucket" the actual retail drop rate fits: common? very common? rare? And then using the appropriate numbers from SE's chart for your TH0 value.  I think we really need a solid guide to determining drop rates added to our wiki.

**Pull request merged**
