### PR TITLE
NPC and Mob shifts for Dec-21 Update

### PR DESCRIPTION
**Pull request by claywar**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by claywar** [comment]
That looks like most of the NPC shifts, just need to fix scripts that depend on old IDs

**Comment by claywar** [comment]
Think I caught all of the IDs updated for impacted zones now, should be good to go.

**Review by zach2good — APPROVED** [review]
I spot-checked an area in dunes that I know has shifted, looks good to me 👍

**Review by TeoTwawki — DISMISSED** [review]
lgtm, if anything is missed we'll fix after

**Comment by TeoTwawki** [comment]
version conf?

**Pull request merged**
