### PR TITLE
[sql] [lua] Add Pools/Skill Lists/Abilities for Trial Sized Avatars

### LINKED ISSUE #2719: 🐛 Garuda Prime- lvl 20 fight(Trial-Size Trial by Wind)
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 
`base`

## Steps to reproduce
I went to get mini fork of wind from rabao npc.  Went to fight trial level 20 garuda but he casts aero IV which is level 72 BLM spell. He should be casting aero 2 instead.
20 smn garuda aero 4
https://ffxiclopedia.fandom.com/wiki/Summoner:_Level_20_Avatar_Battles_by_Andres#Third_Battle:_Garuda

After I died, I went back and I wasn't able to trade mini fork to Proto Crystal?
fork smn 20 garuda

https://www.bg-wiki.com/ffxi/Mini_Fork_of_Wind

## Expected behavior
Aero II instead of Aero IV?
Can use fork again after death?

### PR DESCRIPTION
**Pull request by neuromancerxi**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

* Adds Mob Pools and Skill Lists for Trial Sized Avatar fights 
* Updates Groups to use the new Mob Pools and Skill Lists 
* Adds Missing Mob Ability scripts for Garuda, Shiva, Ifrit, Ramuh, and Titan.

Closes #2719 

## Steps to test these changes

Follow steps/prerequisites to participate in Trial Sized Trial by (Ice/Fire/Earth/Wind/Water/Thunder)
Observe Mobs will only use abilities from Level 20 and Below

### CODE REVIEW

**Comment by WinterSolstice8** [comment]
These mobskill scripts are just copies of the player BPs, right?

**Comment by TeoTwawki** [comment]
> These mobskill scripts are just copies of the player BPs, right?

Not copies (as some functions differ between which entities can call them) but they use the same values where possible, so should be approximately equivalent so should be fine here.

Future forward, I'd like people to state where they source the numbers from up front (saves back and forth time and us checking what might have been). There have been past discussions about this, but they fall out of the community's collective memory pretty fast.

**Comment by WinterSolstice8** [comment]
> but they use the same values where possible, so should be approximately equivalent so should be fine here.

Sweet. that's what I was looking for. Thanks

**Review by WinterSolstice8 — APPROVED** [review]
LGTM

**Pull request merged**
