### PR TITLE
[meta] Publish changelogs to website branch

### PR DESCRIPTION
**Pull request by zach2good**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by zach2good** [comment]
My fork:
image
First entry: Added by hand
Second entry: Added by automatic github action (will remove)

**Comment by zach2good** [comment]
I've also added a 2 week changelog from the 1st, to kick things off:
https://github.com/LandSandBoat/server/tree/website/changelogs

**Review by claywar — APPROVED** [review]

**Comment by zach2good** [comment]
Once this is merged, I'll set this up on my fork and set it to run every 2 days. Then we should have some confidence it won't fall over at the first hurdle

**Comment by zach2good** [comment]
Ok, I've set this up in my fork to run every night at 1 am. In a few days this should fill up with increasingly large changelogs: https://github.com/zach2good/server/tree/website/changelogs

**Pull request merged**
