### PR TITLE
Vendor Price Data - 2022-05

### PR DESCRIPTION
**Pull request by neuromancerxi**
Retail vendor prices captured during May 2022 Return Home Campaign.

Went sifting through mules and pulled in vendor sale prices for items I had in inventory or got from Gobbie Chest. Where possible tests were done with a Fame 0 Character.

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?
Adds Vendor buyback prices for various items.

## Steps to test these changes
Add any adjusted items, sell to vendor with Fame 0 Character.

### CODE REVIEW

**Review by claywar — APPROVED** [review]

**Comment by UynGH** [comment]
Hello and thank you!

I don't know to which vendor you sold your items but for future reference, back on Topaz we confirmed that Challoux (https://www.bg-wiki.com/ffxi/Challoux) is a "fameless" NPC. You can sell everything you want to her whatever your fame is. For now it's better to have a price listed than zero.

**Comment by neuromancerxi** [comment]
> Hello and thank you!
> 
> I don't know to which vendor you sold your items but for future reference, back on Topaz we confirmed that Challoux (https://www.bg-wiki.com/ffxi/Challoux) is a "fameless" NPC. You can sell everything you want to her whatever your fame is. For now it's better to have a price listed than zero.

Noted for future captures, thanks! Would it make sense to add a SQL comment to the top of `item_basic` with this info to prevent any potential confusion/inaccuracies?

**Comment by zach2good** [comment]
> Would it make sense to add a SQL comment to the top of item_basic with this info to prevent any potential confusion/inaccuracies?

I think a prominent comment at the top of the file would be pretty useful!

**Review by zach2good — APPROVED** [review]
Love that giant comment!

**Pull request merged**
