### PR TITLE
[core] Session cleanup and improvements

### PR DESCRIPTION
**Pull request by WinterSolstice8**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

When you login, the server pulls a charid from your login packet, but due to the robust login packet changes, sometimes there's junk data that looks decryptable but isn't
This should severely limit any junk making it across as charid

Cleanup session immediately instead of deffering cleanup to a secondary cleanup if session timed out.
Remove accounts_session immediately on timeout

Remove a bunch of excess/copy pasted code from session cleanup
## Steps to test these changes

Login as normal when zoning,

Disconnect with the following methods
* standard force d/c
* /logout
* /shutdown
* block outgoing C2S packets after casting warp/teleports/etc

### CODE REVIEW

**Review by claywar — DISMISSED** [review]

**Comment by WinterSolstice8** [comment]
Chasing some bug here and finding other stuff that needs cleanup, currently drafted

**Comment by WinterSolstice8** [comment]
Probably done with PR because it's getting long in the tooth but will take some more time to test

For reviewing the changes to `map_cleanup`, better to view the file as-is with this PR and compare to the old one. I more or less just squished it down into a much more readable less else/if copypaste.

**Comment by WinterSolstice8** [comment]
Seems to be fine

**Comment by WinterSolstice8** [comment]
I lied. I pushed one more commit because I realized I could actually validate 0x00As in some meaningful way.

**Review by Xaver-DaRed — APPROVED** [review]
Shameless disclaimer: My approval is out of respect for you and your work, not because I actually understand what's going on here.

**Review by zach2good — APPROVED** [review]

**Comment by WinterSolstice8** [comment]
Squashed some commits, but code unchanged

**Review by zach2good — APPROVED** [review]

**Review by zach2good — APPROVED** [review]

**Pull request merged**
