### PR TITLE
Synth updates

### PR DESCRIPTION
**Pull request by FuzzyWereBeast**
More updates for the synth recipes.

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by FuzzyWereBeast** [comment]
is there a better way that I should be submitting this?  I didn't think it was going to "reopen" the last commit as it was already accepted and I did a "fetch upstream".  Did I miss a step?

**Comment by TeoTwawki** [comment]
It appears you messed up the `base` branch of your fork. most likely when you pull;ed LSB's base into it. Typical workflow is to leave base untouched and make new branches as needed for pull requests, which helps avoid these mishaps. 

New branches begin life as exact copies of the branches they are based on (which is why we named it base) so if your base only ever gets changes form our base it stays conflict free when you make new stuff off new branches. Sounds more complicated than it is, I promise.

**Comment by FuzzyWereBeast** [comment]
Nope.  I follow.  Again, just unfamiliar with how it works.  Thanks for your patience.  New personal branch created.  How will that work going forward after these commits are accepted?

**Comment by TeoTwawki** [comment]
> 
> 
> Nope. I follow. Again, just unfamiliar with how it works. Thanks for your patience. New personal branch created. How will that work going forward after these commits are accepted?

The idea is that your base branch woudl pull in the changes from our base branch as it gets updates. then, when you do your next pull request you would create a new working branch to edit, which begins its life as a 1:1 copy of that base so already contains those commits and the changes in them. Then there is nothing to potentially rebase and nothing to have conflicts with from your own prior work.

edit: the order this happens in matters. if you make branches while the branch they are based on is messed up, those branches will be messed up to

**Comment by FuzzyWereBeast** [comment]
Would it be wise for me to wait until this is reviewed and commited before I make any more adjustments?

**Comment by TeoTwawki** [comment]
I'm just gonna fix it for you

**Comment by FuzzyWereBeast** [comment]
Cool

**Comment by TeoTwawki** [comment]
ok I surrender. Uncle. UNCLE!

I am stubborn and do not like to give up, but Git has defeated me this day. 

I don't know your fork fork git into a state where it has an open PR that has multiple and has zero changes in its final combined diff yet the pr doesn't auto close from it. The fact it didn't auto close and that I could see changes in the previous commits had me thinking I could rebase to retrieve whatever you had that was lost but even the changes in your previous listed commits all already exist in upstream. As far as I know your fork could only get this way by a bad rebase before I started making the commit data I was trying to restore inaccessible. There's just nothing for me to restore. You will need to start over.

**Pull request closed without merging**
