### PR TITLE
[QUEST] fixes on error ticks on server console for Full Speed Ahead!

### LINKED ISSUE #3277: 🐛 [QUEST] Full speed ahead error onEffectTick (nil value)
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

GNU/Linux 

## Branch affected by issue 

`base`

## Steps to reproduce

Start Full speed ahead quest (zone in to Batalia Down)

```
[11/27/22 02:41:26:964][map][error] luautils::onEffectTick: ./scripts/quests/full_speed_ahead.lua:77: attempt to perform arithmetic on field 'BLUE_BEAM_BASE' (a nil value)
stack traceback:
        ./scripts/quests/full_speed_ahead.lua:77: in function 'tick'
        ./scripts/globals/effects/full_speed_ahead.lua:14: in function <./scripts/globals/effects/full_speed_ahead.lua:13> (OnEffectTick:2396)
```

### PR DESCRIPTION
**Pull request by kaincenteno**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

fixes https://github.com/LandSandBoat/server/issues/3277

## Steps to test these changes

!setplayervar <name> [QUEST]FullSpeedAhead 1
!zone { Batallia Downs }

### CODE REVIEW

**Comment by zach2good** [comment]
While re-populating the IDs every tick probably works, and doesn't cost that much, it's probably not a pattern we want to adopt. If you're moving a bit of code, its also a good idea to remove the old broken section.

It would be more reasonable to fix this block that you've copy/pasted from the Batallia Downs Zone Lua.

The issue is in 2 parts (in the Zone.lua):
```
local ID = require('scripts/zones/Batallia_Downs/IDs')
```

We look to be caching the IDs table, so that changes we make to it maybe aren't propagated out globally? I don't remember the rules for this exactly.

and the changes to the table happen here:
```
    -- Prepare everything for Full Speed Ahead!
    local syrillia   = zone:queryEntitiesByName("Syrillia")[1]
    local syrilliaID = syrillia:getID()

    ID.npc.SYRILLIA         = syrilliaID
    ID.npc.BLUE_BEAM_BASE   = syrilliaID + 1
    ID.npc.RAPTOR_FOOD_BASE = syrilliaID + 9

```

My suggestion would be to write everything to the table without caching it, so changing the second section to read more like:

```
    -- Prepare everything for Full Speed Ahead!
    local syrillia   = zone:queryEntitiesByName("Syrillia")[1]
    local syrilliaID = syrillia:getID()

    zones[xi.zone.BATALLIA_DOWNS].npc.SYRILLIA         = syrilliaID
    zones[xi.zone.BATALLIA_DOWNS].npc.BLUE_BEAM_BASE   = syrilliaID + 1
    zones[xi.zone.BATALLIA_DOWNS].npc.RAPTOR_FOOD_BASE = syrilliaID + 9
```

and at the top of the tick for full_speed_ahead, you could make sure the IDs are refreshed:
```
local ID = zones[xi.zone.BATALLIA_DOWNS]
```

and remove the ID declaration at the top of that file

**Comment by zach2good** [comment]
Syrillia might be a good candidate for DYNAMIC_LOOKUP now anyway

**Comment by kaincenteno** [comment]
> Syrillia might be a good candidate for DYNAMIC_LOOKUP now anyway

is there a wiki page for DYNAMIC_LOOKUP so i can guide myself for making the changes?

**Comment by kaincenteno** [comment]
nvm found a former pull request using it. thanks will look into it later.
Will create a feature request for a wiki explaining it for other people to easily find it cuz it looks like a good solution for npc IDs

**Comment by kaincenteno** [comment]
requested changes done, tested working.

**Review by zach2good — APPROVED** [review]

**Pull request merged**
