### PR TITLE
Enable/adjust more low-level desynth recipes (Spatha, Bronze Axe, Cesti, etc.)

### PR DESCRIPTION
**Pull request by RAIST5150**
These are included in the CSV we have been working from in issue #885.
just a handful today.  some results also needed adjustment

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Review by claywar — APPROVED** [review]

**Comment by TeoTwawki** [comment]
?

**Comment by RAIST5150** [comment]
Crap... different one went through... freaking auto naming of stuff with github web client. Thought this one had been committed, so deleted this auto generated patch-1 last night 

Restore branch option is still available.. guessing that will fix it?

Or I could just stitch these changes into the next batch I was holding off on until Fuzzy's open PR goes through.

**Comment by TeoTwawki** [comment]
yes

**Comment by TeoTwawki** [comment]
go ahead and restore. I'll tweak whatever has to be to get both pr in today

**Comment by RAIST5150** [comment]
Oh man... this interface.

Main page is now prompting me to compare and pull, but this page is giving me the option to reopen ths PR and comment.  This option SEEMS like the better choice.   But afraid to click anything at this point.

**Comment by TeoTwawki** [comment]
don't worry I got it from here

**Comment by TeoTwawki** [comment]
weird it would not let me "reopen and comment" when I posted earlier, but both the comment and reopening worked _separately_

**Review by TeoTwawki — APPROVED** [review]
I approve of basing desynth data on the synth data for the same item. Seems like a no brainer to me - its just synthing in reverse!

**Comment by RAIST5150** [comment]
So much potential with the web gui... so convenient to be able to do stuff anywhere--phone, tablet, anyway you can access the site.

 But the automation makes it way too easy to miss potential screwups.

#lessons_learned_the_hard_way

**Pull request merged**
