### PR TITLE
[core] Modernising ZMQ Usage

### PR DESCRIPTION
**Pull request by zach2good**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by zach2good** [comment]
Tested this by logging in and sending myself a `/tell`, which sends and receives ZMQ messages. While this was in progress, that broke. I'm fairly confident in these changes, but would appreciate someone taking them for a spin before we merge this to main.

Other things that involve ZMQ: Linkshell and party messages, formation of parties, all forms of messaging apart from say and shout etc.

**Comment by zach2good** [comment]
It appears as though we are trapped on Ubuntu 20.04 for CI (https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners), and the updated headers/libs aren't available until 21.04 onwards, so I might have to bail on this PR for now :(

**Comment by zach2good** [comment]
Problem from last night:
```
-- ZeroMQ_FOUND: TRUE
-- ZeroMQ_LIBRARY: /usr/lib/x86_64-linux-gnu/libzmq.so
-- ZeroMQ_INCLUDE_DIR: /usr/include
```

The Linux build is ignoring the checked-in modern headers for zmq that we keep, in favour of the old and outdated ones on it's system. There is a high chance that even if I can trick CMake into using the headers I want, they might not be compatible with the underlying lib that it'll link against.

**Comment by zach2good** [comment]
Hard-coding the paths seems to have worked, and the startup checks pass, but I'm still kinda sus

**Comment by zach2good** [comment]
Tested on an Ubuntu 20.04 instance:
```
zrtoogood@instance-2:~/server$ git log
commit 8dc01b64e3ba3e5667ffb0986765d78b9b56c27b (HEAD -> zmq_threadsafety, origin/zmq_threadsafety)
Author: Zach Toogood <zrtoogood@gmail.com>
Date:   Wed Mar 9 10:41:35 2022 +0200
    [cmake] Hard-code other deps INCLUDE_DIRs
```
image

**Review by claywar — APPROVED** [review]

**Pull request merged**
