### PR TITLE
[chore] Remove outer parens from additional Lua conditions

### PR DESCRIPTION
**Pull request by claywar**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
Continues effort to remove outer parentheses from Lua conditions in order to add CI rule

## Steps to test these changes
No impact should be observed

### CODE REVIEW

**Comment by TeoTwawki** [comment]
somehow, I was expecting at least another zero on the end of the total file count. I guess we've been better on manual cleanup than I thought. ***only*** 240! /s

**Review by TeoTwawki — APPROVED** [review]

**Review by Xaver-DaRed — APPROVED** [review]
a thousand less^^ GJ

**Comment by claywar** [comment]
There's still 2500 I need to fix, but doing things in chunks

**Comment by TeoTwawki** [comment]
> There's still 2500 I need to fix, but doing things in chunks

oh.  _deflates_

**Pull request merged**
