### PR TITLE
Add zone_weather for Shadowreign Northlands Zones

### PR DESCRIPTION
**Pull request by Era-Lusiphur**
Was recently noted by @Xaver-DaRed  that the northlands skies were blank. It turns out, weather for those zones were not set properly. This PR copies the existing weather of present area zones to their Shadowreign counterparts in Castle Z (S), Glacier (S), and Xarcabard (S). Throne Room (S) had weather set already.

This dumb copy method is made with the assumption of the weather being fairly close due to lack of useful data being present. It definitely corrects the problem for now. ~~At a future time, someone may be able to extract weather data from zone DATs ( @TeoTwawki mentioned it resides there) and ensure everything is 100%.~~ (See correction below in comments.)

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by Era-Lusiphur** [comment]
This corrects a few zones mentioned in #410

**Comment by TeoTwawki** [comment]
> ( @TeoTwawki mentioned it resides there)

No when you asked I said somebody hung out on retail for 2 full in game years to capture a pattern to use and that zones with perma unchaining weather may have it displaying client side but we'd still need server side to get bonuses to apply.

In all other cases, the type of weather you can get is in the dats, but we have no idea how exactly SE influences dice rolls and its all server side. I know they have in game "seasons" but have seen nothing client side to predict it with and there is def some randomness to. 

/endgrumpyuncleteo

**Comment by RAIST5150** [comment]
Goddess zones did appear to follow seasonal "rules" (between mage and melee jobs, I completed over 30 elemental weapons in retail).

Though it may not be "stock" to do so, if it were put to a vote, I would be fine with the pattern being modeled after (or even tied directly to) the present day's zone counterpart as a "band-aid" until it can be worked out differently.

**Comment by Era-Lusiphur** [comment]
Had a request from off repo to add comments to the SQL file itself.

**Review by Xaver-DaRed — APPROVED** [review]
This is better than what we have now. Further edits can be made once we have more info, if needed.

**Pull request merged**
