### PR TITLE
Re-align region IDs with what the client actually uses.

### PR DESCRIPTION
**Pull request by TeoTwawki**
(as seen in ROM/165/78.dat)

**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [ ] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
https://gist.github.com/TeoTwawki/d46e51e761a95c6dffe11f0dc999f4d1

## Steps to test these changes
Tested as far as build and boot, Xaver was going to do some further tests for me. Potential issues anywhere the Lua does a greater than or less than check on regions, and where regions equal a bit in a mask.

### CODE REVIEW

**Review by claywar — DISMISSED** [review]

**Comment by TeoTwawki** [comment]
Note: I am expecting issues related to Lua side region checks involved with bitmasks for teleports. Namely the expected bits might not be in the same expected order as the regions anymore. And I don't really know how to correct it should that prove to be the case.

**Review by zach2good — DISMISSED** [review]
LGTM, but we don't need git history like: "Edits purely to satisfy CI"

**Comment by TeoTwawki** [comment]
so far, from xavers testing:
- I broke supplies
- I broke conquest NPC selection for spawning
- I broke conquest ranking display
- I broke outpost warps
- I broke unlocking them

I had this in draft mode I dunno what switched it, putting it back till issues resolved and dismissing current aprovals.

**Comment by TeoTwawki** [comment]
well this is gonna be a fun rebase! and then I still have to actually fix it.

**Comment by TeoTwawki** [comment]
I think I'll split off the enum renaming parts, so that this deals solely with re-ordering.

**Comment by TeoTwawki** [comment]
I'm pretty much never going to have the time to return to this and fix its issues, and the rebase its needs will be straight up hellish. So no point in keeping this open.

**Pull request closed without merging**
