### PR TITLE
update item_usable.sql for scroll_of_curaga_v

### PR DESCRIPTION
**Pull request by RAIST5150**
modeling this entry as well as the new file (scripts/globals/items/scroll_of_curaga_v.lua) after existing curaga entries/files.

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by RAIST5150** [comment]
not sure if I submitted the new file for this properly (scripts/globals/items/scroll_of_curaga_v.lua).  The file is showing on the issue page I posted a while back (#846 ).  Just not sure if it is actually going to Base or not?

**Comment by TeoTwawki** [comment]
> not sure if I submitted the new file for this properly (scripts/globals/items/scroll_of_curaga_v.lua). The file is showing on the issue page I posted a while back (#846 ). Just not sure if it is actually going to Base or not?

Guessing you used the website or githubs crappy app to try and submit? coz its the same file, just with one new line added and looks fine to me here, but those methods are known to confuse the heck out of people trying to contribute.

**Review by TeoTwawki — APPROVED** [review]
looks good to me

**Comment by TeoTwawki** [comment]
Ohhh thats what you meant (I just saw #907, forgive me I'm half asleep)

thats cool we can merge both.

**Comment by RAIST5150** [comment]
yeah... the system had me all kinds of confused... hope I didn't break something.

I'm pretty good at that....

**Pull request merged**
