### PR TITLE
[lua] Make "Full Speed Ahead!" resistant to ID shifts

### PR DESCRIPTION
**Pull request by zach2good**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Removes the hard-coded IDs needed to complete FSA and replaces them with a by-name lookup of the main NPC, and then uses offsets from there to work out everything else.

## Steps to test these changes

Play, _and complete_ FSA, either naturally, or through `!minigame` menu

### CODE REVIEW

**Comment by TeoTwawki** [comment]
nice :+1:

**Review by TeoTwawki — APPROVED** [review]
I know the CI isn't done yet, but I don't see anything that could fail it here.

**Comment by zach2good** [comment]
I like this pattern of "look up the ID by name on zone init, or when you need it", but I don't like the binding. We should all talk about how we'd like it to look in the future (we're only using it in a couple of places so far, so we can be flexible)

**Comment by TeoTwawki** [comment]
> I like this pattern of "look up the ID by name on zone init, or when you need it", but I don't like the binding. We should all talk about how we'd like it to look in the future (we're only using it in a couple of places so far, so we can be flexible)

I like it for things where we keep it brief don't have to deal with any side effects of it like here. I had some concerns that per my discussion with Claywar don't apply to our repo but did in old dsp regarding long iterations to find a name.

**Pull request merged**
