### PR TITLE
Fix MariaDB manual import

### PR DESCRIPTION
**Pull request by Xaver-DaRed**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

Fix MariaDB bitching when manualy importing/executing sql files

### CODE REVIEW

**Comment by zach2good** [comment]
Huh... I thought CI would have caught these 🤔

**Comment by TeoTwawki** [comment]
and I did find replace for these when clay saw I missed one for fire_res, so i dunno how they were still there

**Review by TeoTwawki — APPROVED** [review]

**Comment by zach2good** [comment]
I thought perhaps that MariaDB was the one who was pretty relaxes, and MySQL 5.6 was the one that bitches, because we do a full import of stuff using mariadb:
```
  Full_Startup_Checks_2004:
    runs-on: ubuntu-20.04
    needs: Linux_2004_Clang11_64bit
    services:
      mysql:
        image: mariadb
        env:
          MYSQL_DATABASE: xidb
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10
    steps:

...

    - name: Verify MySQL connection from container
      run: |
        mysql -h 127.0.0.1 -uroot -proot -e "SHOW DATABASES"
    - name: Import SQL files
      run: |
        for f in sql/*.sql; do
          echo -e "Importing $f into the database..."
          mysql xidb -h 127.0.0.1 -uroot -proot < $f
        done
        mysql xidb -h 127.0.0.1 -uroot -proot -e "SHOW tables"
```

**Comment by TeoTwawki** [comment]
@zach2good I do remember there being some version stuff about it on linux systems. I thought windows complained regardless so I've been calling things good if my local file imported. Guess not tho.

**Pull request merged**
