### PR TITLE
[Fix] Rampart Status effect lowering SDT

### PR DESCRIPTION
**Pull request by Aeltorian**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Fixes Rampart so it actually does gain the SDT buff. 

## Steps to test these changes

Removed the - value to the power which negated a buff. 
Tested on priv server on several mobs for a few hours to make sure SDT was working.

### CODE REVIEW

**Review by WinterSolstice8 — APPROVED** [review]
thanks

**Comment by Xaver-DaRed** [comment]
This doesnt fix rampart at all, I'm sorry to say. physical and magical SDT cant use the same power, because the modifiers use different scales entirely

**Comment by Aeltorian** [comment]
When I tested without the changes, rampart did no changes to damage taken. When I took out the -, I started to see damage reduction whenever rampart was active.

**Comment by TeoTwawki** [comment]
> When I tested without the changes, rampart did no changes to damage taken. When I took out the -, I started to see damage reduction whenever rampart was active.

for one damage type. he's telling you that 2 diff types are mistakenly together when they aren't handled the same. the script will need some reworking because if its what he says they shouldn't be in the same loop together.


Or we update mods to be same scaling.

**Comment by TeoTwawki** [comment]
Or we update mods to be same scaling.

**Comment by Aeltorian** [comment]
Well, I didn't touch the formula that the previous writer wrote up. So in a little detail, how does it work differently between the two types? I mean, it's been like this for around a year and someone who actively uses pld would notice it not working... 

As far as I know, it's a solid 25% damage reduction for 30-45 seconds or however, the rest of the SDT formula goes.

**Comment by TeoTwawki** [comment]
appears its not even supposed to be doing these multiple SDT mods at all, and is supposed to use standard dmg taken instead. so the whole thing is wrong in that case.

**Comment by TeoTwawki** [comment]
> Well, I didn't touch the formula that the previous writer wrote up.

we're aware you didn't do it, and that doesn't matter.

**Comment by Aeltorian** [comment]
> appears its not even supposed to be doing these multiple SDT mods at all, and is supposed to use standard dmg taken instead. so the whole thing is wrong in that case.

What does SDT stand for? I've heard multiple things since last night when this was brought to my attention.

**Comment by TeoTwawki** [comment]
>  it's been like this for around a year and someone who actively uses pld would notice it not working...

if you are going to contribute for long my friend, prepare to be shocked at the frequency with which we (not you, but the main devs) are held responsible for things nobody ever reported to the tracker and we didn't realize for long stretched of time

**Comment by TeoTwawki** [comment]
> > appears its not even supposed to be doing these multiple SDT mods at all, and is supposed to use standard dmg taken instead. so the whole thing is wrong in that case.
> 
> What does SDT stand for? I've heard multiple things since last night when this was brought to my attention.

Specific damage taken. like _specifically_ fire damage is an example. the term may be used differently in some contexts on wikis (notably on monster correlation)  but this is how we used it.

**Comment by Aeltorian** [comment]
> > it's been like this for around a year and someone who actively uses pld would notice it not working...
> 
> if you are going to contribute for long my friend, prepare to be shocked at the frequency with which we (not you, but the main devs) are held responsible for things nobody ever reported to the tracker and we didn't realize for long stretched of time

My apologies. I don't mean it in a bad way. I try to take bit of pride in helping others any way I can. I'm a newbie around these parts but I've been away from coding for too long.

What do you mean by scaling?

**Comment by TeoTwawki** [comment]
> > > it's been like this for around a year and someone who actively uses pld would notice it not working...
> > 
> > 
> > if you are going to contribute for long my friend, prepare to be shocked at the frequency with which we (not you, but the main devs) are held responsible for things nobody ever reported to the tracker and we didn't realize for long stretched of time
> 
> My apologies. I don't mean it in a bad way. I try to take bit of pride in helping others any way I can. I'm a newbie around these parts but I've been away from coding for too long.
> 
> What do you mean by scaling?

oh I'm just letting you know. I still occasionally find something that's been broken for like 6yrs and people act like everyone knew and we ignored it and then I am all BUG REPORT WHERE? and hear crickets lol

scaling is like, one modifier is handled 0-100 treated like a percent and another will be 0-10,000 where 254 will be 2.54% to get 2 more decimal places of precision (modifier code doesn't support decimals in the values you see, so we have to pad it)

a lot of mods come on different scales. haste is one of those extra precise ones.

**Comment by Aeltorian** [comment]
> > > > it's been like this for around a year and someone who actively uses pld would notice it not working...
> > > 
> > > 
> > > if you are going to contribute for long my friend, prepare to be shocked at the frequency with which we (not you, but the main devs) are held responsible for things nobody ever reported to the tracker and we didn't realize for long stretched of time
> > 
> > 
> > My apologies. I don't mean it in a bad way. I try to take bit of pride in helping others any way I can. I'm a newbie around these parts but I've been away from coding for too long.
> > What do you mean by scaling?
> 
> oh I'm just letting you know. I still occasionally find something that's been broken for like 6yrs and people act like everyone knew and we ignored it and then I am all BUG REPORT WHERE? and hear crickets lol
> 
> scaling is like, one modifier is handled 0-100 treated like a percent and another will be 0-10,000 where 254 will be 2.54% to get 2 more decimal places of precision (modifier code doesn't support decimals in the values you see, so we have to pad it)
> 
> a lot of mods come on different scales. haste is one of those extra precise ones.

Ooo, that's right. I think I understand what you're talking about. I ran across that when I was looking a possible bug with Shell's MDT not working. Noticed that it worked from a different scale than just pure mdt removed kinda like how protect is.

**Comment by gweivyth** [comment]
> I still occasionally find something that's been broken for like 6yrs and people act like everyone knew and we ignored it and then I am all BUG REPORT WHERE? and hear crickets lol

This may be the most accurate thing I've ever seen. 😭

> Ooo, that's right. I think I understand what you're talking about. I ran across that when I was looking a possible bug with Shell's MDT not working. Noticed that it worked from a different scale than just pure mdt removed kinda like how protect is.

Yeah the sources aren't amazingly clear about this either which doesn't help during the research phase. There's also been a lot of wild theories over the years that were touted as facts. One of the more stand-out ones is that all of these sources are multiplicative, but that makes no logical sense.

**Comment by TeoTwawki** [comment]
> Yeah the sources aren't amazingly clear about this either which doesn't help during the research phase. There's also been a lot of wild theories over the years that were touted as facts. One of the more stand-out ones is that all of these sources are multiplicative, but that makes no logical sense.

Thats is why going onto retail and collecting a ton of data is king, `#shitWikiSays`

**Comment by Aeltorian** [comment]
Man. The rose colored glasses are definitely crumbling like an AoE wiping a full set of Utsusemi.

**Comment by Aeltorian** [comment]
Would it be prudent if I could modify the current array here from to sdt, dark sdt so it at least takes care of the magical sdt and then work on adding the physical sdt in a later patch? Because as of right now, rampart doesn't give any sdt and being that most dmg is magical in endgame, could be useful for the time being. 

Or should I close this PR and rewrite to make it work the way where physical sdt is scaled properly alongside magical sdt but aren't exactly together in the same calculation.

**Review by Xaver-DaRed — APPROVED** [review]

**Pull request merged**
