### PR TITLE
Fix for Chocobo Jig II targeting issue

### PR DESCRIPTION
**Pull request by SirGouki**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Fixes Chocobo Jig II not targeting party members, only the user and their trusts by changing the range from 0.0f to 10.0f.
This value was obtained using the in client AoE ring that shows up when trying to use Chocobo Jig II.

## Steps to test these changes

Prior to the change:
Be DNC level 70+ and the party leader.
Have a trust and a party member, with the party member not at the same exact location as the leader.
Use Chocobo Jig II:
- Party Leader and trust will gain the effect
- Party member player will NOT gain the effect.
After the change:
- Party Leader, trust, and party member player will all gain the effect.

### CODE REVIEW

**Comment by SirGouki** [comment]
PR is trying to include where I fixed the white space in my CPP from a previous PR, not sure why because that should have already been merged from the previous PR.  I'm going to try to resolve it.

**Comment by TeoTwawki** [comment]
rebase, force push onto same branch name and it will auto update the pr.

**Comment by SirGouki** [comment]
I dropped my fork and redid it, cause I had a different issue.  Is that going to effect that?

**Comment by TeoTwawki** [comment]
~~If you do a force push to same branch name, I can still reopen this and it will show that content~~ not if the entire fork is deleted

**Comment by SirGouki** [comment]
it's pushed

**Comment by TeoTwawki** [comment]
god dammit shithub.

**Pull request closed without merging**
