### PR TITLE
Remove Dia spells attribute and remove duplicate params.

### PR DESCRIPTION
**Pull request by Xaver-DaRed**
Removed all 6 Dia spells attribute. 
Source: https://translate.google.com/translate?hl=en&sl=ja&tl=en&u=http%3A%2F%2Fwiki.ffo.jp%2Fhtml%2F338.html

Also removed from all 6 scripts 2 duplicate params, becouse why not.
It hasn't broken anything from my testing.

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to Topaz Next's [Limited Contributor License Agreement](https://github.com/DerpyProjectGroup/topaz/blob/release/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/DerpyProjectGroup/topaz/blob/release/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by cocosolos** [comment]
I'm not sure how spell damage and resistance is calculated, but if you take the relevant section from that wiki and translate it through google (rather than having google translate the whole page) you get:
```
初撃ダメージはMNDによるダメージ変動はなく、魔法攻撃力アップのジョブ特性と曜日・天候効果、属性杖によってのみ変動する。
```
->
```
The initial damage does not change due to MND, but changes only depending on the job characteristics of increasing magic attack power, the day of the week / weather effect, and the attribute wand.
```

**Comment by Xaver-DaRed** [comment]
lol, thats hilarious... I guess I can remove the whole MND atribute and diff so it only takes into account the magic attack and element...
Gonna need more testing

**Comment by TeoTwawki** [comment]
I just assumed it was unused but defined for some other reason (I dunno how else we missed INT for so many years)

and on teir1 dia its being clamped to min1 max2 before resist anyway which is pretty lolsy if it ever factored into dmg,

(on retail you -can- land for zero, but that is presumably from resistance)

**Comment by Xaver-DaRed** [comment]
its clamped first and then resistance is applied, wich can result in 0
from what i've seen in magic.lua, i could just set diff to 0 and remove the atribute altoguether

**Comment by TeoTwawki** [comment]
> its clamped first and then resistance is applied, wich can result in 0

I saw that, and I was surmising that is likely how I get the zero's on retail

> from what i've seen in magic.lua, i could just set diff to 0 and remove the atribute altoguether

:+1:

**Comment by Xaver-DaRed** [comment]
Re-tested with last commit and it seemed to work. Or at least, it didn't explode.
param.diff cannot be removed, as applyResistanceEffect requires either a diff OR it calculates one itself, wich requires an attribute (MND or INT)

**Pull request merged**
