### PR TITLE
[IDs] Update messages documentation with missing messages

### PR DESCRIPTION
**Pull request by Schaedelschaden**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Adds missing messages to documentation/message.log.

### CODE REVIEW

**Comment by Schaedelschaden** [comment]
Not sure if all of the unassigned messages need to go into msg.lua, but at the very least the documentation can be updated and converted from a .log file to a .txt

**Comment by TeoTwawki** [comment]
> Not sure if all of the unassigned messages need to go into msg.lua, but at the very least the documentation can be updated and converted from a .log file to a .txt

So what we've done is to add them to the lua/c++ enums on an add needed basis or as we expect to near future use them. doesn't mean we'd necessarily reject additions is properly named though. And co updates always good.

**Comment by TeoTwawki** [comment]
it looks like you renamed a file outside of git (like renamed in windows) and so it's committed a delete of the file and add of a new file of the same content. that breaks the history record. Also adding to what I said about adding to the lua / enums there's not much point of basically just copying the entire document into it as a gigantic series of comments - essentially an unusable form. Let's leave that to the doc.

**Review by claywar — APPROVED** [review]

**Comment by Schaedelschaden** [comment]
Thanks for the clarification Teo!

**Review by Xaver-DaRed — APPROVED** [review]

**Pull request merged**
