### PR TITLE
[SQL] Add some missing item_equipment and item_weapon entries. Fix some incorrect MIDs

### PR DESCRIPTION
**Pull request by helixhamin**
With corrections to item_basic.sql
As per the previous PR request, single space between EOL and comment.

**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
Adds missing items to item_equipment and item_weapon sql.

## Steps to test these changes

As GM, use command !additem itemid 1
See if the items spawn in inventory (Make sure inventory is not full when attempting).
If yes, make sure they can be equipped. If it is a weapon, make sure it changes the character damage value.

### CODE REVIEW

**Comment by helixhamin** [comment]
As per request in https://github.com/LandSandBoat/server/pull/4177 I have made sure any comments are only 1 space after the end of line statement in the SQL, and to make the PR smaller, I have not included any of the item_mods, item_pet_mods or item_latents. I will submit those in separate PR requests.

**Comment by TeoTwawki** [comment]
when you do mods, do them in multiple small batches if its a lot of rows.

**Comment by helixhamin** [comment]
> when you do mods, do them in multiple small batches if its a lot of rows.

Yep, that is my intention. Debating doing them by job, or just by number order.

**Comment by zach2good** [comment]
Can we get a more descriptive title than `Adjust only item_equipment.sql and item_weapon.sql`? Whats being adjusted? Are things being added? Are flags being changed? Are things from more modern retail being added?

**Comment by zach2good** [comment]
These PR titles are automatically pulled into our patch notes, so please make them descriptive of whats being changed

**Comment by zach2good** [comment]
Patch notes: https://landsandboat.github.io/server/changelog

**Comment by helixhamin** [comment]
> These PR titles are automatically pulled into our patch notes, so please make them descriptive of whats being changed

Okay, adjusted.

**Review by Xaver-DaRed — APPROVED** [review]

**Comment by Xaver-DaRed** [comment]
I think Zach was refering to the actual commit title, not the PR title.

You would need to amend the commit title and force push, iirc

**Pull request merged**
