### PR TITLE
Run CPP and SQL files in modules during CIs.

### PR DESCRIPTION
**Pull request by clanofartisans**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Attempting to resolve the issues Zach outlined in https://github.com/LandSandBoat/server/issues/5347 ~ CPP and SQL module files aren't being run for `Full_Startup_Checks_Linux`, `MultiInstance_Startup_Checks_Linux`, or `Full_Startup_Checks_Windows`.

## Steps to test these changes

Run CIs.

### CODE REVIEW

**Comment by clanofartisans** [comment]
It looks like CPP and SQL modules were all run in the relevant places:

## Linux_Clang15_64bit
**CPP**: https://github.com/LandSandBoat/server/actions/runs/11131756240/job/30934153504?pr=6296#step:6:614

## Windows_64bit_Debug
**CPP**: https://github.com/LandSandBoat/server/actions/runs/11131756240/job/30934154788?pr=6296#step:6:523

## Full_Startup_Checks_Linux
**SQL**: https://github.com/LandSandBoat/server/actions/runs/11131756240/job/30934726752?pr=6296#step:7:134

## MultiInstance_Startup_Checks_Linux
**SQL**: https://github.com/LandSandBoat/server/actions/runs/11131756240/job/30934727182?pr=6296#step:7:134

## Full_Startup_Checks_Windows
**SQL**: https://github.com/LandSandBoat/server/actions/runs/11131756240/job/30934500041?pr=6296#step:7:134

**Comment by clanofartisans** [comment]
This is to resolve https://github.com/LandSandBoat/server/issues/5347

**Comment by zach2good** [comment]
This isn't quite what I had in mind. `Linux_Clang15_64bit` is the base build on Linux, using Clang15. Modules as a concept are additions to the base software, and so shouldn't be a part of the base build.

I reckon what would make sense would be to give modules on both Linux and Windows their own jobs, which includes configuration (setting init.txt, dbtool, etc.), build, and then running everything. To speed these up, you can make them rely on the base versions of their builds: Linux_Clang15_64bit -> Linux_Clang15_64bit_Modules, and a Windows equivalent, etc.

and make sure the base builds cache their build folders, like I've started doing here:
https://github.com/LandSandBoat/server/pull/6275/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721

You can make different jobs run sequentially like this:
```
Full_Startup_Checks_Windows:
    runs-on: windows-2022
    needs: Windows_64bit_Debug
```

The general flow will be (Linux example):
- The regular linux build configures and builds itself.
- The regular linux build caches its build folder
- The regular linux build caches its build artifacts (exes)
- The regular linux startup checks pull down the caches artifacts (exes) and run stuff
- The modules linux job pulls down the cached build folder first
- The modules linux job changes the init.txt file, and runs dbtool, etc.
- The modules linux job reconfigures cmake, and rebuilds - it should be faster because of the incremental build thanks to the cached build folder
- the modules linux job then goes on to do startup checks within the same job, etc.

**Comment by clanofartisans** [comment]
> This isn't quite what I had in mind. `Linux_Clang15_64bit` is the base build on Linux, using Clang15. Modules as a concept are additions to the base software, and so shouldn't be a part of the base build.
> 
> I reckon what would make sense would be to give modules on both Linux and Windows their own jobs, which includes configuration (setting init.txt, dbtool, etc.), build, and then running everything. To speed these up, you can make them rely on the base versions of their builds: Linux_Clang15_64bit -> Linux_Clang15_64bit_Modules, and a Windows equivalent, etc.
> 
> and make sure the base builds cache their build folders, like I've started doing here: https://github.com/LandSandBoat/server/pull/6275/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721
> 
> You can make different jobs run sequentially like this:
> 
> ```
> Full_Startup_Checks_Windows:
>     runs-on: windows-2022
>     needs: Windows_64bit_Debug
> ```
> 
> The general flow will be (Linux example):
> 
> * The regular linux build configures and builds itself.
> * The regular linux build caches its build folder
> * The regular linux build caches its build artifacts (exes)
> * The regular linux startup checks pull down the caches artifacts (exes) and run stuff
> * The modules linux job pulls down the cached build folder first
> * The modules linux job changes the init.txt file, and runs dbtool, etc.
> * The modules linux job reconfigures cmake, and rebuilds - it should be faster because of the incremental build thanks to the cached build folder
> * the modules linux job then goes on to do startup checks within the same job, etc.

Makes sense! I'll redo them as separate jobs.

**Comment by zach2good** [comment]
Adding this to CI here: https://github.com/LandSandBoat/server/pull/6573

**Pull request closed without merging**
