### PR TITLE
[Login] Add IP Limit Exceptions

### PR DESCRIPTION
**Pull request by The-Aerec**
Co-Authored-By: Damarus <leblanc.jlj@gmail.com>

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Adds Exceptions to the IP Login Limit via dates: (Allows for Temporary time gated vs permanent)

## Steps to test these changes
Login on multi accounts.

### CODE REVIEW

**Comment by The-Aerec** [comment]
This is a draft PR for collaboration, this was my idea on how to proceed and my 'best attempt' (I am not a cpp guru obviously, and i'm very much still learning.)

Server owner sets a date in exceptions: yyyymmddhhmmss format. (We could even change the sql data type to a char or varchar type and make the date format more readable and just substr the '-' and ':' out of: yyyy-mm-dd-hh:mm:ss)

We convert to epoch and check differences between epoch and exception date and if the epoch is after the exception date then well the user can't login if there is a session already on their IP.

Owner can set date years in the future for a more permanent exception, or an actual date for a temporary one.

Please rip this apart... I suck at cpp.

**Comment by CatsEyeXI** [comment]
just stopping by to say i fully support this <3

**Comment by zach2good** [comment]
> Server owner sets a date in exceptions: yyyymmddhhmmss format. (We could even change the sql data type to a char or varchar type and make the date format more readable and just substr the '-' and ':' out of: yyyy-mm-dd-hh:mm:ss)

Why not jus use a datetime or timestamp type in SQL?
```sql
  `exception_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
```

image

So this is an infinite exception, rather than "you can have this custom limit"?

If you're going to modify an existing table, which will have existing user data in it, you'll need to provide a migration (look in tools). It would be easier for you, and anyone else if you just create a whole new table, then it'll just appear as part of a regular update without needing a migration (I think?):

 ```
account_ip_exceptions.sql

id |  login_limit | exception_expires | notes
```

Then you can just query using the account number, or add it to nearby queries.

You can get away with not using whole time structures, and just use unix epoch:
https://database.guide/unix_timestamp-examples-mysql/#:~:text=In%20MySQL%2C%20you%20can%20use,or%20another%20specified%20date%2Ftime.

We use that here:
```cpp
int32 CCharEntity::GetTimeCreated()
{
    TracyZoneScoped;
    const char* fmtQuery = "SELECT UNIX_TIMESTAMP(timecreated) FROM chars WHERE charid = %u;";

    int32 ret = sql->Query(fmtQuery, id);

    if (ret != SQL_ERROR && sql->NumRows() != 0 && sql->NextRow() == SQL_SUCCESS)
    {
        return sql->GetIntData(0);
    }

    return 0;
}
```

Here is the modern cpp way of getting that same epoch to compare with:
```cpp
int64_t timestamp = duration_cast<milliseconds>(system_clock::now().time_since_epoch()).count();
```

https://godbolt.org/z/5PTjx5Ejc

**Comment by zach2good** [comment]
Adding on to this, you WILL need a migration, but it'll be very simple.

Since you're probably going to add the exception list to the protected tables list.

if exceptions table doesn't exist, create it.

**Comment by claywar** [comment]
> If you're going to modify an existing table, which will have existing user data in it, you'll need to provide a migration (look in tools). It would be easier for you, and anyone else if you just create a whole new table, then it'll just appear as part of a regular update without needing a migration (I think?):

Since it will need to be set up as a protected table, will still need a migration, since those aren't touched by the tool except for initial db setup

**Review by zach2good — APPROVED** [review]

**Comment by zach2good** [comment]
Don't merge yet, mroe changes incoming

**Comment by The-Aerec** [comment]
> Don't merge yet, mroe changes incoming

Ready to go: Changed id -> accid to be in line with other sql files when it comes to referring to an Account ID

**Review by zach2good — APPROVED** [review]

**Pull request merged**
