### PR TITLE
Add H2H weapon mods

### PR DESCRIPTION
**Pull request by helixhamin**
Update some that were in error.
Added a couple missing ones.

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by helixhamin** [comment]
Sorry, forgot:

> Cite your sources. This can be comments in your code, or your commit messages. Pull Request descriptions and comments will get lost over time.

My sources are the item text as seen on ffxiah, with some checks for issues between both ffxicyclopedia and bg-wiki, but I relied on the information listed on the items information for my inclusions.

**Comment by TeoTwawki** [comment]
you got conflicts. the add effect branch finally merged to base.

**Comment by helixhamin** [comment]
> you got conflicts. the add effect branch finally merged to base.

Yes, because I resolved those conflicts to send to your branch (the modid 160-164 that you had 2 less 0s on).
I will try to do something sometime, but it will sit as is for a while, as I will be busy with other things.

**Comment by TeoTwawki** [comment]
> > you got conflicts. the add effect branch finally merged to base.
> 
> Yes, because I resolved those conflicts to send to your branch (the modid 160-164 that you had 2 less 0s on).
> I will try to do something sometime, but it will sit as is for a while, as I will be busy with other things.

yes but the only reason to send to the effect branch was..for effect things which are now removed lol. So I switched it back now that its merged. Sorry for the hassle!

**Comment by helixhamin** [comment]
Closing this, as it is a pain to go through and edit so many conflicts. I will release a new PR on the updated base.

**Pull request closed without merging**
