### PR TITLE
[LUA] Update Blood Rage & Warcry ability use messages

### LINKED ISSUE #2786: 🐛 [WAR] [JA] Blood Rage is casted several times when used
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## OS / platform the server is running (if known)

GNU/Linux

`base`

## Steps to reproduce

get 1000 TP
use blood rage
see several text lines
image

## Expected behavior

get 1000 TP
use blood rage
see only one text line

### PR DESCRIPTION
**Pull request by Schaedelschaden**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [X] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [X] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Closes #2786
Updates abilities.sql with the correct base messages for Blood Rage and Warcry.
Updates job_utils/warrior.lua Blood Rage and Warcry with correct message when targeting party members.
Updates abilities/blood_rage.lua and abilities/warcry.lua onUseAbility functions with returns so the message passes through.
Adds two messages (JA_GAIN_EFFECT & JA_ATK_ENHANCED) to globals/msg.lua.
Updates job_utils/warrior.lua formatting.

## Retail Captures

pol_anxxo9OWSw

pol_g05ksCMTvn

pol_qzcEfIbtGb

pol_xcdS1plvvq

## Steps to test these changes

1. Upload changes to your server.
2. Load the server.
3. Use the !changejob WAR 99 command.
4. Summon trusts or log in multiple characters.
5. Use Blood Rage and Warcry to confirm their messages match the retail captures.

### CODE REVIEW

**Review by WinterSolstice8 — APPROVED** [review]
LGTM

**Comment by WinterSolstice8** [comment]
p.s. if you're interested in more message fixes apparently all the aoe Circle ability messages are off too as per https://github.com/LandSandBoat/server/issues/2400 as well as maybe rampart, mantra, killer instinct

**Comment by Schaedelschaden** [comment]
Sweet, I can definitely take a look. I think there are quite a few AoE messages out there that changed and need to be updated. Crummy part is it seems like they have individual overrides that will have to be applied to the abilities like they were here.

**Comment by WinterSolstice8** [comment]
> Crummy part is it seems like they have individual overrides that will have to be applied to the abilities like they were here.

Yeah it's a bummer. Sometimes there are "No Effect" messages based on other buffs. Check Liement/Vallation/Valiance in rune fencer's job helper for some oddities like that.

thankfully the vast majority of buffs dont have corner cases.

**Pull request merged**
