### PR TITLE
Fix Prelude Cast Time

### PR DESCRIPTION
**Pull request by ririkaimikania**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [ ] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Changes the cast time from 8 seconds to 4 seconds to reflect actual. 

The fandomwiki and bg-wiki history shows the incorrect cast time of 8s. The cast time were incorrectly copied because 8s is the default for bard songs for party buffs. Single target buffs were always 4s such as single target etude are 4s. 

The links I provided below are from the 2004 brady guide that has the correct information. Sourced from huntin4games's youtube channel. 

https://youtu.be/RLulY8zx5D8?t=374

I have also provided screenshot and highlights of hunter's prelude and archer's prelude.

https://imgur.com/0wMNYcz
https://imgur.com/4f3nZvX

Screenshot 2023-07-27 at 10 05 44 AM

Screenshot 2023-07-27 at 10 05 26 AM

## Steps to test these changes

Use bard and play hunter's prelude and archer's prelude on self.

### CODE REVIEW

**Comment by TeoTwawki** [comment]
must... resist urge to... make fun of brady guide...!

AHEM. thank you for your PR. 😄 but I just went on retail changed to bard and watched it take 8 seconds to cast, with no gear on

**Comment by ririkaimikania** [comment]
Wow really? 8s 

I guess that's the end of that then.

**Comment by TeoTwawki** [comment]
maybe it was different in the past. 2 decades is a long time for stuff to change in.

**Comment by ririkaimikania** [comment]
Oh right. SE kept messing with prelude. It used to be AOE for 8s, then later they changed it to single target for 4s, and now it's back to AOE for 8s.

**Comment by ririkaimikania** [comment]
What I'm trying to fix it's actually ASB's prelude issue. It's single target and 8s. It's killing me.

**Comment by ririkaimikania** [comment]
Close because this isn't an issue for LSB's prelude cast time.

**Comment by TeoTwawki** [comment]
> What I'm trying to fix it's actually ASB's prelude issue. It's single target and 8s. It's killing me.

in that case, in suggest pr'ing to them to move their changes out to a module that covers both the aoe/single-target-ness and the cast time

**Comment by ririkaimikania** [comment]
Yep. Thanks that's exactly what I'll do.

**Pull request closed without merging**
