### PR TITLE
[login] Add Task Manager ticks

### PR DESCRIPTION
**Pull request by WinterSolstice8**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
Adds task manager ticks to Login

Related: #6518

## Steps to test these changes

Wait a while after running login and hopefully see `(C++) Pinging database to keep connection alive` eventually

### CODE REVIEW

**Review by zach2good — APPROVED** [review]

**Comment by StabbyCutyou** [comment]
Hello, unwarranted question from someone just trying to learn the codebase:

if ping_connection calls getState() https://github.com/LandSandBoat/server/blob/724226264029861686b61108af450eb8e5f415c4/src/common/taskmgr.cpp#L41

And getState() adds a task which calls ping_connection with a type of CTaskMgr::TASK_INTERVAL
https://github.com/LandSandBoat/server/blob/724226264029861686b61108af450eb8e5f415c4/src/common/database.cpp#L136

And CTaskMgr::TASK_INTERVAL type Tasks get re-enqueued after a run of DoTimer()
https://github.com/LandSandBoat/server/blob/724226264029861686b61108af450eb8e5f415c4/src/common/taskmgr.cpp#L117-L120

Won't this slowly build up a never ending list of Tasks to ping the DB, as ping_connection keeps calling getState() which keeps adding a new task to call ping_connection, and that task is pushed back onto the TaskManager stack after each run?

Apologies if i'm just mis-reading the code and causing a distraction.

**Comment by WinterSolstice8** [comment]
It returns early here https://github.com/LandSandBoat/server/blob/724226264029861686b61108af450eb8e5f415c4/src/common/database.cpp#L90

**Comment by WinterSolstice8** [comment]
Just went to double check ,and after an hourish the debugger thinks there's only one task here: 
image

**Comment by WinterSolstice8** [comment]
image
Finally triggered

**Comment by StabbyCutyou** [comment]
Womp womp

Apologies! Appreciate you taking the time to explain it!

**Review by Xaver-DaRed — APPROVED** [review]

**Comment by zach2good** [comment]
If this works great, but inside of getState is meant to be self-repairing, so then it doesn't work :(

**Comment by StabbyCutyou** [comment]
I noticed that as well but I assumed lack of familiarity with the codebase meant I was missing something more obvious.

Is it possible that isvalid() and reconnect() are implemented in a way where they aren't aware of the server having closed the connection, and are returning true (and thus, the broken connection) even though they haven't actually validated / properly reconnected? Ie: they're designed to repair the client in the event of a state that the client is aware of / caused (which in this case, they wouldn't know that the server timed out the connection)?

I poked around the driver itself but I'm supremely out of my element with cpp, so figured I'd raise it as a possibility. For all I know, I'm not even looking at the right thing:

https://github.com/ericcurtin/mariadb-connector-cpp/blob/60a87352d2edfad375eb60eafd6d52ba84eb9404/driver/mysql_connection.cpp#L1550

And

https://github.com/ericcurtin/mariadb-connector-cpp/blob/60a87352d2edfad375eb60eafd6d52ba84eb9404/driver/mysql_connection.cpp#L1590

Substantially lowering the idle timeout on Maria's side might be one way to validate this more quickly. If I didn't have to work through the weekend, I'd be happy to donate time trying to help test a fix here.

**Comment by WinterSolstice8** [comment]
Jury's still out on if it fixed anything

I never had the problem on this machine, this is simply adding task manager ticks that happens to use sql ping, but I do agree that the "self healing" bit does not seem to work for others

**Comment by StabbyCutyou** [comment]
The original problem, as I experienced it, would only happen in specific circumstances - namely, the connection would need to be closed on the remote db server without the client being aware.

In my example, it happens consistently due to idleness (i set my server up, and have been playing around with it sporadically. I've been reading the code a lot more than I've actually used the emulator tbh, so it's easy to repro for me, and my db and app servers are not the same machines, so I'm not going over the local loopback).

If your server is highly trafficked, you might literally never experience it.

**Comment by zach2good** [comment]
Since login, search, and world server are all refactors to use the new `db` namespace, I'd like to have this PR go out into the wild for a few weeks and see if it does the reconnection logic without periodic pings: https://github.com/LandSandBoat/server/pull/6568

If we get back reports that it doesn't work, then this PR can come in on top of it

**Comment by StabbyCutyou** [comment]
I can do an update tonight and let the server run for a few days and then see if the error recurs.

Appreciate the attention on the issue!

**Comment by zach2good** [comment]
This is another db improvement, which should solidify the self-healing of connections if they break: https://github.com/LandSandBoat/server/pull/6571

**Comment by WinterSolstice8** [comment]
I don't think this is necessary anymore

**Pull request closed without merging**
