### PR TITLE
Droplist audit for The Boyahda Tree issue #975

### PR DESCRIPTION
**Pull request by hooksta4**
First pass, would like an extra set of eyes. Did not mess with NM's. Updated a few droprates consistent with ffxidb. Added Old_goobbue ID as it did not have a dropID.

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by Xaver-DaRed** [comment]
remember to always follow this chart when adding items to mobs.
imagen

I'll go through the rates in a few

**Comment by TeoTwawki** [comment]
when editing drop lists be ware that other mobs may use the same drop ID, and simply editing the list to make it correct for the mob you are looking at can make it wrong for another mob 
(like mandragora that are dropping leach items, if you replace the items you may then have leaches dropping madragora items instead). 
Such cases will require the drop ID in the mob_groups table to be changed, possibly with a whole new drop ID being created first.

So I hope you actually checked what mobs used the IDs you are editing items in, and if you didn't you'd better.

**Comment by hooksta4** [comment]
Fair point.

**Comment by hooksta4** [comment]
> when editing drop lists be ware that other mobs may use the same drop ID, and simply editing the list to make it correct for the mob you are looking at can make it wrong for another mob (like mandragora that are dropping leach items, if you replace the items you may then have leaches dropping madragora items instead). Such cases will require the drop ID in the mob_groups table to be changed, possibly with a whole new drop ID being created first.
> 
> So I hope you actually checked what mobs used the IDs you are editing items in, and if you didn't you'd better.

Indeed, the korrigan is in fact linked in with leeches, so I will need to redo it all over again. Way to kill this?

**Comment by TeoTwawki** [comment]
> > when editing drop lists be ware that other mobs may use the same drop ID, and simply editing the list to make it correct for the mob you are looking at can make it wrong for another mob (like mandragora that are dropping leach items, if you replace the items you may then have leaches dropping madragora items instead). Such cases will require the drop ID in the mob_groups table to be changed, possibly with a whole new drop ID being created first.
> > So I hope you actually checked what mobs used the IDs you are editing items in, and if you didn't you'd better.
> 
> Indeed, the korrigan is in fact linked in with leeches, so I will need to redo it all over again. Way to kill this?

find the drop id each should actually have or create a new one if an existing one doesn't match what the drop

**Comment by hooksta4** [comment]
in this instance, will have to create a new one for korrigans as they are the only ones that drop the 4 leaf korrigan bud

**Comment by TeoTwawki** [comment]
> in this instance, will have to create a new one for korrigans as they are the only ones that drop the 4 leaf korrigan bud

possibly a duplicate of the leeches droplist overwrote it, deleting or korrigan buds out of existence. It looked to me like someone tried to shift drop ID's to close a gap and mistakenly replaced a bunch.

**Comment by hooksta4** [comment]
Is there a way to reject/close this one? I feel it would be easier for me to start over because I made all those changes..?

**Comment by TeoTwawki** [comment]
> Is there a way to reject/close this one? I feel it would be easier for me to start over because I made all those changes..?

Can just force push over it to replace it. but the close button is at the bottom. There is also the option to convert it to a draft at the right side where the reviewer area is on this page.

**Comment by hooksta4** [comment]
I just don't want it being in narnia forever.

**Pull request closed without merging**
