### PR TITLE
[lua] Implement Dynamis-Jeuno Lottery NMs

### PR DESCRIPTION
**Pull request by EpicTaru**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Implements the Lottery NMs for Dynamis-Jeuno (Zone 188).
- Uses Lottery PH information from https://github.com/LandSandBoat/server/pull/1502, specifically the information regarding the specific PH MobIDs found in the IDs.lua file.
    - This PR **DOES NOT** include the group spawning or the timed spawn NM that were also found in PR#1502, it only uses the PH MobID information found in that PR.
- Adds PH code to the .lua files for the PH mobs.
    - The lottery chance percentage (**10**%) and cooldown time (20 minutes, a.k.a. **1200** seconds) values in these .lua files are **_ASSUMED_** to be the same values as those for **Dynamis-Beaucedine** and **Dynamis-Xarcabard**.  
        - Way back in https://github.com/DarkstarProject/darkstar/pull/6190 is when the lottery chance percentage and cooldown time values were added to Dynamis-Beaucedine and Dynamis-Xarcabard. 
    
**Final verification of the true and actual lottery chance percentage and cooldown time values still need to be found for all three of the above zones, as commented in the .lua files for all of the above PH mobs!!!** 

``/soapboxmode on``

This PR is being done to allow for LSB private servers to be able to fight some of the NMs that drop the item used to pop the zone boss, obtain the zone clear KI, and be able to move on to the Northlands Dynamis zones.  

Without the implementation of these NMs (both these lottery NMs and the timed respawn NM mobs (which will be implemented in a seperate PR later)), LSB private servers (and any private server that is/was based on TPZ/TPZ-N/the ending days of DSP) had to use custom methods to set players as having cleared this zone so they are not stuck at Dynamis-Jeuno or force their players to be stuck at Dynamis-Jeuno, staring at the stars, dreaming of the armor and items that could not be obtained from the Northlands Dynamis zones.

``/soapboxmode off``

## Steps to test these changes

Be a GM with ``!godmode`` enabled for both of the below scenarios.

Before pulling this PR down:
- Dream dreams that have been dreamt for years on years of Northlands Dynamis items that were just dreams.
- Occasionally zone into Dynamis-Jeuno, with your lottery ticket in hand, proceed to slaughter any and all mobs in hopes that any of the NMs spawn/are up that drop the boss pop item.
- Give up the slaughtering once you realize that no matter how many mobs you kill, the NMs just won't appear.
- /sigh, rip up that lottery ticket, and leave the zone knowing that dreams won't come true, until......

After pulling this PR down:
- Get more lottery tickets, one of them for sure will have the winning number!
- Zone into Dynamis-Jeuno (preferably on a job that can one-shot any of the PH mobs (to prevent being swarmed with link aggro))
- Proceed to kill, and kill, and kill, and kill, and kill the PHs until finally, you see a mob that you haven't ever seen before (ever since Neo Dynamis was released on DSP), it's one of the Lottery NMs!  
- Kill that Lottery NM before it runs away and hope that it drops the boss pop item (because otherwise you'll have to return to killing the PHs so that one of the Lottery NMs may spawn again).
- Rest easy once one of the Lottery NMs drops the boss pop item.
- Go kill the zone boss, obtain the trophy KI, leave the zone, go to the nearest convenience store and redeem your winning lottery ticket then begin the trek to the Northlands.....you should probably buy some warm-weather outfits with the money from the winning lottery ticket, it's pretty cold up there!

### CODE REVIEW

**Comment by PrettzL** [comment]
Hell yeah brother.

**Review by TeoTwawki — APPROVED** [review]
***STAMP***

Would also accept temp commenting out the "extra" non NM mobs -or- making those mobs lotto off each other as a temp measure, as a separate pr (not combined to this one, so that a revert could be used later)

**Review by PrettzL — APPROVED** [review]

**Review by claywar — APPROVED** [review]

**Comment by EpicTaru** [comment]
> _**STAMP**_
> 
> Would also accept temp commenting out the "extra" non NM mobs -or- making those mobs lotto off each other as a temp measure, as a separate pr (not combined to this one, so that a revert could be used later)

Ay, this is just the beginning!

**Comment by ManuelFranco1113** [comment]
I just want to say Thank You to everyone who supported me through the years. My name is Manuel Franco, New Berlin, Wisconsin. My story of how I won the Powerball lottery of $768.4M is a bit of a tale. I have been playing Powerball tickets for 6 years now since I turned 18. I bought my first ticket on my 18 birthday. I was feeling very lucky that day because I had contacted Dr. Odunga Michael to help me with the winning Powerball numbers. I really had that great great feeling that I looked at the camera wanting to wink at it. I only did a tiny part of it and trusted him. He gave me the numbers after I played a couple other tickets along with it for $10. I checked my ticket after the winnings came online and saw the numbers were correct including the Power play. I screamed for about 10 minutes because it felt like a dream. I had won $768.4M. You can check my winning testimony with the lottery officials just with my name search. Thank you Dr Odunga. Well, his email is [odungaspelltemple@gmail.com](mailto:odungaspelltemple@gmail.com) and you can also call or Whats-app him at +2348167159012 so you guys can contact him

**Pull request merged**
